### ISSUE TITLE
[Bug]: Getting node:events:492 write EPIPE error

### ISSUE THREAD

**Issue by moshere-cirm** [microsoft/playwright-python#2454] opened 2024-05-30 08:02 UTC
### Version

1.40.0

### Expected behavior

Scraping running successfully.

### Actual behavior

However from time to time getting the following error and all the process is being killed.

```
node:events:492  throw er; // Unhandled 'error' event 
Error: write EPIPE at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)
Emitted 'error' event on Socket instance at: 
at emitErrorNT (node:internal/streams/destroy:151:8)
at emitErrorCloseNT (node:internal/streams/destroy:116:3)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
errno: -32,
code: 'EPIPE',
syscall: 'write'

```
[https://hastebin.com/share/exuwozijat.yaml
](url)

Looked into our code and it contains close for browser and page.
```

    async def run_function_for_browser(self, function, **kwargs):
        retries_left = self._retries + 1
        async with async_playwright() as playwright:
            browser = await playwright.chromium.connect_over_cdp(self.SBR_WS_CDP)   # Todo: better reuse browser and create context per each task
            page = await browser.new_page()
            page.set_default_timeout(self._timeout)
            try:
                while True:
                    retries_left -= 1
                    if retries_left:
                        try:
                            self.check_connection(browser)
                            return await function(page, **kwargs)
                        except TimeoutError:
                            self._log.error(f'Time out error, retries left: {retries_left}')
                            continue
                        except InvalidSessionException as e:
                            self._log.error(f'Invalid session caught, retries left: {retries_left}\n{e}')
                            continue
                        except Exception as e:
                            self._log.error(f"Playwright Scraping Browser Failed, retries left: {retries_left}. {e}")
                    else:
                        break
            except Exception as e:
                self._log.error(f"Playwright Scraping Browser Failed, no more retries. {e}")
                raise e
            finally:
                await page.close()
                await browser.close()
```

Also looked into the described bug here: [https://github.com/microsoft/playwright-python/issues/2275](url)
And seems not related to our situation.

Any option to wrap this error and recover from this as our process is killed after this crash?

thank you

### Environment

```Text
Docker on AWS EC2
- Operating System: [ubuntu:20.04]
- CPU: [NA]
- Browser: [Chromium]
- Python Version: [3.8.6]
- Other info:
```

**Comment by mxschmitt** [comment] 2024-06-02 13:25
We unfortunately need more details in order to look into bugs like this. Would it be possible to provide a reproduction which we can run locally?

**Comment by moshere-cirm** [comment] 2024-06-03 14:11
Thanks.
It'll be more complex to share the exact code that simulates it.
Meanwhile I've a question.
is there an option to restart the Node process in case of failure without crashing the whole playwright python app?

**Comment by mxschmitt** [comment] 2024-06-06 18:27
> is there an option to restart the Node process in case of failure without crashing the whole playwright python app?

Unfortunately not. Since we expect the Node.js to always stay open during a Playwright "session". If it terminates, its usually a bug somewhere.

**Comment by mxschmitt** [comment] 2024-06-17 10:22
I'll close it in the meantime until we have a reproduction as part of the triage process - feel free to re-file if you have more details etc. Thanks!

**Closed by mxschmitt** 2024-06-17 10:22 UTC
