### ISSUE TITLE
EPERM: operation not permitted

### ISSUE THREAD

**Issue by ywlfff** [microsoft/playwright-python#404] opened 2020-12-27 12:08 UTC
What does it mean that errors occasionally occur at runtime?

[Error: EPERM: operation not permitted, unlink 'C:\Users\ADMINI~1\AppData\Local\Temp\playwright_chromiumdev_profile-74j3Xb\CrashpadMetrics-active.pma'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'unlink',
  path: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\playwright_chromiumdev_profile-74j3Xb\\CrashpadMetrics-active.pma'
}
127.0.0.1 - - [27/Dec/2020 20:02:16] "POST /login HTTP/1.1" 200 -

**Comment by mxschmitt** [comment] 2020-12-28 13:24
Sounds like a duplicate of https://github.com/microsoft/playwright/issues/4780 (upstream issue).

**Comment by pavelfeldman** [comment] 2021-01-14 22:53
Yup, looks like dupe, let's track it there.

**Closed by pavelfeldman** 2021-01-14 22:53 UTC
