### ISSUE TITLE
Where can i find this dictionary?

### ISSUE THREAD

**Issue by jmartle** [microsoft/playwright-python#638] opened 2021-04-22 03:19 UTC
this: https://github.com/microsoft/playwright/blob/b4209e9dc80e6226f6b173ab77f0390a809964a2/src/deviceDescriptors.ts

it is from the Node.js verison of Playwright. but where can i find this dict in the Python version?

**Comment by mxschmitt** [comment] 2021-04-22 09:08
Closed as duplicate of https://github.com/microsoft/playwright/issues/6263

**Closed by mxschmitt** 2021-04-22 09:08 UTC
