### ISSUE TITLE
[BUG]I have installed Python 3.10 environment with Anaconda and then installed Playwright. However, when activating the Playwright environment in the command prompt (powershell) and trying to run the playwright command, there is no response. 

### ISSUE THREAD

**Issue by libp** [microsoft/playwright-python#2228] opened 2024-01-08 07:51 UTC
### System info
- Playwright Version: [playwright==1.40.0]
- Operating System: [Windows 10]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:
- Additionally, when running a Playwright demo script (demo.py), you encounter the following error:
(playwright) PS C:\Users\peng\git\playwright> python demo.py
Traceback (most recent call last):
  File "C:\Users\peng\git\playwright\demo.py", line 3, in <module>
    with sync_playwright() as p:
  File "C:\Users\peng\.conda\envs\playwright\lib\site-packages\playwright\sync_api\_context_manager.py", line 79, in __enter__
    playwright = self._playwright
AttributeError: 'PlaywrightContextManager' object has no attribute '_playwright'
Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<Connection.run.<locals>.init() running at C:\Users\peng\.conda\envs\playwright\lib\site-packages\playwright\_impl\_connection.py:273> wait_for=<Future finished result=None> cb=[ProtocolCallback.__init__.<locals>.cb() at C:\Users\peng\.conda\envs\playwright\lib\site-packages\playwright\_impl\_connection.py:194]>
Future exception was never retrieved
future: <Future finished exception=Exception('Connection closed while reading from the driver')>
Exception: Connection closed while reading from the driver
Future exception was never retrieved
future: <Future finished exception=BrokenPipeError(32, '管道正在被关闭。', None, 232, None)>
Traceback (most recent call last):
  File "C:\Users\peng\.conda\envs\playwright\lib\asyncio\proactor_events.py", line 401, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
  File "C:\Users\peng\.conda\envs\playwright\lib\asyncio\windows_events.py", line 548, in send
    ov.WriteFile(conn.fileno(), buf)
BrokenPipeError: [WinError 232] 管道正在被关闭。

### Source code
from playwright.sync_api import Playwright,sync_playwright

with sync_playwright() as playwright:
    browser = playwright.chromium.launch(channel='chrome', headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto('https://baidu.com')
    page.wait_for_load_state('networkidle')
    page.screenshot(path='example.png')
    browser.close()

**Comment by libp** [comment] 2024-01-09 05:21
![image](https://github.com/microsoft/playwright-python/assets/16248888/a82b5e5b-974b-416d-a905-21e0150d196d)
print none

**Comment by libp** [comment] 2024-01-09 05:24
If I install Playwright using pip, the result is the same. Could it be related to my environment variables? Why is there no response when I enter 'playwright,' but when I use 'import playwright,' everything works fine?

By the way, looking at your avatar, you must be a handsome and wise individual. Before moving on, I sought your assistance and had a pleasant resolution to the previous question. I hope this issue can be resolved just as smoothly.

**Comment by mxschmitt** [comment] 2024-01-09 12:37
Could you try running `chcp 437`? This might make it work while we implement a permanent fix. Environment variables are most likely not the cause for this.

It seems that the underlying driver we use fails to launch, thats why the CLI and normal Playwright API is not working as expected.

> but when I use 'import playwright,' everything works fine?

According to https://github.com/microsoft/playwright-python/issues/2228#issue-2071031573 the normal API is also not working if I understand it correctly or does it work now?

**Comment by libp** [comment] 2024-01-10 00:56
![image](https://github.com/microsoft/playwright-python/assets/16248888/da6f005e-d12a-4cb0-9b95-9698dfdfc7a9)
After setting it to 437, there was no effect.   
The same error persists.
The normal API is also not working

**Comment by mxschmitt** [comment] 2024-01-10 15:20
Could you try the following? In your case its not `playwright.sh` its `playwright.cmd` instead.

<img width="872" alt="image" src="https://github.com/microsoft/playwright-python/assets/17984549/924ecfbd-47d3-4388-8825-422fe106a673">

What this does / I did: Start a Python REPL, import Playwright, just evaluate `playwright` so we know where the module is installed, use the module path, add the `driver` directory to it, and start the internal driver via that, so we see what happens if you start the driver directly. The driver is also the same as the CLI, so things like `--version` work.

I hope that this gives us a clue on why its not working on your environment. If it still prints nothing, try to execute just `node.exe`. In my example above it would be:

`/Users/maxschmitt/Developer/playwright-python/playwright/driver/node.exe`

**Comment by libp** [comment] 2024-01-11 01:32
![image](https://github.com/microsoft/playwright-python/assets/16248888/84882688-bfb4-40ba-9da8-6815b075d22d)
The same error persists.

**Comment by libp** [comment] 2024-01-11 10:17
I possess two computers—one with the Playwright environment already installed and another without. I duplicated the Python environment from the computer with the Playwright setup, then proceeded to extract it into the Conda "env" directory on the second computer. However, when executing Playwright on the latter machine, disparate outcomes were observed, as depicted in the following image.

![image](https://github.com/microsoft/playwright-python/assets/16248888/ed0efb8e-0c68-44ed-9796-986d7d6bbbb9)

**Comment by libp** [comment] 2024-01-15 07:26
Additional Inquiry:

I have an additional question. I've noticed that the effectiveness of page.wait_for_load_state() doesn't seem to match that of page.wait_for_timeout(3000). When utilizing page.wait_for_load_state(), it appears that the script doesn't genuinely wait for the completion of requests as expected. Any insights into this discrepancy?

**Comment by mxschmitt** [comment] 2024-01-15 19:56
Maybe conda environments are not designed to copy them from one machine to another machine? I tried to reproduce the issue and was not able to on my Windows machine - can you maybe share exact reproduction steps?

Normally there should never be a need for `wait_for_load_state` or `wait_for_timeout`. Playwright's clicks/assertions/fills wait until the element is on the page and is ready to use etc. They also retry. Could you maybe share exact steps of whats not working?

**Comment by libp** [comment] 2024-01-17 05:18
Regarding the issue with wait_for_load_state or wait_for_timeout, it could be attributed to the testing platform's relatively antiquated nature, featuring multiple frames within its pages. Simultaneously, upon clicking a particular button, a gradually fading popup emerges, making it inconvenient for me to precisely locate elements. Consequently, I find it necessary to rely on wait_for_timeout to avoid potential errors or ineffective clicks. For now, let's set this matter aside. Thank you for your understanding.

**Comment by mxschmitt** [comment] 2024-01-18 09:08
Great discovery! I'm very happy for you that you found the root cause!

I'm going to close it for now, since the main issue has been solved - don't hesitate to file a new issue for further bug reports.

**Closed by mxschmitt** 2024-01-18 09:08 UTC
