### ISSUE TITLE
When I use route.fullfill to set multiple set-cookies in headers, only one succeeds

### ISSUE THREAD

**Issue by oldlwhite** [microsoft/playwright-python#493] opened 2021-02-11 07:12 UTC
set-cookies     
_m_h5_tk=bddc5856aa21544fa74f467c96df2844_1613035576047;Path=/;Domain=taobao.com;Max-Age=604800;SameSite=None;Secure, _m_h5_tk_enc=2d7b6618ab66811ebabdd035d9ed9ff7;Path=/;Domain=taobao.com;Max-Age=604800;SameSite=None;Secure

I have modified the source code

```
    async def fulfill(
        self,
        status: int = None,
        headers: Dict[str, str] = None,
        body: Union[str, bytes] = None,
        path: Union[str, Path] = None,
        contentType: str = None,
    ) -> None:
        params = locals_to_params(locals())
        length = 0
        if isinstance(body, str):
            params["body"] = body
            params["isBase64"] = False
            length = len(body.encode())
        elif isinstance(body, bytes):
            params["body"] = base64.b64encode(body).decode()
            params["isBase64"] = True
            length = len(body)
        elif path:
            del params["path"]
            file_content = Path(path).read_bytes()
            params["body"] = base64.b64encode(file_content).decode()
            params["isBase64"] = True
            length = len(file_content)

        headers = params.get("headers",{})

        if params.get("contentType"):
            headers["content-type"] = params["contentType"]
        elif path:
            headers["content-type"] = (
                mimetypes.guess_type(str(Path(path)))[0] or "application/octet-stream"
            )
        if length and "content-length" not in headers:
            headers["content-length"] = str(length)
            
        params["headers"] = [{"name":name,"value":value} for name in headers.keys() for value in headers.get_list(name)]
        await self._channel.send("fulfill", params)
```
When I modified the source code, I successfully set multiple cookies

**Comment by mxschmitt** [comment] 2021-02-11 07:44
Seems like a duplicate of #4987

**Comment by mxschmitt** [comment] 2021-02-11 22:56
Could you provide the function call how you call route.fulfill?

Might be connected to https://github.com/microsoft/playwright/issues/4987

**Comment by pavelfeldman** [comment] 2021-02-11 23:27
Mind uploading a pull request?

**Comment by mxschmitt** [comment] 2021-05-12 21:20
Closed for now since we are following the upstream implementation. If you still experience issues, please submit a reproducible script, thanks!

**Closed by mxschmitt** 2021-05-12 21:20 UTC
Labels: P3-collecting-feedback
