### ISSUE TITLE
Invalid handle

### ISSUE THREAD

**Issue by nubonics** [microsoft/playwright-python#599] opened 2021-03-24 16:19 UTC
compiled via pyinstaller with --windowed
```
Task exception was never retrieved
future: <Task finished name='Task-441' coro=<Connection.run() done, defined at playwright\_impl\_connection.py:163> exception=OSError(9, 'The handle is invalid', None, 6, None)>
Traceback (most recent call last):
  File "playwright\_impl\_connection.py", line 166, in run
  File "playwright\_impl\_transport.py", line 60, in run
  File "asyncio\subprocess.py", line 236, in create_subprocess_exec
  File "asyncio\base_events.py", line 1630, in subprocess_exec
  File "asyncio\windows_events.py", line 389, in _make_subprocess_transport
  File "asyncio\base_subprocess.py", line 36, in __init__
  File "asyncio\windows_events.py", line 885, in _start
  File "asyncio\windows_utils.py", line 153, in __init__
  File "subprocess.py", line 808, in __init__
  File "subprocess.py", line 1182, in _get_handles
OSError: [WinError 6] The handle is invalid
```

**Comment by mxschmitt** [comment] 2021-03-30 08:09
Duplicate of #513

**Comment by pavelfeldman** [comment] 2021-03-30 17:30
Closing as a dupe

**Closed by pavelfeldman** 2021-03-30 17:30 UTC
