### ISSUE TITLE
[Issue]: Not able to open some working URLs via Playwright-python.

### ISSUE THREAD

**Issue by nitin-g2** [microsoft/playwright-python#1861] opened 2023-04-14 07:35 UTC
Hey, I am using playwright-python to open some URLs in headless mode. I am using Chromium headless browser but it is not opening those URLs however they are valid URLs and I am able to open them in the Google Chrome browser.
For example data.com, mediamath.com I am getting timeout after 30 seconds.
Here is my code:

url = "https://data.com" # tried http://data.com as well
playwright = sync_playwright().start()
self.browser = playwright.chromium.launch(headless=True)
self.context = self.browser.new_context()
self.page = self.context.new_page()
self.response = self.page.goto(url)

So that you know, I am using a single browser instance to open all the URLs.
Please help

**Comment by mxschmitt** [comment] 2023-04-14 09:53
This is mos likely caused by bot protection from their side. These two sites are also not working from my device, even without Playwright. Since we can't act on that, I unfortunately have to close it.

**Closed by mxschmitt** 2023-04-14 09:53 UTC

**Comment by nitin-g2** [comment] 2023-04-14 09:59
Thanks @mxschmitt for your reply. I am able to open those without Playwright. I am not sure I completely understand this, By bot protection you mean they are not allowing these tools or scripts to open these sites, am I correct?
