### ISSUE TITLE
[Bug]: Extensions is don't work.

### ISSUE THREAD

**Issue by uamind** [microsoft/playwright-python#2457] opened 2024-06-02 09:18 UTC
### Version

1.44.0

### Steps to reproduce

Example steps (replace with your own):
1. download "Proxy SwitchyOmega" and unpack
2. use extensions
3. python test.py
4. You should see the error come up

### Expected behavior

Can set proxy 

### Actual behavior

Can't set proxy

### Additional context

code:with sync_playwright() as p:
            plugin_path = os.path.join(plugin_path,'SwitchyOmega')
            userData = os.path.join(PATH,'userdata')
            browser = p.chromium.launch_persistent_context(
                user_data_dir=userData,
                executable_path=chromePath,
                headless=False,
                args=[
                    f'--disable-extensions-except={plugin_path}',
                    f'--load-extension={plugin_path}',
                    "--disable-application-cache",
                    "--disk-cache-size=0",
                    "--media-cache-size=0",
                    "--disable-gpu-shader-disk-cache",
                    "--disable-blink-features=AutomationControlled",
                    "--disable-geolocation",
                    "--no-sandbox",
                    "--disable-web-security",
                    "--allow-running-insecure-content",
                    "--disable-extensions",
                    "--disable-infobars",
                    f"--window-position={x},{y}",
                ],
                user_agent=device,
                viewport={'width': 500, 'height': 500},
            )  
            page = browser.new_page()
            jspath = os.path.join(path,'js/stealth.min.js')
            with open(jspath) as f:
                js = f.read()
                page.add_init_script(js)
            page.add_init_script("""
            Object.defineProperty(navigator, 'deviceMemory', {
                    get: () => 8
            });""")
            try:
               page.goto(url,wait_until="domcontentloaded",timeout=180000)

### Environment

```Text
- Operating System: [Windows 11]
- CPU: [AMD64]
- Browser: [Chromium 123.0.6312.4]
- Python Version: [3.11.8]
- Other info:
```

**Comment by uamind** [comment] 2024-06-02 09:21
use playwright :
![image](https://github.com/microsoft/playwright-python/assets/52064273/72cc7854-0839-49ea-8ae9-dbb80b4e2680)
norm start:
![image](https://github.com/microsoft/playwright-python/assets/52064273/005464ab-1b41-4720-9488-41022d13e21f)

**Comment by mxschmitt** [comment] 2024-06-06 21:00
I'm not familiar with the extension. I'd try the following things:

1. Does it reproduce without the stealth plugin?
2. Have tried launching Chromium manually and load the unpacked extension - does it work there? This would help us to find out if its actually a Playwright bug or just a Chromium issue. You can get all the arguments by setting the `DEBUG=pw:browser` environment variable.

**Comment by mxschmitt** [comment] 2024-06-17 10:23
I'll close it for now, since this does not look like a bug in Playwright and as per above.

**Closed by mxschmitt** 2024-06-17 10:23 UTC
