### ISSUE TITLE
[Question]: Cloudflare 403 Forbidden 

### ISSUE THREAD

**Issue by Nevea-web** [microsoft/playwright-python#1396] opened 2022-07-01 15:17 UTC
### Your question

Hello everyone, I'm sending a request
```
headers ={
'Accept-Encoding': 'gzip, deflate, br',
'Host': "api.alien worlds.io ",
"User Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"
}
response=context.request.get("https://api.alien worlds.io/v1/alienworlds/mines " ,headers=headers)
response.status >>403
```
I get a 403 response
I make exactly the same request via
```
response= http.request('GET', 'https://api.alien worlds.io/v1/alienworlds/minus ',headers=headers)
response.status >>200
```
I get the answer 200
headers are the same, but if you look in debug
it can be seen that playwright changes the headers .
to
```
headers={
"user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0",
"accept-encoding": "gzip, deflate, br",
"host": "api.alienworlds.io",
}
```
how can this be fixed?

**Comment by mxschmitt** [comment] 2022-07-12 16:02
This is most likely caused by the Cloudflare bot protection / web application firewall. You can check your request headers e.g. here: https://httpbin.org/headers

Since this is nothing which can be fixed on Playwright side, we can't act on it. If you have a concrete bug report for us with a repro, please file a new issue, thanks!

**Closed by mxschmitt** 2022-07-12 16:02 UTC

**Comment by gorkemhacioglu** [comment] 2023-10-25 22:26
I am having the same issue, any solution would be great?
[neveatears](https://github.com/neveatears)
