### ISSUE TITLE
Popup from popup not work

### ISSUE THREAD

**Issue by hsk20011** [microsoft/playwright-python#1970] opened 2023-06-13 07:18 UTC
### Your question

from popop page3, when push a button new popup page4 is expected, but not work

            with page.expect_popup() as page3_info:
                page.frame_locator("iframe[name=\"ifm_TDM396\"]").get_by_role("link", name="판매상태변경").first.click()
            page3 = page3_info.value
            page3.get_by_label("모두").check()
            page3.close()
            with page3.expect_popup() as page4_info:
                page3.get_by_role("link", name="판매중지").click()
            page4 = page4_info.value
            page4.close()
            page4.get_by_role("link", name="확인").click()

 error message >>
    async with page3.expect_popup() as page4_info:
  File "C:\WPy64-31050\YHB\venv\lib\site-packages\playwright\_impl\_async_base.py", line 53, in __aexit__
    await self._event.value
  File "C:\WPy64-31050\YHB\venv\lib\site-packages\playwright\_impl\_async_base.py", line 34, in value
    return mapping.from_maybe_impl(await self._future)
playwright._impl._api_types.Error: Page closed
=========================== logs ===========================
waiting for event "popup"
============================================================

**Comment by mxschmitt** [comment] 2023-06-16 08:39
Since this issue does not include any reproducible, we have to close it. Please re-file with more details, otherwise we can't act on it. Thanks for your understanding!

**Closed by mxschmitt** 2023-06-16 08:39 UTC
