### ISSUE TITLE
[BUG] Context cannot be closed when HAR File Record is Enabled

### ISSUE THREAD

**Issue by rvoak** [microsoft/playwright-python#1881] opened 2023-04-25 14:52 UTC
### System info
- Playwright Version: 1.32.1
- Operating System: macOS
- Browser: Chromium
- Other info:

### Source code

```python
from playwright.sync_api import Playwright, sync_playwright

def main(playwright: Playwright) -> None:

    # Change the URL here
    URL = "https://hindilinks4u.kim/ant-man-and-the-wasp-quantumania-2023-hindi-dubbed-Watch-online/"

    # Set up the browser context
    context = playwright.chromium.launch_persistent_context(
        headless=False,
        user_data_dir = extension_dir,
        devtools = True,
        record_har_path = "{}/harfile.har".format(directory),
        args=[
                "--headless=new",
                "--disable-extensions-except={}".format(ext_file),  # Launch browser with my own extension
                "--load-extension={}".format(ext_file)
             ],
    )

    # Navigate to the webpage
    page = context.new_page()
    page.goto(URL)

    # Define the number of rows and columns in the grid
    num_rows = 10
    num_cols = 10

    # Find the dimensions of the grid
    grid_width = page.evaluate("() => document.documentElement.scrollWidth")
    grid_height = page.evaluate("() => document.documentElement.scrollHeight")

    # Calculate the width and height of each cell in the grid
    cell_width = grid_width // num_cols
    cell_height = grid_height // num_rows

    # Loop through each cell in the grid
    for row in range(num_rows):
        for col in range(num_cols):
            # Calculate the coordinates of the cell
            x = col * cell_width
            y = row * cell_height

            # Move the mouse to the cell and click it
            page.mouse.move(x, y)
            page.mouse.click(x, y)

            print("Clicked {}, {}".format(x,y))

            # Wait for a short period of time
            page.wait_for_timeout(1000)
            print("Done Waiting!")

    # Clean up
    print("Closing pages....")
    for p in context.background_pages:
        p.close()
    print("Closed Pages")
    print("Closing Context....")
    context.close() # THIS IS STUCK!
    print("Closed context.....")

# Execute
with sync_playwright() as playwright:
    main(playwright)
```

**Expected**

The context is closed and the program terminates gracefully.

**Actual**

The program is stuck on the ```context.close()``` call. This does not happen if the HAR file recording is disabled.

**Comment by mxschmitt** [comment] 2023-05-02 12:50
Looks like the loaded Chrome Extension is critical to reproduce this bug. Do you mind sharing it with us?

I tried the following inside our repository which was working for me:

```py
from pathlib import Path
from playwright.sync_api import Playwright, sync_playwright


def main(playwright: Playwright) -> None:
    extension_path = str(
        Path("/Users/maxschmitt/Developer/playwright-python/tests/assets")
        / "simple-extension"
    )
    # Change the URL here
    URL = "https://hindilinks4u.kim/ant-man-and-the-wasp-quantumania-2023-hindi-dubbed-Watch-online/"

    # Set up the browser context
    context = playwright.chromium.launch_persistent_context(
        headless=False,
        user_data_dir="",
        devtools=True,
        record_har_path="harfile.har",
        args=[
            "--headless=new",
            "--disable-extensions-except={}".format(
                extension_path
            ),  # Launch browser with my own extension
            "--load-extension={}".format(extension_path),
        ],
    )
    # Navigate to the webpage
    page = context.new_page()
    page.goto(URL)

    # Define the number of rows and columns in the grid
    num_rows = 10
    num_cols = 10

    # Find the dimensions of the grid
    grid_width = page.evaluate("() => document.documentElement.scrollWidth")
    grid_height = page.evaluate("() => document.documentElement.scrollHeight")

    # Calculate the width and height of each cell in the grid
    cell_width = grid_width // num_cols
    cell_height = grid_height // num_rows

    # Loop through each cell in the grid
    for row in range(num_rows):
        for col in range(num_cols):
            # Calculate the coordinates of the cell
            x = col * cell_width
            y = row * cell_height

            # Move the mouse to the cell and click it
            page.mouse.move(x, y)
            page.mouse.click(x, y)

            print("Clicked {}, {}".format(x, y))

            # Wait for a short period of time
            page.wait_for_timeout(1000)
            print("Done Waiting!")

    # Clean up
    print("Closing pages....")
    for p in context.background_pages:
        p.close()
    print("Closed Pages")
    print("Closing Context....")
    context.close()  # THIS IS STUCK!
    print("Closed context.....")


# Execute
with sync_playwright() as playwright:
    main(playwright)

```

**Comment by rvoak** [comment] 2023-05-02 22:46
I tried it without the extension -- and it still does not work for me! The ```context.close()``` remains stuck.

**Comment by mxschmitt** [comment] 2023-05-06 08:43
Did you try my reproducible? Since yours was not runnable for me. You are not using Google Chrome / Microsoft Edge, so company enterprise policies should not apply.

Which macOS version are you using? It might be caused by geolocation based differences in terms of what the website is serving, since I'm from Germany.

**Comment by mxschmitt** [comment] 2023-05-17 22:14
@rvoak any updates? Otherwise we unfortunately need to close this, since we can't reproduce and we cannot act on it.

**Comment by rvoak** [comment] 2023-05-22 14:37
Here is the extension: https://github.com/hadiamjad/WebCheck/tree/click-hijacking

**Comment by mxschmitt** [comment] 2023-08-11 09:50
Sorry for the late reply. What I can observe with the latest version is that Chromium crashes, but this seems unrelated to your context cannot be closed issue.

I got a crash report ID for it, pinged someone at Google about it if they have a crbug for it already, if not, I'll file it at crbug, but the repro is kinda convoluted and I can only reproduce it on macOS.

Uploaded crash report ID:	6832872cc57a6946

**Closed** 2023-10-04 14:15 UTC
Labels: triaging
