### ISSUE TITLE
[BUG] Stuck in waiting —— with sync_playwright() as p

### ISSUE THREAD

**Issue by thx2199** [microsoft/playwright-python#1931] opened 2023-05-20 08:38 UTC
**Context:**
- Playwright Version: 1.33.0
- Operating System: Windows11
- Python version: 3.10.11
- Browser: All
- Extra: It was supposed to work, but after anaconda uninstalled Python 3.10.10, it became unusable after installing the global Python 3.10.11.

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally.

```python
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    browser = p.chromium.launch(headless=False,slow_mo=100)
    context1 = browser.new_context() 
    page1 = context1.new_page()
    # ...
    browser.close()
```

**Describe the bug**

The program needs to wait indefinitely when executing 
with sync_playwright() as p: 
or 
p = sync_playwright().start(), 
and the browser cannot be opened.
But it can be performed normally in cmd 
playwright codegen --target python -o #....
It's just that the Python API can't dispatch the browser.

**Comment by pscj** [comment] 2023-05-20 10:57
same version and  same question.

**Comment by thx2199** [comment] 2023-05-24 12:12
I didn't change it, and after two days it was working normally.

**Comment by mxschmitt** [comment] 2023-05-26 00:09
We are unfortunately so far not able to reproduce this. Would it be possible to set the `DEBUGP=1` environment variable while you try to use Playwright? Which might yield to more useful debugging output.

**Comment by mxschmitt** [comment] 2023-06-21 09:15
Closing as part of the triage process, since we unfortunately are not able to reproduce this. Feel free to file a new issue with the debug output request above.

**Closed by mxschmitt** 2023-06-21 09:15 UTC
Labels: triaging
