### ISSUE TITLE
[Bug]: Cannot create chromium incognito context with playwright 1.41 and forward

### ISSUE THREAD

**Issue by phillip-morrow** [microsoft/playwright-python#2504] opened 2024-07-30 19:15 UTC
### Version

1.41.0 - 1.45.1

### Steps to reproduce

Steps:
1. First install `1.40`
2. Create a new browser context
3. Note that the new browser context is in incognito mode
4. Uninstall `1.40` and install `1.41-1.45`
5. Note that the new browser context is not in incognito mode

Notes: I have followed the documentation.  I've tried using the default context and creating a completely new browser context with `browser.new_context()` <-- new incognito session `context.new_page()`.

Currently, with 1.40, we're completely stable using the stealth plugin.  However, since versions 1.41 and forward do not start incognito, stealth is behaving oddly and some network traffic is being blocked.

### Expected behavior

I expect new chromium contexts to default to incognito mode.

### Actual behavior

All new contexts are non-incognito for the chromium binaries that ship with playwright versions 1.41 and forward.

### Environment

```Text
- Operating System: [Ubuntu 22.04][Mac OS 14.5]
- CPU: [Intel]
- Browser: Chromium
- Python Version: [3.9]
```

**Comment by mxschmitt** [comment] 2024-07-30 19:25
> do not start incognito

how do you observe the change in the behaviour? 

In the web platform there is no such thing as incognito or not. Playwright's BrowserContexts are fully isolated from each-other. If you mean that the browser window does not have "Incognito" at the top right anymore, this is just a pure UI change - the underlying context is still isolated.

**Comment by phillip-morrow** [comment] 2024-07-30 19:29
If I pause in debug and manually open incognito mode in a new window, the new window is then incognito and resembles how a fresh browser context opens in 1.40.0 and prior by default.

**Comment by mxschmitt** [comment] 2024-07-31 07:36
Do you mind elaborating on "the new window is then incognito"? If you perform manual actions with the browser like opening tabs or new windows, this is outside of our control. Only new_page/new_context are supported there to launch new tabs etc.

In the web platform there is no such thing as incognito or not. The website aka. JavaScript etc. can't tell. Only the Chromium UI has changed slightly and does not mention "Incognito" anymore.

The documentation is still correct and aligns with how recent versions, including v1.41 and forward behave.

**Comment by phillip-morrow** [comment] 2024-07-31 14:27
Absolutely.  First, let me say thank you for chiming in here.  I want to make sure it's perfectly understood that I'm very clearly saying that it is **_not_** a "UI change in chromium" and following the public facing documentation or otherwise, there is currently no way to open a chromium browser in incognito mode.

The point I made about opening the incognito window manually in the binary shipped with version 1.41 is to prove that it is not a UI change in chromium.

It is immediately an observable change in behavior between 1.40 and 1.41 by looking at the new windows opened while running tests headed.

1.41 by default and following the python binding's documentation for an incognito browser session
![image](https://github.com/user-attachments/assets/5aedb1b2-8467-40c4-8690-5174f40c15b6)

1.40 by default and following the python binding's documentation for an incognito browser session
![image](https://github.com/user-attachments/assets/50e7cbd3-0927-4aae-ae11-4daf37717125)

While yes, in both modes it is the same V8 engine, the big difference is the browser is now saving:
 - history
 - cookies
 - cache

We can even follow up and prove that the session is not incognito by checking:
```local_storage = await page.evaluate("window.localStorage")
    session_storage = await page.evaluate("window.sessionStorage")
    cookies = await page.context.cookies()```

☝️ all of which should be empty for each session and they are not.
 
That means the next time the binary is opened, the user session from the previous test is still active.  This means to support 1.41 and forward, I would be required to write additional code to clear all of that for each session before fetching the intended context file or logging in if that does not exist.

**Comment by mxschmitt** [comment] 2024-07-31 14:36
> We can even follow up and prove that the session is not incognito by checking:

Do you mind providing me a full script where I can observe that behaviour? I was running the following which was working fine for me:

```python
from playwright.sync_api import sync_playwright

with sync_playwright() as playwright:
    browser = playwright.chromium.launch()

    context1 = browser.new_context()
    page1 = context1.new_page()
    page1.goto('http://example.com')
    page1.evaluate('window.localStorage.setItem("name", "value")')
    page1.reload()
    print(f"This should be 'value': {page1.evaluate('window.localStorage.getItem("name")')}")

    context2 = browser.new_context()
    page2 = context2.new_page()
    page2.goto('http://example.com')
    print(f"This should be 'None': {page2.evaluate('window.localStorage.getItem("name")')}")

    browser.close()
```

**Comment by phillip-morrow** [comment] 2024-07-31 15:30
We're currently using playwright pytest, so we use fixtures with scopes.  In asking me to provide the code you forced me to 🦆 rubber duck debug something:

## My mistake
Incorrectly creating browser context with `session` scope, the context was the same for every test function.
```
@pytest.fixture(scope="session")
def incognito_browser_context(browser_context_args):
    with sync_playwright() as p:
        browser = p.chromium.launch() 
        context = browser.new_context()  
        yield context
        context.close()
        browser.close()
```

```
@pytest.fixture(scope="function")
def page(incognito_browser_context):
    page = incognito_browser_context.new_page()
    apply_stealth(page)
    yield page
    page.close()
```

Now context creation has been moved to its own fixture with `function` scope while the browser is still defined with `session` scope and the contexts are now truly isolated as you have suggested.

```
@pytest.fixture(scope="function")
def context(browser):
    context = browser.new_context()
    yield context
    context.close()
```

The problem was observable between two tests when the new session had cookies from the prior test.

While the problem of sharing context between tests has now been addressed, I still believe there's a bug where playwright itself isn't opening incognito chromium browser sessions.  The defect may not be isolated to the python binding itself.   Are there logs or anything that I can provide that might help?

**Comment by mxschmitt** [comment] 2024-07-31 16:10
Awesome, so you were re-using the same context.

> I believe it proves that the browser was continuously reopened without incognito

`incognito_browser_context` was a `session` fixture, which is the same for the whole Pytest test session. So you will have 1 session for all your tests, so localStorage etc. are the same and persisted in-memory. There is also just a single browser.

Under hood they are "OffTheRecord" profiles, which don't persist anything to disk. See e.g. [this Chromium discussion](https://issues.chromium.org/issues/333967644) about it if you are curious, that the upstream UI has been slightly changed to not say "Incognito" for "OffTheRecord" profiles. If you still think there is a bug, we need something we can run locally.

We recommend to use the official pytest-plugin, which uses our best practises (single browser and context per test etc) and has tested fixtures:

- Getting started: https://playwright.dev/python/docs/intro
- Source: https://github.com/microsoft/playwright-pytest

**Comment by phillip-morrow** [comment] 2024-08-01 15:01
Thank you for everything.  The change in UI aligns with your thread with chromium.org.   From what I see in that thread, the OffTheRecord profiles are no longer being handled as incognito.

We can take this conversation to discord, but 1.41 and forward, I notice a few things.   I've run into some issues stability testing the new versions that may be related, but I don't know where to start to provide logs or investigate.

Every now and then, playwright seems to crash with an internal error.  It happens intermittently.  I believe the browser has crashed and playwright is attempting to take a screenshot; which is the source of the internal error.   

Also, the playwright stealth library works intermittently as well.  It appears to be causing network traffic to be blocked.  Not all page assets load and console is ridden with errors because several assets, probably javascript files are now undefined.  That's why I had to create a new browser, context, and page.  Without stealth, I have to manually set a user agent that isn't flagged as a bot running headlessly.

Playwright stealth is stable in `1.40` and becomes unstable in `1.41`.

It appears that something about 1.41 is a breaking change for us and I can't merge it, because it would introduce flake to our pipelines.   I'd really like to help resolve these issues if possible.

**Comment by mxschmitt** [comment] 2024-08-01 18:03
> From what I see in that thread, the OffTheRecord profiles are no longer being handled as incognito.

Yes, from the UI perspective.

> Every now and then, playwright seems to crash with an internal error. It happens intermittently. I believe the browser has crashed and playwright is attempting to take a screenshot; which is the source of the internal error.

This sounds like a different bug. Would appreciate if you could file a separate bug for it with a reproduction etc.

> Also, the playwright stealth library works intermittently as well. 

This is outside of the scope for Playwright since its from a third-party. If you come up with a reproduction which is self-contained (not using stealth) we are more than happy to look into it.

Since this issue seems sorted out for now, I'm going to close it. For the other two, feel free to file separate issues. Thanks for your understanding!

**Closed by mxschmitt** 2024-08-01 18:03 UTC
