### ISSUE TITLE
[BUG] playwright = await async_playwright().start()

### ISSUE THREAD

**Issue by Isfate** [microsoft/playwright-python#2091] opened 2023-09-28 02:12 UTC
**When I load the playwright driver, the following problem occurs**

Task exception was never retrieved
future: <Task finished name='Task-307' coro=<Connection.run() done, defined at /data1/software/anaconda3/envs/vicunaweb/lib/python3.10/site-packages/playwright/_impl/_connection.py:217> exception=NotImplementedError()>
Traceback (most recent call last):
  File "/data1/software/anaconda3/envs/vicunaweb/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 224, in run
    await self._transport.connect()
  File "/data1/software/anaconda3/envs/vicunaweb/lib/python3.10/site-packages/playwright/_impl/_transport.py", line 139, in connect
    raise exc
  File "/data1/software/anaconda3/envs/vicunaweb/lib/python3.10/site-packages/playwright/_impl/_transport.py", line 127, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "/data1/software/anaconda3/envs/vicunaweb/lib/python3.10/asyncio/subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/data1/software/anaconda3/envs/vicunaweb/lib/python3.10/asyncio/base_events.py", line 1675, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/data1/software/anaconda3/envs/vicunaweb/lib/python3.10/asyncio/unix_events.py", line 198, in _make_subprocess_transport
    with events.get_child_watcher() as watcher:
  File "/data1/software/anaconda3/envs/vicunaweb/lib/python3.10/asyncio/events.py", line 803, in get_child_watcher
    return get_event_loop_policy().get_child_watcher()
  File "/data1/software/anaconda3/envs/vicunaweb/lib/python3.10/asyncio/events.py", line 616, in get_child_watcher
    raise NotImplementedError
NotImplementedError
Traceback (most recent call last):
  File "/data1/melo/zyl/webglm/app_fast.py", line 65, in post
    fetch_results = fetcher.fetch(urls)
  File "/data1/melo/zyl/webglm/fetching/__init__.py", line 27, in fetch
    self.loop.run_until_complete(get_raw_pages(urls, close_browser=True))
  File "/data1/software/anaconda3/envs/vicunaweb/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/data1/melo/zyl/webglm/fetching/playwright_based_crawl_new.py", line 50, in get_raw_pages
    context = await get_conetent()
  File "/data1/melo/zyl/webglm/fetching/playwright_based_crawl_new.py", line 27, in get_conetent
    playwright = await async_playwright().start()
  File "/data1/software/anaconda3/envs/vicunaweb/lib/python3.10/site-packages/playwright/async_api/_context_manager.py", line 51, in start
    return await self.__aenter__()
  File "/data1/software/anaconda3/envs/vicunaweb/lib/python3.10/site-packages/playwright/async_api/_context_manager.py", line 46, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
  File "/data1/software/anaconda3/envs/vicunaweb/lib/python3.10/site-packages/playwright/_impl/_transport.py", line 127, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "/data1/software/anaconda3/envs/vicunaweb/lib/python3.10/asyncio/subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/data1/software/anaconda3/envs/vicunaweb/lib/python3.10/asyncio/base_events.py", line 1675, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/data1/software/anaconda3/envs/vicunaweb/lib/python3.10/asyncio/unix_events.py", line 198, in _make_subprocess_transport
    with events.get_child_watcher() as watcher:
  File "/data1/software/anaconda3/envs/vicunaweb/lib/python3.10/asyncio/events.py", line 803, in get_child_watcher
    return get_event_loop_policy().get_child_watcher()
  File "/data1/software/anaconda3/envs/vicunaweb/lib/python3.10/asyncio/events.py", line 616, in get_child_watcher
    raise NotImplementedError
NotImplementedError

**Comment by mxschmitt** [comment] 2023-10-04 12:13
Looks like the wrong event loop is used on your system. Can you provide us a minimal reproducible?

**Comment by mxschmitt** [comment] 2023-10-16 13:26
Closing as per above. Please re-file with more details, thanks!

**Closed by mxschmitt** 2023-10-16 13:26 UTC
Labels: triaging
