### ISSUE TITLE
[Question]: failed to click locator

### ISSUE THREAD

**Issue by garyzhang21** [microsoft/playwright-python#1762] opened 2023-02-14 03:14 UTC
### Your question

![image](https://user-images.githubusercontent.com/32188719/218629599-e2d36d6f-9aae-426c-8249-1ce0bff2dd92.png)
i used the xpath  //*[text()='2534'] , but i found click action not working well. but actually it works by selenium 
what should i do?

**Comment by garyzhang21** [comment] 2023-02-15 10:02
and it is ant design picker for the locator.

**Comment by aslushnikov** [comment] 2023-02-17 13:53
@garyzhang21 what do you mean by "not working well"? What kind of error does it give you?

**Comment by garyzhang21** [comment] 2023-02-20 01:34
> @garyzhang21 what do you mean by "not working well"? What kind of error does it give you?

no error, and no actions when i want to click the label 2534,it is still 2536 displayed in the screenshot.

**Comment by garyzhang21** [comment] 2023-02-21 02:25
i tried. 
![image](https://user-images.githubusercontent.com/32188719/220231660-76478fde-01de-476a-a32c-252b5991e40d.png)
from this picture you can see i already request click function, and it passed, but it does not click the locator that i want.

**Comment by garyzhang21** [comment] 2023-02-21 07:03
I see i already got the reason why not clickable. it is because of not compatible for my component.
btw. actually i set the phone model. and my component is ant design picker for mobile. and if i open the develop tool to select phone again, i can click , so any solution for this point ?
here is my code to set up the device of phone:
       if phone !=None:
            iphone = p.devices[phone]
            context = browser.new_context(**iphone)
            page = context.new_page()

**Comment by garyzhang21** [comment] 2023-02-21 07:39
{'user_agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 14_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Mobile/15E148 Safari/604.1', 'viewport': {'width': 428, 'height': 746}, 'device_scale_factor': 3, 'is_mobile': True, 'has_touch': True, 'default_browser_type': 'webkit'}

this is the detail of iphone.

**Comment by garyzhang21** [comment] 2023-02-21 07:59
chrome version : 
\chromium-1045\chrome-win\chrome.exe> version=110.0.5481.38>

**Comment by mxschmitt** [comment] 2023-02-21 09:10
As you can see in the screenshot there are two elements with the selector. We recommend using [Locators](https://playwright.dev/docs/locators), since they are strict, and throw if the selector does not resolve to 1 element. Maybe you are clicking on the wrong element?

See here about how to debug selectors: https://playwright.dev/python/docs/debug-selectors

**Comment by garyzhang21** [comment] 2023-02-21 10:19
> As you can see in the screenshot there are two elements with the selector. We recommend using [Locators](https://playwright.dev/docs/locators), since they are strict, and throw if the selector does not resolve to 1 element. Maybe you are clicking on the wrong element?
> 
> See here about how to debug selectors: https://playwright.dev/python/docs/debug-selectors

you can see that i click the element that xpath is //*[text()='2534']  
but from the screenshot  2534 can not be selected.
and i found the reason.  it is because of not compatible for my component.
btw. actually i set the phone model. and my component is **ant design picker for mobile**. and if i open the develop tool to select phone again, i can click , so any solution for this point ?

here is my code to set up the device of phone:
if phone !=None:
iphone = p.devices[phone]
context = browser.new_context(**iphone)
page = context.new_page()

and here is the iphone print: 
{'user_agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 14_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Mobile/15E148 Safari/604.1', 'viewport': {'width': 428, 'height': 746}, 'device_scale_factor': 3, 'is_mobile': True, 'has_touch': True, 'default_browser_type': 'webkit'}

**Comment by aslushnikov** [comment] 2023-02-21 15:35
> and i found the reason. it is because of not compatible for my component.

@garyzhang21 Glad to here the issue is resolved. Closing this then.

Do not hesitate to file more issues if you think this we can be helpful though. We will appreciate if you follow issue template next time. Thanks!

**Closed by aslushnikov** 2023-02-21 15:35 UTC
Labels: triaging
