### ISSUE TITLE
[BUG] PDF directly access does not emit download event

### ISSUE THREAD

**Issue by wizpresso-steve-cy-fan** [microsoft/playwright-python#1757] opened 2023-02-09 09:51 UTC
@mxschmitt This is just an example and I will try to do a download interaction based on button click later. As if I clicked a button to download the file, it also uses `goto` behind the scene, so I think both should behave the same, I just want to do a simplification. 

So far, this seems to be working:
```py3
import asyncio
from playwright.async_api import async_playwright
import json
from anyio import Path
from aiofiles.tempfile import TemporaryDirectory

preference = {
    "plugins": {
        "always_open_pdf_externally": True,
    },
}


async def handle(route):
    response = await route.fetch()
    if 'content-type' in response.headers and response.headers['content-type'] == 'application/pdf':
        response.headers['Content-Disposition'] = 'attachment'
    await route.fulfill(response=response, headers=response.headers)


async def main():
    async with TemporaryDirectory() as d:
        preference_dir = Path(d) / "Default"
        await preference_dir.mkdir(777, parents=True, exist_ok=True)
        await (preference_dir / "Preferences").write_text(json.dumps(preference))
        
        async with async_playwright() as p:
            context = await p.chromium.launch_persistent_context(d, headless=False, accept_downloads=True)
            try:
                await context.route("*", handle)
                page = await context.new_page()
                async with page.expect_download() as download_info:
                    try:
                        await page.goto("https://www1.hkexnews.hk/listedco/listconews/gem/2023/0209/2023020900150_c.pdf")
                    except:
                        download = await download_info.value
                        print(await download.path())
            finally:
                await context.close()

asyncio.run(main())

```
Combining the trick on https://github.com/microsoft/playwright/issues/3509#issuecomment-675441299 and https://stackoverflow.com/a/75201448/3289081

My end goal is to capture the PDF download and send the file stream into stdout/remote pipe. 

N.B.
Although I can go without making a persistent context to trigger the PDF download if I go headless, it apparently does not behave well in non-headless mode, so the suggestion at https://github.com/microsoft/playwright/issues/3509#issuecomment-1369299639 is not working.

_Originally posted by @wizpresso-steve-cy-fan in https://github.com/microsoft/playwright/issues/20771#issuecomment-1423910442_

**Comment by mxschmitt** [comment] 2023-02-09 11:10
Sounds like a duplicate of https://github.com/microsoft/playwright/issues/7822 to me which is exactly about that PDFs in headed don't end up in downloads.

**Comment by aslushnikov** [comment] 2023-02-17 14:01
Merging into https://github.com/microsoft/playwright/issues/7822

**Closed by aslushnikov** 2023-02-17 14:01 UTC
