### ISSUE TITLE
[QUESTION] How use expect_file_chooser correctly?

### ISSUE THREAD

**Issue by qupfer** [microsoft/playwright-python#249] opened 2020-10-22 14:17 UTC
Hi, I'm new to python/playwright and not sure how to use the "expect_file_chooser" correctly.

I try to select a (large) file, and then upload it.

Thats my snippet (using playwright-pytest)

```python
with page.expect_file_chooser() as file_select:
    page.click('input[type="file"]')
    fc=file_select.value
    fc.setFiles("/absolute/path/to/my/large/file") # seems to hang here
page.click('button  >> text= Upload File ')  #which should start the upload
```
If I use a small file instead, it will work, but the filechooser need lot of time. 

Can somebody give me a hint, what I'm doing wrong?

Thanks :-)

Edit:
it seems, that the complete file is read to the buffer and there it hangs.
Any other solution the get the "file select" to the site?

**Comment by macgeneral** [comment] 2020-10-27 21:44
This works for me:

```python
with page.expect_file_chooser() as file_chooser:
    page.click('button  >> text=Upload File') 
    file_chooser.value.setFiles(files=["/absolute/path/to/my/large/file])
```

**Comment by pavelfeldman** [comment] 2020-10-28 07:04
This is indeed simpler:
```py
page.setInputFiles(selector='input[type="file"]', files=['/absolute/path/to/my/large/file'])
```

Sometimes input is created dynamically, so event is necessary. In this case, something like this should work:
```py
page.setContent("<input type=file></input>")
with page.expect_file_chooser() as fc_info:
    page.click('input[type="file"]')
# It is essential that the value is unboxed after the context manager exited
fc = fc_info.value
fc.setFiles({'name': 'test.txt', 'mimeType': 'text/plain', 'buffer': b'Hello World'})
```

**Comment by qupfer** [comment] 2020-10-28 08:16
Thanks for your answers, but it still work for small and medium files (40 MB).
My large file (1 GB) run endless and no differente if im using file Chooser and setFiles() or Element.setInputFiles().
Both works with medium large file (but also needs lot of time) and Never Ends with large file.

**Comment by macgeneral** [comment] 2020-10-28 10:01
Does the large file upload work if you upload it as normal user over the front-end? How long are your timeouts configured? Does the file upload work if you for example open the page in playwright with headless=False and set a page.waitForTimeout(300000) and manually upload it there?

**Comment by pavelfeldman** [comment] 2020-10-28 17:29
There is a cut-off at 128MB payload size in Chromium CDP that you are hitting: https://github.com/microsoft/playwright/issues/3768

**Comment by pavelfeldman** [comment] 2020-10-28 17:30
We prioritize issues based on the upvotes, so go ahead and thumb up that original issue please!

**Comment by pavelfeldman** [comment] 2020-11-21 18:16
Closing as a dupe of https://github.com/microsoft/playwright/issues/3768

**Closed by pavelfeldman** 2020-11-21 18:16 UTC

**Comment by Bingo-Li** [comment] 2021-07-08 10:02
I have a question here. when I import a excel, open file dialog won't close automatically.

![image](https://user-images.githubusercontent.com/20297585/124903201-541cad80-e016-11eb-9174-dca2f5bd8bdd.png)
My script is:     
page.set_input_files("input[type=\"file\"]", "UserImportTemplate.xlsx")
So there are any bug? Thanks!

**Comment by mxschmitt** [comment] 2021-07-08 10:11
Please open a new issue with reproducible steps.

**Comment by qupfer** [comment] 2021-07-08 11:34
The file-chooser worked for me only in headless mode. Otherthise the system filechooser poped up, which playwright can't control.

**Comment by SalamandraLw** [comment] 2021-12-13 13:19
![image](https://user-images.githubusercontent.com/88287165/145819507-7b4006c7-ff96-4259-b047-1e1b618a7eea.png)
I'm having the error "Permission denied" would anyone know how to solve it? inside this folder there are around 30 files
