### ISSUE TITLE
[Question]How do i make a POST requests in a playwright driver ? (python)

### ISSUE THREAD

**Issue by NoName7258** [microsoft/playwright-python#1009] opened 2021-11-06 19:27 UTC
How do i make a POST requests in a playwright driver ? (python)

**Comment by kumaraditya303** [comment] 2021-11-07 17:08
It would be nice if it could be a context manager to auto dispose it after use, https://playwright.dev/docs/next/api/class-apirequestcontext#api-request-context-dispose

**Comment by kumaraditya303** [comment] 2021-11-07 17:10
It should also be integrated with the pytest plugin.

**Comment by kumaraditya303** [comment] 2021-11-09 08:21
Duplicate of https://github.com/microsoft/playwright-python/issues/1004

**Closed** 2021-11-09 09:38 UTC
Labels: v1.17
