### ISSUE TITLE
[Question]:When I use connect_over_cdp and the download request method is POST, expect_download cannot work

### ISSUE THREAD

**Issue by kinopop** [microsoft/playwright-python#2332] opened 2024-02-28 02:09 UTC
### Please do not submit this issue.

- [X] I understand

**Comment by kinopop** [comment] 2024-02-28 02:15
Come on,continue,[https://github.com/microsoft/playwright/issues/29679](url)
![微信图片编辑_20240228100757](https://github.com/microsoft/playwright-python/asset
![微信图片编辑_20240228100738](https://github.com/microsoft/playwright-python/assets/35102979/1661fd42-0714-4014-8ad6-ae1f948d21fe)
s/3510
![微信图片编辑_20240228100713](https://github.com/microsoft/playwright-python/assets/35102979/248ddb49-7fa7-412d-9b8a-c86a18b13953)
2979/c58306bb-d549-4380-a750-9aeea5723877)
It just cannot work by expect_download
I'm sure it didn't listen to download requests, but I don't know how to debug and optimize it.

**Comment by kinopop** [comment] 2024-02-28 02:16
![微信图片编辑_20240228100757](https://github.com/microsoft/playwright-python/assets/35102979/7c57d8ce-b407-4777-9186-a27f9f17d3cb)

**Comment by kinopop** [comment] 2024-02-28 02:30
If it cannot listen to download requests, how should I use route() to make the file save as correctly？

**Comment by mxschmitt** [comment] 2024-02-29 12:41
We need clear reproduction steps in order to look into issues like this. I tried it as per https://github.com/microsoft/playwright/issues/29679#issuecomment-1966177956 and it was working as intended.

**Comment by mxschmitt** [comment] 2024-03-05 14:37
Closing it as per above. Feel free to re-file with clear reproduction steps.

**Closed by mxschmitt** 2024-03-05 14:37 UTC
