### ISSUE TITLE
[Question]: Why I get the error ValueError: I/O operation on closed pipe

### ISSUE THREAD

**Issue by JCHacking** [microsoft/playwright-python#1876] opened 2023-04-24 09:40 UTC
I am making a layer that wraps Playwright to have more flexibility to changes, one of the parts is to manage browsers, it consists of the following class:
```python
"""Actions on browsers with Playwright."""
from typing import Optional

from playwright.async_api import Playwright, Browser as PlaywrightBrowser, BrowserContext as PlaywrightBrowserContext, \
    async_playwright

from py_web_gui.browser.data import Browser, BrowserData
from py_web_gui.browser.error import BrowserNotStartedError
from py_web_gui.browser.browser_base import BrowserBase


class BrowserPlaywright(BrowserBase):
    """Actions on browsers with Playwright.

    Attributes:
        __playwright: Playwright Manager
        __browsers: Browsers
        __playwright_browsers: Browser names for playwright
        browser_context: Playwright's BrowserContext
    """
    __playwright: Optional[Playwright] = None
    __browsers: dict[Browser, PlaywrightBrowser] = {}
    __playwright_browsers: dict[Browser, str] = {
        Browser.CHROME: "chromium",
        Browser.FIREFOX: "firefox",
        Browser.EDGE: "webkit"
    }

    def __init__(self, browser_data: BrowserData):
        """Actions on browsers with Playwright.

        Args:
            browser_data: Browser Data
        """
        super().__init__(browser_data)
        self.browser_context: Optional[PlaywrightBrowserContext] = None

    async def init(self) -> None:
        """Start browser."""
        if self.__playwright is None:
            self.__playwright = await async_playwright().start()

        if self.browser_data.browser not in self.__browsers.keys():
            self.__browsers[self.browser_data.browser] = await getattr(self.__playwright, self.__playwright_browsers[self.browser_data.browser]).launch(
                    executable_path=self.browser_data.path,
                    headless=False,
                    slow_mo=self.browser_data.cooldown
                )

        self.browser_context = await self.__browsers[self.browser_data.browser].new_context()

    async def close(self) -> None:
        """Closes browser.

        Raises:
            BrowserNotStartedError: Browser not started
        """
        if self.browser_context is None:
            raise BrowserNotStartedError()

        for page in self.browser_context.pages:
            await page.close()

        await self.browser_context.close()
        self.browser_context = None

        if len(self.__browsers[self.browser_data.browser].contexts) <= 0:
            await self.__browsers[self.browser_data.browser].close()
            del self.__browsers[self.browser_data.browser]

        if len(self.__browsers.keys()) <= 0:
            await self.__playwright.stop()  # type: ignore[func-returns-value]
            self.__playwright = None
```

Testing to see if the previously created class works well, I tried the following code:
```python
import asyncio

from py_web_gui import BrowserBase, BrowserPlaywright, BrowserData, Browser


async def main():
    browsers: list[BrowserPlaywright] = [
        BrowserPlaywright(
            BrowserData(path=r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe", browser=Browser.CHROME)
        ),
        BrowserPlaywright(
            BrowserData(path=r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe", browser=Browser.CHROME)
        )
    ]

    try:
        for browser in browsers:
            await browser.init()

            if browser.browser_context is not None:
                page = await browser.browser_context.new_page()
                await page.goto("https://www.google.es")

        await asyncio.sleep(5)
    finally:
        for browser in browsers:
            await browser.close()

asyncio.run(main())
```

I get the following error:
```python
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001C403DCEA20>
Traceback (most recent call last):
  File "C:\Python311\Lib\asyncio\proactor_events.py", line 116, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\proactor_events.py", line 80, in __repr__
    info.append(f'fd={self._sock.fileno()}')
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001C403DCEA20>
Traceback (most recent call last):
  File "C:\Python311\Lib\asyncio\proactor_events.py", line 116, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\proactor_events.py", line 80, in __repr__
    info.append(f'fd={self._sock.fileno()}')
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x000001C403DCD300>
Traceback (most recent call last):
  File "C:\Python311\Lib\asyncio\base_subprocess.py", line 125, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\base_subprocess.py", line 70, in __repr__
    info.append(f'stdin={stdin.pipe}')
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\proactor_events.py", line 80, in __repr__
    info.append(f'fd={self._sock.fileno()}')
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
```

If there is only one in the array of browsers, it does not happen.

Could someone give me some guidance? I understand that it is something that I close or do not close, but I do not see at any time that I am leaving something aside.

**Comment by mxschmitt** [comment] 2023-04-24 12:22
Can you provide a full reproducible script which we can run locally to reproduce the error? Since your code above has imports which prevents me from running it.

**Comment by JCHacking** [comment] 2023-04-25 06:46
Of course, I have uploaded the code to this repository.
The test would be the dev.py
https://github.com/JCHacking/py_web_gui

**Comment by mxschmitt** [comment] 2023-05-02 12:17
Thanks!

Looks like the issue in this case was that you were using static class variables and not variables scoped to the class instance. See [here](https://stackoverflow.com/a/68672/6512681) about the difference. If you make the following changes its working for me:

```diff
diff --git a/py_web_gui/browser/browser_playwright.py b/py_web_gui/browser/browser_playwright.py
index 6acc202..f479146 100644
--- a/py_web_gui/browser/browser_playwright.py
+++ b/py_web_gui/browser/browser_playwright.py
@@ -18,8 +18,8 @@ class BrowserPlaywright(BrowserBase):
         __playwright_browsers: Browser names for playwright
         browser_context: Playwright's BrowserContext
     """
-    __playwright: Optional[Playwright] = None
-    __browsers: dict[Browser, PlaywrightBrowser] = {}
+    __playwright: Optional[Playwright]
+    __browsers: dict[Browser, PlaywrightBrowser]
     __playwright_browsers: dict[Browser, str] = {
         Browser.CHROME: "chromium",
         Browser.FIREFOX: "firefox",
@@ -32,6 +32,8 @@ class BrowserPlaywright(BrowserBase):
         Args:
             browser_data: Browser Data
         """
+        self.__playwright = None
+        self.__browsers = {}
         super().__init__(browser_data)
         self.browser_context: Optional[PlaywrightBrowserContext] = None
 
@@ -43,7 +45,6 @@ class BrowserPlaywright(BrowserBase):
         if self.browser_data.browser not in self.__browsers.keys():
             self.__browsers[self.browser_data.browser] = \
                 await getattr(self.__playwright, self.__playwright_browsers[self.browser_data.browser]).launch(
-                    channel=self.browser_data.channel,
                     headless=False,
                     slow_mo=self.browser_data.cooldown
                 )
```

I made the channel changes, since on my cor-phosted machine the enterprise policies end up in a browser.close hang, but these are known issues, see [here](https://playwright.dev/docs/troubleshooting#incompatible-microsoft-edge--google-chrome-policy-settings).

**Comment by JCHacking** [comment] 2023-05-02 15:26
Thank you very much!!! You're right using it as instance attributes works!!!

The idea I had was to be able to use the same instance of __playwright and __browsers for everything, because even if I instantiate several BrowserPlaywright classes they could all use the same one of playwright. 

I guess at some point I am closing something which then when trying to close it again fails and that's why the warning. I have not been able to see with a debugger that it closes earlier than expected.

**Comment by mxschmitt** [comment] 2023-05-02 20:40
I actually saw that we can improve the error reporting on our side by a ton, will keep this issue open until we implemented the better error reporting so such things won't happen again.

**Comment by JCHacking** [comment] 2023-05-03 05:46
Perfect!!!

I am still investigating why in my code the error occurs. I have tried 2 things.

1 -> Download playwright from the fix-api-call-after-close branch to see if the error message changed (It didn't).
2 -> Change __browsers from a dictionary to a variable that stores only the PlaywrightBrowser, this seems to fix it, I don't know what conflict I have for using a dictionary.

**Comment by mxschmitt** [comment] 2023-05-03 06:57
I was spotting two bugs on our side, which reflected on how you did things in your project.

a) calling a Playwright method on page, context, or browser on a playwright session which is stopped ends up in errors
b) calling playwright.stop() multiple times ends up in errors

So I believe that you call playwright.stop() too early.

**Comment by JCHacking** [comment] 2023-05-03 07:33
Playwright.stop() is only called once and that is at the end. Otherwise it does not enter in the last if because it detects that there is any open context apart from the one that has been closed before.
I have checked it with Debugger and can confirm that it only runs once.


If I perform an await asyncio.sleep(60) before execute playwright.stop() I get the same error, so I don't think it's because of timeouts.

**Comment by JCHacking** [comment] 2023-05-08 21:37
The code that I want to work is the first commit https://github.com/JCHacking/py_web_gui/commit/fb84cffaccc38924dd2dc948928ef5dd3da785a3
The rest were for testing so you could see what I meant in some aspects.

With this in mind I have tested with that code and with playwright version 1.33.0.post3+gb913f48 according to PIP.

The error message seems to have changed, I now receive the following:
```python
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x0000020F5B9F05E0>
Traceback (most recent call last):
  File "C:\Python311\Lib\asyncio\base_subprocess.py", line 125, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\base_subprocess.py", line 70, in __repr__
    info.append(f'stdin={stdin.pipe}')
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\proactor_events.py", line 80, in __repr__
    info.append(f'fd={self._sock.fileno()}')
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000020F5B9F1D00>
Traceback (most recent call last):
  File "C:\Python311\Lib\asyncio\proactor_events.py", line 116, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\proactor_events.py", line 80, in __repr__
    info.append(f'fd={self._sock.fileno()}')
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
```

Although it looks like the same error, it only occurs 2 times instead of the 3 that happens with version 1.33 uploaded to pypi.

**Comment by mxschmitt** [comment] 2023-05-09 07:38
So the problem which is now in place is that you define the variables as static variables but you read them as instance variables. If you modify the code like this it will work:

```diff
diff --git a/py_web_gui/browser/browser_playwright.py b/py_web_gui/browser/browser_playwright.py
index bd0d030..03690af 100644
--- a/py_web_gui/browser/browser_playwright.py
+++ b/py_web_gui/browser/browser_playwright.py
@@ -37,18 +37,18 @@ class BrowserPlaywright(BrowserBase):
 
     async def init(self) -> None:
         """Start browser."""
-        if self.__playwright is None:
-            self.__playwright = await async_playwright().start()
+        if BrowserPlaywright.__playwright is None:
+            BrowserPlaywright.__playwright = await async_playwright().start()
 
-        if self.browser_data.browser not in self.__browsers.keys():
-            self.__browsers[self.browser_data.browser] = \
-                await getattr(self.__playwright, self.__playwright_browsers[self.browser_data.browser]).launch(
+        if self.browser_data.browser not in BrowserPlaywright.__browsers.keys():
+            BrowserPlaywright.__browsers[self.browser_data.browser] = \
+                await getattr(BrowserPlaywright.__playwright, BrowserPlaywright.__playwright_browsers[self.browser_data.browser]).launch(
                     executable_path=self.browser_data.path,
                     headless=False,
                     slow_mo=self.browser_data.cooldown
                 )
 
-        self.browser_context = await self.__browsers[self.browser_data.browser].new_context()
+        self.browser_context = await BrowserPlaywright.__browsers[self.browser_data.browser].new_context()
 
     async def close(self) -> None:
         """Closes browser.
@@ -65,10 +65,10 @@ class BrowserPlaywright(BrowserBase):
         await self.browser_context.close()
         self.browser_context = None
 
-        if len(self.__browsers[self.browser_data.browser].contexts) <= 0:
-            await self.__browsers[self.browser_data.browser].close()
-            del self.__browsers[self.browser_data.browser]
+        if len(BrowserPlaywright.__browsers[self.browser_data.browser].contexts) <= 0:
+            await BrowserPlaywright.__browsers[self.browser_data.browser].close()
+            del BrowserPlaywright.__browsers[self.browser_data.browser]
 
-        if len(self.__browsers.keys()) <= 0:
-            await self.__playwright.stop()  # type: ignore[func-returns-value]
-            self.__playwright = None
+        if len(BrowserPlaywright.__browsers.keys()) <= 0:
+            await BrowserPlaywright.__playwright.stop()  # type: ignore[func-returns-value]
+            BrowserPlaywright.__playwright = None
```

**Comment by mxschmitt** [comment] 2023-05-09 14:12
(Before this then ends up that you create Playwright twice but only close it once)

**Comment by JCHacking** [comment] 2023-05-10 03:15
You are right, once changed so that all those variables are read statically it works correctly.

Thank you!!!

**Closed** 2023-05-10 04:14 UTC
Labels: v1.34
