### ISSUE TITLE
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded

### ISSUE THREAD

**Issue by onishant** [microsoft/playwright-python#1449] opened 2022-07-22 11:58 UTC
I am trying to automate a .csv download process from a website.
I am using the following code on my **Windows** machine and it gives me the exact output I need.
```# Import base libraries for DAG
from airflow import DAG
from airflow.operators.python_operator import PythonOperator
from libs.config import default_args
from airflow.models import Variable

# Get the root folder variable
data_files_root_folder = Variable.get("production_data_root_folder")

# Import Playwright and dependent libraries
from playwright.sync_api import sync_playwright
from bs4 import BeautifulSoup
import os

# Create playwright instance
with sync_playwright() as p:
    # Create browser object
    browser = p.chromium.launch(headless=True, slow_mo=50)

    # Create a page object
    page = browser.new_page()

    # Go to the login page
    page.goto('https://app.the-omj.com/en/home')

    # Select and enter login details
    page.fill('//*[@id="auth0-lock-container-1"]/div/div[2]/form/div/div/div/div[2]/div[2]/span/div/div/div/div/div/div/div/div/div/div/div[1]/div/input', 'xxxxxxxxxx')
    page.fill('//*[@id="auth0-lock-container-1"]/div/div[2]/form/div/div/div/div[2]/div[2]/span/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/input', 'xxxxxxxx')
    
    # Click submit
    page.click('button[type=submit]')

    # Print checks
    print("Login complete")
    
    # Wait for object to appear
    page.is_visible('//html/body/app-root/div[1]/app-page-home/div/div[1]/div/div[2]/app-tile-quicklinks/div/div[5]/a/p')

    # Click 1
    page.click('//html/body/app-root/div[1]/app-page-home/div/div[1]/div/div[2]/app-tile-quicklinks/div/div[5]/a')

    # Click 2
    page.click('body > app-root > div.content > app-page-research-home > div > div > div.left > app-page-research-list > div > div.list > ul > li:nth-child(4) > div > ul > li:nth-child(2) > div.name > span')
    
    # Click 3
    page.click('//html/body/app-root/div[1]/app-page-research-home/div/div/div[1]/app-page-research-report/div/div[2]/div/div[2]/div[1]/div[1]')


    # Click for download
    with page.expect_download() as download_info:
        page.click('//html/body/app-root/div[1]/app-page-research-home/div/div/div[1]/app-page-research-viewer/div/div[2]/div/i')
    
    # Specify download path
    download = download_info.value
    file_name = download.suggested_filename
    destination_folder_path = f'{data_files_root_folder}/download/UK M OMJ ExchangeRates/Staging'
    
    # Download
    download.save_as(os.path.join(destination_folder_path, file_name))


    browser.close()
```

The problem is, I am unable to do the same on the **Linux VM in Azure**. The error is as following:
```
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "//html/body/app-root/div[1]/app-page-home/div/div[1]/div/div[2]/app-tile-quicklinks/div/div[5]/a"
```
I have tried:
1. **Increasing the timeout, but it doesn't work.** Keeps giving the same error message (even for extremely large timeouts) -> page.goto(link, timeout = 100000).
2. **Changing between the CSS and XPATHs.** Gives the same error as before .

I introduced a `print(page.url)` after the login, but it displays the page without the contents of the page. So it hasn't been really clear for me. Could anyone give me some tips to solve this problem?

P.S. Please let me know if you need anymore information.

**Comment by rwoll** [comment] 2022-07-22 20:52
The selectors you're using are extremely specific, so if anything about the structure of the page is different based on viewport, user agent, etc. the script is going to break.

I recommend using some friendlier selectors based on https://playwright.dev/python/docs/selectors#best-practices

Additionally, record a Trace https://playwright.dev/python/docs/trace-viewer and see what it's doing.

If I read your script correctly, the timeout occurs waiting for a selector after you click login. It could be that Auth0 is blocking you from logging in on that device.  

Once you have a trace, it might give a better sense of where the problem is.

**Comment by rwoll** [comment] 2022-07-22 20:52
btw, you can use `npx playwright codegen <your site>` to generate some selector suggestions

**Comment by onishant** [comment] 2022-07-25 11:35
Thanks @rwoll for the quick reply.
I have managed to switch to some friendlier selectors based on the best practices.
However, since the Linux VM that I am using in Azure doesn't have a GUI, the `codegen` method or 'trace recording' method won't work.

I am trying to understand how Auth0 could be blocking my device to log in but haven't had much luck so far. Is there a specific way to look for this?
P.S. for your reference, I had earlier used Selenium to do the same process and it worked completely fine until the recent update broke it. But Auth0 was never blocking it.

**Comment by rwoll** [comment] 2022-07-25 17:22
> However, since the Linux VM that I am using in Azure doesn't have a GUI, the codegen method or 'trace recording' method won't work.

Enabling tracing will drop a zip file/trace on disk. This should work regardless of the environment. You can then copy the trace artifact to your local machine and view the trace there in a GUI. (The trace was created to help debug CI failures.)

> I am trying to understand how Auth0 could be blocking my device to log in but haven't had much luck so far. Is there a specific way to look for this?

I don't recommend debugging the specifics too much, other than determining the failure is in Auth0 blocking you on the linux machine. There's a lots of automation-detection log in services use to prevent logins. For auth0 specifically, you can use a different login flow than the UI to ensure you're not blocked. @mxschmitt Can you elaborate?

**Comment by rwoll** [comment] 2022-07-27 17:29
> It makes me wonder if there is something about the authentication that is stopping the page from loading?
> Is there any other method to look at this problem?

Assuming the same code works locally to log you in, and without changing it, it gets stuck in CI on the Auth0 screen, it is most likely Auth0's servers blocking the authentication (perhaps based on IP address or some other signal).

At this point, I recommend reaching out to your Auth0 rep so they can help you determine what'a blocking the auth currently, and how to remove that block for your test account—or provide another mitigation strategy.

I'm going to close this issue for now, but please comment back once you find out more, and/or re-open as necessary.

**Closed by rwoll** 2022-07-27 17:29 UTC
Labels: triaging

**Comment by missemily22** [comment] 2022-12-11 10:08
@rwoll I am getting this same error when I am enabling Headless Mode
With Headless turned to False, there is no such error...
