### ISSUE TITLE
[BUG] Hanging when browser runs out of memory

### ISSUE THREAD

**Issue by nathanielobrown** [microsoft/playwright-python#1847] opened 2023-04-04 16:07 UTC
**Context:**
- Playwright Version: 1.31.1
- Operating System: Linux+docker
- Python version: 3.10.6
- Browser: Chromium

**Code Snippet**

My code hangs when trying to save a trace to a file every so often

```python
from pathlib import Path
import tempfile
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch()
    with browser.new_context() as context:
        page = browser.new_page()
        context.tracing.start(screenshots=True, snapshots=True)
        try:
            page.goto("https://some_url.com")
            # Do some stuff that fails
        finally:
            file = tempfile.NamedTemporaryFile(suffix=".zip")
            path = Path(file.name)
            file.close()
            # This hangs forever, using 100% CPU
            context.tracing.stop(path=path)
            # Would return path to some parent function...
    browser.close()
```

**Describe the bug**
It seems like something goes wrong with the trace saving and then Playwright gets caught in an infinite loop on [these two lines](https://github.com/microsoft/playwright-python/blob/main/playwright/_impl/_sync_base.py#L101-L102):
```python
        while not task.done():
            self._dispatcher_fiber.switch()
```
The main Python process is pegged at 100% CPU executing these two lines. When I use `lsof`, no process even has the zipfile I'm trying to save the trace to open. There may have been an exception that inside the `try` block that Playwright is unable to handle saving traces for. I will add more logging to figure this out and report back, but I feel like Playwright should not get hung here regardless.

![hung_trace_capture](https://user-images.githubusercontent.com/5266576/229849060-0c80b24d-f716-439b-a282-50ab8a2fb7ab.png)

**Comment by mxschmitt** [comment] 2023-04-11 14:59
I would recommend for now to upgrade to 1.32.1+ since we changed tracing a lot and how it works under the hood to process it, when getting stopped.

**Comment by nathanielobrown** [comment] 2023-04-16 16:16
I upgraded Playwright to 1.32.1 and can confirm that this issue still happens on 1.32.1.

From my logs, one of the exceptions that occurred before I tried to stop tracing is `<class 'playwright._impl._api_types.Error'>: Navigation failed because page was closed!`. I'm not sure that this is the _only_ exception that causes the hang, and I also know that this exception does not cause a hang in every case.

My understanding is this error indicates a page crash. Is it valid to try to call `tracing.stop()` after a page crash?

**Comment by mxschmitt** [comment] 2023-04-19 14:21
I'm not entirely sure if this is a page crash, you could set the `DEBUG=pw:browser` env var, which would show the browser crash logs (if any).

Not sure how `tracing.stop()` behaves if a page is crashing, but judging from a quick look into the source code it should.

**Comment by nathanielobrown** [comment] 2023-04-19 17:32
Ok, I've set `DEBUG=pw:browser` and I'll wait and see what that produces

**Comment by nathanielobrown** [comment] 2023-04-28 15:21
Here are some of the `pw:browser` logs from around the time that one of these "hangs" on stop tracing occurred
[Explore-logs-2023-04-28 11 18 44.txt](https://github.com/microsoft/playwright-python/files/11354964/Explore-logs-2023-04-28.11.18.44.txt)

**Comment by mxschmitt** [comment] 2023-05-02 14:38
Unfortunately they don't contain helpful information. Did you try to monitor the memory use? So we can make sure its not ending up in a out of memory error of your system.

**Comment by nathanielobrown** [comment] 2023-05-02 15:12
I have pretty much narrowed it down to an out of memory issue. I haven't been able to find a log anywhere that shows an OOM memory handler killing a process (this is in a Kubernetes pod, FYI), but the issue started happening all the time and then I raised the container memory limit and it has not happened since.

I was going to dig into the `Failed to connect to socket /run/dbus/system_bus_socket` and `Failed to adjust OOM score of renderer` in case those were preventing Chrome from more gracefully handling the out of memory situation, but maybe you can confirm that those are not an issue?

In general, do you have any tips on debugging/getting visibility into these out-of-memory situations or ways to make Playwright handle the situation more gracefully?

**Comment by mxschmitt** [comment] 2023-05-02 20:43
The two error messages are most likely not related. Two common mistakes which end up in a OOM are that you re-use your context. Since we only flush / clean memory up when you actually close aka. re-create your context. Another common reason is that you forgot to close the page or context somewhere in a loop or occurring operating.

There are three layers you'd have to debug:

a) Python memory leak - I guess you are familiar to debug that.
b) Node.js memory leak - If you see this growing and growing, we can help debugging that, but for that we need a repro.
c) Browser memory leak - This usually happens when the websites you are navigating to have a memory leak.

**Comment by nathanielobrown** [comment] 2023-05-02 21:05
Thank you for the tips @mxschmitt! For my case I think it's just that sometimes I interact with websites that use more memory than I have allocated, so sort of option C, although maybe it's not a leak per se, just a memory hungry website. I monitor my worker's memory usage and there is no leakage over time.

I guess what I'm hoping to workout is some way so _if_ I run out of memory, things don't hang. Almost anything would be preferable to that, include an exception in my Python code or even the Python process being killed. I'm going to try a few things, but let me know if you have any ideas. On thing I will try is using [dumb-init](https://github.com/Yelp/dumb-init) as [Browserless](https://github.com/browserless/chrome) is using this

**Comment by nathanielobrown** [comment] 2023-05-03 13:07
Also, I have a ton of Zombie processes that are consuming no RAM, like this:
```
Process 70188 - chrome                         memory usage: 0MB
Process 70189 - chrome                         memory usage: 0MB
Process 70383 - chrome_crashpad                memory usage: 0MB
Process 70385 - chrome_crashpad                memory usage: 0MB
Process 70388 - chrome                         memory usage: 0MB
Process 70389 - chrome                         memory usage: 0MB
Process 70581 - chrome_crashpad                memory usage: 0MB
Process 70583 - chrome_crashpad                memory usage: 0MB
Process 70586 - chrome                         memory usage: 0MB
Process 70587 - chrome                         memory usage: 0MB
Process 70777 - chrome_crashpad                memory usage: 0MB
Process 70779 - chrome_crashpad                memory usage: 0MB
Process 70782 - chrome                         memory usage: 0MB
Process 70783 - chrome                         memory usage: 0MB
Process 70977 - chrome_crashpad                memory usage: 0MB
Process 70979 - chrome_crashpad                memory usage: 0MB
Process 70982 - chrome                         memory usage: 0MB
Process 70983 - chrome                         memory usage: 0MB
Process 71180 - chrome_crashpad                memory usage: 0MB
Process 71182 - chrome_crashpad                memory usage: 0MB
Process 71185 - chrome                         memory usage: 0MB
Process 71186 - chrome                         memory usage: 0MB
Process 71379 - chrome_crashpad                memory usage: 0MB
Process 71381 - chrome_crashpad                memory usage: 0MB
Process 71384 - chrome                         memory usage: 0MB
```
Not sure what that's all about

**Comment by mxschmitt** [comment] 2023-05-06 08:44
Looks suspicious for sure! We need a reproducible unfortunately to act on this further.

**Comment by nathanielobrown** [comment] 2023-05-06 12:55
The zombie processes listed above were totally solved by using [dumb-init](https://github.com/Yelp/dumb-init), so there's the solution to that issue.

I've done some tests where I run a local docker container with artificially constrained memory to observe the behavior. As of yet I have not get it to hang as I see in production, but I suspect it might take the OOM memory handler killing the right process at _just_ the right time to trigger this hang. So next step for me would be to run this test many times and see if I can get it to ever hang. My test command was along these lines: `docker run --rm -it --memory=250m --memory-swap=250m --env-file bots/.env -v "$(pwd)/test_mem.py:/test.py" mcr.microsoft.com/playwright/python:v1.32.1-jammy python /test.py`

However, there's a chance dumb-init may have solved the issue and I've made some adjustments to memory allocations that mean this hasn't happened again for a while so I'm going to leave this for now.

**Comment by mxschmitt** [comment] 2023-05-09 07:43
Cool, was just discussing this issue with a coworker and turns out that a init manager or just passing --init is essential for using Playwright / running browsers inside Docker.

Closing it then for now, feel free to re-file if you still experience issues.

**Closed by mxschmitt** 2023-05-09 07:43 UTC
Labels: triaging

**Comment by nathanielobrown** [comment] 2023-05-09 11:26
Thank you for the confirmation @mxschmitt! I will reopen if I'm able to reproduce the hanging issue

**Comment by nathanielobrown** [comment] 2023-06-08 13:33
@mxschmitt, I think I've narrowed down what's going on. My task execution framework ([Temporal](https://temporal.io/)) has a timeouts feature that for threaded tasks caused an exception (`temporalio.exceptions.CancelledError` to be raised in a thread to try to get it to exit. When this exception is raised while Playwright is performing an action, I think it gets Playwright into a bad state where it infinite loops.

My question to you is, how can I cancel a section of Playwright code in a way that will not cause invalid states? I imagine it might be quite difficult with this threaded setup where an exception can be raised at any time.

If I switch from sync Playwright to async Playwright, I feel like this problem might be eliminated because then Temporal uses built in task cancellation that raises `asyncio.CancelledError`, which will only be raised in a coroutine if that coroutine has yielded control to the event loop. Would you say that async Playwright gracefully handles `asyncio.CancelledError`'s?
