### ISSUE TITLE
[BUG] SSL WRONG_SIGNATURE_TYPE Error When Running httpx inside Playwright Docker Container

### ISSUE THREAD

**Issue by ozw-sei** [microsoft/playwright-python#1990] opened 2023-06-23 03:20 UTC
**Context:**
- Playwright Docker Version: [what Playwright version do you use?] mcr.microsoft.com/playwright/python:v1.34.0-jammy
- Operating System: [e.g. Windows, Linux or Mac] Windows WSL2 
```
$ cat /etc/os-release
PRETTY_NAME="Pengwin"
NAME="Pengwin"
VERSION_ID="11"
VERSION="11 (bullseye)"
ID=debian
ID_LIKE=debian
HOME_URL="https://github.com/whitewaterfoundry/Pengwin"
SUPPORT_URL="https://github.com/WhitewaterFoundry/Pengwin/issues"
BUG_REPORT_URL="https://github.com/WhitewaterFoundry/Pengwin/issues"
VERSION_CODENAME=bullseye
PENGWIN_VERSION="23.03.0"
```

- Python version: [e.g. 3.8, 3.9] 3.10

**Code Snippet**

```python
import httpx

insecure_ssl_context = httpx.create_ssl_context(verify=False)
insecure_ssl_context.set_ciphers("DEFAULT@SECLEVEL=1")

url = "https://www.tama-monorail.co.jp/"

r = httpx.get(url, verify=insecure_ssl_context)
r.raise_for_status()

print("success!")
```

**Describe the bug**

Add any other details about the problem here.Hello,

I have encountered an issue when executing a Python script using the httpx library inside a Playwright Docker container. I'm attempting to establish a connection to a secure server, but am running into a WRONG_SIGNATURE_TYPE SSL error.

Here is the command I'm using:

```
docker pull mcr.microsoft.com/playwright/python:v1.34.0-jammy && \
docker run -it mcr.microsoft.com/playwright/python:v1.34.0-jammy bash -c 'pip install httpx && python -c "import httpx; insecure_ssl_context = httpx.create_ssl_context(verify=False); insecure_ssl_context.set_ciphers(\"DEFAULT@SECLEVEL=1\"); url = \"https://www.tama-monorail.co.jp/\"; r = httpx.get(url, verify=insecure_ssl_context); r.raise_for_status(); print(\"success\")"'
```

This command results in the following error:

```
httpx.ConnectError: [SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:997)
```

This error only occurs when running the script inside the Docker container.

After researching this issue, it seems that it might be related to mismatched signature algorithms between the server and the client, or possibly the Python and OpenSSL versions used in the Docker image. However, I'm not entirely sure what's causing the issue, or how to resolve it.

Could you please assist with this issue? Is it something related to the Docker image or the httpx library? Are there specific settings that I might need to adjust?

Thank you in advance for your help.

**Comment by ozw-sei** [comment] 2023-06-23 06:07
I have an update on this issue. I tested the same Python script using the mcr.microsoft.com/playwright:v1.35.0-focal image, which is based on Ubuntu 20.04 LTS, and the issue did not occur. The httpx connection was established successfully without any SSL errors.

It appears that the issue might be specific to the mcr.microsoft.com/playwright/python:v1.34.0-jammy image. Could it be a compatibility issue with the Python or OpenSSL versions used in this particular image?

Any additional insights or guidance on this issue would be greatly appreciated. Thank you.

**Comment by mxschmitt** [comment] 2023-06-25 09:03
This looks most likely not like a Playwright issue. The Docker container which we build is pretty straightforward, see here: https://github.com/microsoft/playwright-python/blob/main/utils/docker/Dockerfile.jammy

So its just stock Ubuntu + Python. Maybe httpx uses some outdated ca-certificates internally, I'd try to explore in that direction.

As per https://github.com/encode/httpx#dependencies make sure to have an updated version of `certifi` PIP package.

**Comment by mxschmitt** [comment] 2023-06-29 19:33
Closing as per above since this is not a Playwright issue and most likely also reproduces with normal stock Ubuntu.

**Closed by mxschmitt** 2023-06-29 19:33 UTC
Labels: triaging
