### ISSUE TITLE
[Question] How to interact with a input inside a iframe

### ISSUE THREAD

**Issue by CheemaOTB** [microsoft/playwright-python#656] opened 2021-04-29 01:12 UTC
I'm trying to fill an input that is inside an iframe but I have had no luck. Here is the code. Am I doing something wrong?

`iframe = page.query_selector('xpath=//iframe[@title="payment"]').content_frame()

iframe.fill('//*[@id="cardCvc-input"]', '123')`

**Comment by mxschmitt** [comment] 2021-04-29 07:57
Duplicate of #654

See an example in #655

**Closed by mxschmitt** 2021-04-29 07:57 UTC
