### ISSUE TITLE
[BUG] Playwright Cause Incorrect window.innerHeight Values

### ISSUE THREAD

**Issue by caseyoneill** [microsoft/playwright-python#1112] opened 2022-01-18 21:18 UTC
**Context:**
- Playwright Version: 1.17.2
- Operating System: Mac
- Python version: 3.9.9
- Browser: Playwright default Chromium

**Problem**
When Chromium or Chrome is opened by Playwright, the window.innerHeight value is incorrect. If you open the dev tools console and inspect that property you will most likely get a number that is not accurate. If you then resize the window and inspect again, the number will not have updated. Sometimes the innerHeight value is larger than the window.outerHeight value which should be impossible. 

**Expected Result**
window.innerHeight should be accurate

**Code Snippet**

```

# Simple script to demonstrate window.innerHeight bug
from playwright.sync_api import sync_playwright

with sync_playwright() as playwright:

    browser = playwright.chromium.launch(headless=False)
    page = browser.new_page()
    page.goto('https://google.com')

    # Place breakpoint here. Go to browser window and open debug console.
    # inspect window.innerHeight. Resize window, inspect again and notice
    # that the value does not change.
    browser.close()

**Comment by mxschmitt** [comment] 2022-01-19 06:54
Closing as a duplicate of https://github.com/microsoft/playwright/issues/11465

**Closed by mxschmitt** 2022-01-19 06:54 UTC
