### ISSUE TITLE
[Question]: Taking screenshot of page immediately

### ISSUE THREAD

**Issue by Zeckie** [microsoft/playwright-python#1420] opened 2022-07-10 03:11 UTC
### Your question

I've run into an issue where a call to `page.screenshot(timeout=500)` is timing out, raising the exception: `TimeoutError('Timeout 500ms exceeded.\n=========================== logs ===========================\ntaking page screenshot\n============================================================')`.  I think at the time this occurs, the page is loading.

How do I make it take the screenshot immediately?
[page.click()](https://playwright.dev/python/docs/api/class-page#page-click) has `force` to skip [actionability checks](https://playwright.dev/python/docs/actionability), [page.screenshot()](https://playwright.dev/python/docs/api/class-page#page-screenshot) does not.

Also, when the timeout occurs, is there a way to determine what it was waiting for (eg is it waiting for the page to load, or something else?)

**Comment by DetachHead** [comment] 2022-07-11 07:08
this behavior is extremely annoying for stuff like debugging timing issues. for example, in our codebase we have an error handler that takes a screenshot when a test fails:

```py
try:
    if not page.query_selector("foo"):
        raise Exception("failed to find element")
except Exception:
    page.screenshot() # the element appears before it takes the screenshot
    raise
```

we only just noticed that there was a delay between the failure and the screenshot, making the screenshot pretty much useless for determining what actually went wrong.

**Comment by rwoll** [comment] 2022-07-12 15:55
@Zeckie Can you share a repro so we can track it down? It shouldn't hang!

@DetachHead Tracing will automatically take before and after screenshots for various actions: https://playwright.dev/python/docs/api/class-tracing That is the recommended approach for the debugging use case.

**Comment by DetachHead** [comment] 2022-07-13 00:44
@rwoll it doesn't for `query_selector`

![image](https://user-images.githubusercontent.com/57028336/178624442-72cde147-af4e-4001-9cb9-1c22e507e622.png)

also can this issue be transferred to the main playwright repo? as this isn't specific to playwright-python

**Comment by mxschmitt** [comment] 2022-07-13 07:49
We strongly discourage using ElementHandles, see here: https://playwright.dev/python/docs/locators

Could you try using Locators instead and then verify it again? Since it most likely gets then shown correctly.

**Comment by rwoll** [comment] 2022-07-18 18:48
Closing as part of triage. Please re-file with a repro that shows the screenshot hanging as that sounds like a bug, but without a repro we will just be guessing in this case. Thanks!

**Comment by KotlinIsland** [comment] 2022-07-19 01:57
@rwoll No one said anything about hanging, the issue is that `screenshot` waits for something before it takes the screenshot, but the use-case is often that you want to take a screenshot immediately to identify some aberrant behavior.

There is a `timeout` argument to the `screenshot` function, but no documentation about what it's waiting for.

**Comment by rwoll** [comment] 2022-07-19 05:22
@KotlinIsland You can see a log of what it's doing by setting `DEBUG` env var to `pw:api`:

For a snippet like:

```ts
  await page.goto("https://example.com");
  await page.locator("h1").screenshot({
    path: "example.jpg",
  });
```

it will output:

```
  pw:api => browserType.launch started +0ms
  pw:api <= browserType.launch succeeded +297ms
  pw:api => browser.newContext started +1ms
  pw:api <= browser.newContext succeeded +17ms
  pw:api => browserContext.newPage started +0ms
  pw:api <= browserContext.newPage succeeded +171ms
  pw:api => page.goto started +0ms
  pw:api navigating to "https://example.com/", waiting until "load" +1ms
  pw:api   "commit" event fired +88ms
  pw:api   navigated to "https://example.com/" +1ms
  pw:api   "load" event fired +3ms
  pw:api <= page.goto succeeded +0ms
  pw:api => locator.screenshot started +1ms
  pw:api waiting for selector "h1" +1ms
  pw:api   "domcontentloaded" event fired +26ms
  pw:api   selector resolved to visible <h1>Example Domain</h1> +29ms
  pw:api taking element screenshot +4ms
  pw:api   waiting for element to be visible and stable +5ms
  pw:api   element is visible and stable +26ms
  pw:api <= locator.screenshot succeeded +35ms
  pw:api => browser.close started +1ms
  pw:api <= browser.close succeeded +376ms
```

If you have code we can run that illustrates where it's giving you an issue, we can better understand the problem to try to fix it. Here's a code pointer in case you're curious about what it's doing under the hood: https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/screenshotter.ts (there's also browser-specific logic, too)

Thanks!

**Comment by KotlinIsland** [comment] 2022-07-19 05:26
@rwell `timeout` doesn't appear in that file at all.

**Comment by rwoll** [comment] 2022-07-19 05:42
> @rwell `timeout` doesn't appear in that file at all, but what I can tell it's just a total timeout for the entire process?

Essentially, yes. Stepping through the code shows how the timeout comes into play:

[`screenshotElement`](https://github.com/microsoft/playwright/blob/9fda46822cb9a7cb39558bc18f2e5298864ca4c4/packages/playwright-core/src/server/screenshotter.ts#L112)'s first arg is a progress reporter. If you look at the functions it calls and passes progress reporter to, you'll see some places where the timeout is referenced.

The screenshot code has a few layers! :) If you have a case where it's behaving unexpectedly, please file a new issue in the main repo with a repro.

@Zeckie re:

> Also, when the timeout occurs, is there a way to determine what it was waiting for (eg is it waiting for the page to load, or something else?)

You can debug by setting the `DEBUG` env var to `pw:api`. It'll output logs like https://github.com/microsoft/playwright-python/issues/1420#issuecomment-1188611288

**Comment by KotlinIsland** [comment] 2022-07-19 05:46
https://github.com/microsoft/playwright/issues/15773

**Comment by Zeckie** [comment] 2022-07-21 05:24
```python
from datetime import datetime

from playwright.sync_api import sync_playwright

with sync_playwright() as pw:
    browser = pw.chromium.launch(headless=False)
    page = browser.new_page()

    # DelayApp - source code at https://github.com/Zeckie/DelayApp
    page.goto("http://localhost:28080/DelayApp/")
    page.screenshot(type="png", path="./first.png")  # works fine
    try:
        print(f"{datetime.now()} About to click link")
        # After clicking this link, the server takes 10 seconds to respond,
        # then the target page has a stylesheet that takes another 20 seconds
        page.click("//a[.='Page 10s CSS 20s IMG 30s']", timeout=5000)
    except Exception as ex:
        print(f"{datetime.now()} Click caught: {ex}")

    try:
        print(f"{datetime.now()} About to call screenshot")
        page.screenshot(type="png", path="./second.png", timeout=10000)
        print(f"{datetime.now()} It worked!")
    except Exception as ex:
        print(f"{datetime.now()} Screenshot caught: {ex}")

    print(f"{datetime.now()} About to call screenshot (timeout=0)")
    page.screenshot(type="png", path="./third.png", timeout=0) # waits until jsp + stylesheet loaded
    print(f"{datetime.now()} Closing")
    page.close()
    browser.close()
```

Output:
```
2022-07-21 15:19:28.833430 About to click link
2022-07-21 15:19:33.842260 Click caught: Timeout 5000ms exceeded.
=========================== logs ===========================
waiting for selector "//a[.='Page 10s CSS 20s IMG 30s']"
  selector resolved to visible <a href="page.jsp?delay=10000&css=20000&img=30000">Page 10s CSS 20s IMG 30s</a>
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
============================================================
2022-07-21 15:19:33.842260 About to call screenshot
2022-07-21 15:19:43.850827 Screenshot caught: Timeout 10000ms exceeded.
=========================== logs ===========================
taking page screenshot
============================================================
2022-07-21 15:19:43.850827 About to call screenshot (timeout=0)
2022-07-21 15:19:59.637647 Closing
```

**Comment by Zeckie** [comment] 2022-07-21 05:50
And with `DEBUG` = `pw:api`

```
2022-07-21T05:46:31.960Z pw:api navigating to "http://localhost:28080/DelayApp/", waiting until "load"
2022-07-21T05:46:31.983Z pw:api   "commit" event fired
2022-07-21T05:46:31.983Z pw:api   navigated to "http://localhost:28080/DelayApp/"
2022-07-21T05:46:31.984Z pw:api   "load" event fired
2022-07-21T05:46:31.986Z pw:api taking page screenshot
2022-07-21T05:46:32.003Z pw:api   "domcontentloaded" event fired
2022-07-21 15:46:32.217872 About to click link
2022-07-21T05:46:32.212Z pw:api waiting for selector "//a[.='Page 10s CSS 20s IMG 30s']"
2022-07-21T05:46:32.229Z pw:api   selector resolved to visible <a href="page.jsp?delay=10000&css=20000&img=30000">Page 10s CSS 20s IMG 30s</a>
2022-07-21T05:46:32.233Z pw:api attempting click action
2022-07-21T05:46:32.234Z pw:api   waiting for element to be visible, enabled and stable
2022-07-21T05:46:32.294Z pw:api   element is visible, enabled and stable
2022-07-21T05:46:32.294Z pw:api   scrolling into view if needed
2022-07-21T05:46:32.295Z pw:api   done scrolling
2022-07-21T05:46:32.299Z pw:api   performing click action
2022-07-21T05:46:37.223Z pw:api taking page screenshot
2022-07-21 15:46:37.230489 Click caught: Timeout 5000ms exceeded.
=========================== logs ===========================
waiting for selector "//a[.='Page 10s CSS 20s IMG 30s']"
  selector resolved to visible <a href="page.jsp?delay=10000&css=20000&img=30000">Page 10s CSS 20s IMG 30s</a>
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
============================================================
2022-07-21 15:46:37.230489 About to call screenshot
2022-07-21T05:46:42.360Z pw:api   click action done
2022-07-21T05:46:42.360Z pw:api   waiting for scheduled navigations to finish
2022-07-21T05:46:42.361Z pw:api   "commit" event fired
2022-07-21T05:46:42.361Z pw:api   navigated to "http://localhost:28080/DelayApp/page.jsp?delay=10000&css=20000&img=30000"
2022-07-21T05:46:42.361Z pw:api   navigated to "http://localhost:28080/DelayApp/page.jsp?delay=10000&css=20000&img=30000"
2022-07-21T05:46:42.364Z pw:api   navigations have finished
2022-07-21 15:46:47.232317 Screenshot caught: Timeout 10000ms exceeded.
=========================== logs ===========================
taking page screenshot
============================================================
2022-07-21 15:46:47.232317 About to call screenshot (timeout=0)
2022-07-21T05:47:02.371Z pw:api   "domcontentloaded" event fired
2022-07-21T05:47:02.682Z pw:api taking page screenshot
2022-07-21 15:47:03.006954 Closing
```

**Comment by rwoll** [comment] 2022-07-21 20:14
Folding into https://github.com/microsoft/playwright/issues/15773

**Closed by rwoll** 2022-07-21 20:14 UTC
Labels: triaging

**Comment by Zeckie** [comment] 2022-07-22 01:17
I noticed in the debug output above that about 5 seconds after the `click` had timed out,  there was an entry `click action done`. Is that normal? Does that mean the timeout is only in the python code, and playwright is still waiting for the click to finish before doing the screenshot? 

`2022-07-21 15:46:37.230489 Click caught: Timeout 5000ms exceeded.`

`2022-07-21T05:46:42.360Z pw:api   click action done`
