### ISSUE TITLE
Resource temporarily unavailable error in docker container using simple playwright function

### ISSUE THREAD

**Issue by indiejohnny** [microsoft/playwright-python#451] opened 2021-01-21 08:14 UTC
Hello. I'm using playwright with "python:3.7-slim-buster" docker image. 

I basically go to given url and return it's page source and screenshot.

```
def get_url(url: str):
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        context = browser.newContext(
            viewport={"width": 1200, "height": 600},
            ignoreHTTPSErrors=True,
            javaScriptEnabled=True,
        )

        page = context.newPage()
        logging.info(f"Going to :[{url}]")
        page.goto(url, waitUntil="load", timeout=TIMEOUT)

        page_source = page.content()
        screenshot = page.screenshot()
        page.close()
        context.close()
        browser.close()
        p.stop()
        del p
        logging.info(f"Browser closed for :[{url}]")

    return page_source, screenshot
```

As you can see above, I close page, context, browser then I stop sync_playwright then I delete it. But still, after closing a browser, in docker when I check processes with "ps aux" I'm still seeing defunct playwright processes. And they still there until I restart the container.
![Screenshot at 2021-01-21 11-04-26](https://user-images.githubusercontent.com/17926639/105321729-e3551680-5bd8-11eb-98cd-3822446ef07f.png)

And, after calling this function about 200 times, I get an error:
![Screenshot at 2021-01-21 11-10-38](https://user-images.githubusercontent.com/17926639/105322041-5494c980-5bd9-11eb-8e32-7e6104f48276.png)

**Comment by kumaraditya303** [comment] 2021-01-21 08:44
> Hello. I'm using playwright with "python:3.7-slim-buster" docker image.
> 
> I basically go to given url and return it's page source and screenshot.
> 
> ```
> def get_url(url: str):
>     with sync_playwright() as p:
>         browser = p.chromium.launch(headless=True)
>         context = browser.newContext(
>             viewport={"width": 1200, "height": 600},
>             ignoreHTTPSErrors=True,
>             javaScriptEnabled=True,
>         )
> 
>         page = context.newPage()
>         logging.info(f"Going to :[{url}]")
>         page.goto(url, waitUntil="load", timeout=TIMEOUT)
> 
>         page_source = page.content()
>         screenshot = page.screenshot()
>         page.close()
>         context.close()
>         browser.close()
>         p.stop()
>         del p
>         logging.info(f"Browser closed for :[{url}]")
> 
>     return page_source, screenshot
> ```
> 
> As you can see above, I close page, context, browser then I stop sync_playwright then I delete it. But still, after closing a browser, in docker when I check processes with "ps aux" I'm still seeing defunct playwright processes. And they still there until I restart the container.
> ![Screenshot at 2021-01-21 11-04-26](https://user-images.githubusercontent.com/17926639/105321729-e3551680-5bd8-11eb-98cd-3822446ef07f.png)
> 
> And, after calling this function about 200 times, I get an error:
> ![Screenshot at 2021-01-21 11-10-38](https://user-images.githubusercontent.com/17926639/105322041-5494c980-5bd9-11eb-8e32-7e6104f48276.png)

@indiejohnny There is no need to `del p` as it is being used a context manager. Try removing the `del` statement

**Comment by indiejohnny** [comment] 2021-01-21 08:47
> > Hello. I'm using playwright with "python:3.7-slim-buster" docker image.
> > I basically go to given url and return it's page source and screenshot.
> > ```
> > def get_url(url: str):
> >     with sync_playwright() as p:
> >         browser = p.chromium.launch(headless=True)
> >         context = browser.newContext(
> >             viewport={"width": 1200, "height": 600},
> >             ignoreHTTPSErrors=True,
> >             javaScriptEnabled=True,
> >         )
> > 
> >         page = context.newPage()
> >         logging.info(f"Going to :[{url}]")
> >         page.goto(url, waitUntil="load", timeout=TIMEOUT)
> > 
> >         page_source = page.content()
> >         screenshot = page.screenshot()
> >         page.close()
> >         context.close()
> >         browser.close()
> >         p.stop()
> >         del p
> >         logging.info(f"Browser closed for :[{url}]")
> > 
> >     return page_source, screenshot
> > ```
> > 
> > 
> > As you can see above, I close page, context, browser then I stop sync_playwright then I delete it. But still, after closing a browser, in docker when I check processes with "ps aux" I'm still seeing defunct playwright processes. And they still there until I restart the container.
> > ![Screenshot at 2021-01-21 11-04-26](https://user-images.githubusercontent.com/17926639/105321729-e3551680-5bd8-11eb-98cd-3822446ef07f.png)
> > And, after calling this function about 200 times, I get an error:
> > ![Screenshot at 2021-01-21 11-10-38](https://user-images.githubusercontent.com/17926639/105322041-5494c980-5bd9-11eb-8e32-7e6104f48276.png)
> 
> @indiejohnny There is no need to `del p` as it is being used a context manager. Try removing the `del` statement

Actually I put del statement after I got this error. It didn't change anything, with or without del statement.

**Comment by pavelfeldman** [comment] 2021-01-21 16:55
Can you repro it locally on your host system or only in the docker?

Playwright runs a driver child process  called playwright-cli under the hood and what we see here is that this driver becomes zombie. Which is not what it can do by design - when you exit the `sync_playwright()` context, Playwright closes the pipe to playwright-cli and that one is supposed to self-destruct. Could it be that there is an unhandled error in the middle of your handler?

**Comment by indiejohnny** [comment] 2021-01-25 11:33
I ran my code block adding this part end of it:
```
for a in range(200):
    print(a)
    get_url("http://example.com")
```

I followed `a` and processes running on my host system. As `a` increases, `[playwright.sh] <defunct>` processes increased as well.
![Screenshot at 2021-01-25 14-31-11](https://user-images.githubusercontent.com/17926639/105700502-fdb12c00-5f19-11eb-8aa0-1f192f013d59.png)

I also, update my package with the latest one (playwright==1.8.0a1). When I stop my program, child/zombie processes killed as well.

**Comment by indiejohnny** [comment] 2021-01-28 08:02
@pavelfeldman @kumaraditya303 Any updates?

**Comment by kumaraditya303** [comment] 2021-02-14 14:15
@indiejohnny Try this snippet
```py
def get_url(url: str):
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        context = browser.newContext(
            viewport={"width": 1200, "height": 600},
            ignoreHTTPSErrors=True,
            javaScriptEnabled=True,
        )

        page = context.newPage()
        logging.info(f"Going to :[{url}]")
        page.goto(url, waitUntil="load", timeout=TIMEOUT)

        page_source = page.content()
        screenshot = page.screenshot()
        page.close()
        context.close()
        browser.close()
        logging.info(f"Browser closed for :[{url}]")

    return page_source, screenshot
```

**Comment by indiejohnny** [comment] 2021-02-17 11:41
@kumaraditya303 I already try that snippet.

**Comment by pavelfeldman** [comment] 2021-03-02 17:30
@indiejohnny could you try official Playwright docker [image](https://playwright.dev/docs/next/docker) and see if you experience the same?

**Comment by pavelfeldman** [comment] 2021-03-30 18:06
Closing non-actionable bugs as a part of the triage. We need more information to address your issue. Please file a new one with the questions above answered and we'll be able to help.

**Closed by pavelfeldman** 2021-03-30 18:06 UTC
Labels: triaging
