### ISSUE TITLE
[BUG] Cannot use IPython REPL with Playwright

### ISSUE THREAD

**Issue by spookylukey** [microsoft/playwright-python#2060] opened 2023-09-06 11:59 UTC
Use case: I want to write tests interactively using a Python REPL, specifically the IPython REPL. Why? Because this is an [awesome and superior way to program](https://lukeplant.me.uk/blog/posts/repl-python-programming-and-debugging-with-ipython/) :smile:   especially for writing tests of an interactive session with a browser.

### System info
- Playwright Version: 1.37.0 
- OS: LinuxMint

### Source code

- [X] I provided exact source code that allows reproducing the issue locally.

**Test file**

```python
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch(headless=False)
    page = browser.new_page()

    import IPython
    IPython.embed()

    browser.close()
```

**Expected**

I should be able to see an IPython REPL and interactively write my Playwright tests to control the  browser.

**Actual**

```
...
RuntimeError: This event loop is already running
sys:1: RuntimeWarning: coroutine 'Application.run_async' was never awaited
```

I think I'm expecting the reply of "use the async API", but you get the same behaviour with async:

```python
import asyncio

from playwright.async_api import async_playwright


async def run(playwright):
    chromium = playwright.chromium
    browser = await chromium.launch(headless=False)
    context = await browser.new_context()
    await context.new_page()

    import IPython
    IPython.embed()

    await browser.close()


async def main():
    async with async_playwright() as playwright:
        await run(playwright)


asyncio.run(main())
```

(I have a workaround, but I'm still logging this as a bug in case there is a bugfix or better workaround)

**Comment by spookylukey** [comment] 2023-09-06 12:06
Here is the workaround I have:
```bash
pip install nest-asyncio
```

Then embed IPython as follows:
```python
import IPython
import nest_asyncio

nest_asyncio.apply()
IPython.embed()
```

**Comment by mxschmitt** [comment] 2023-09-09 20:24
We recommend the workaround as of today. Or use the plain normal breakpoint() REPL. The issue is that we have our own async loop and iPython internally also wants to create one, which is not possible as per Python spec. This looks more like an IPython issue rather than a Playwright issue to me, so not sure if we can act on it.

**Comment by mxschmitt** [comment] 2023-09-18 07:38
Closing then as per above, since this is not actionable for us and it most likely won't change in the near future.

Thanks for your understanding!

**Closed by mxschmitt** 2023-09-18 07:38 UTC
