### ISSUE TITLE
[Bug]: AttributeError: 'PlaywrightContextManager' object has no attribute '_playwright'

### ISSUE THREAD

**Issue by KotlinIsland** [microsoft/playwright-python#999] opened 2021-11-02 05:29 UTC
### Playwright version

1.16.1

### Operating system

Windows

### Other information

python 3.10.0

### What happened? / Describe the bug

I see `AttributeError` sometimes when I run playwright.

### Code snippet to reproduce your bug

```shell
from playwright.sync_api import sync_playwright

for i in range(10000):
    print(i)
    with sync_playwright() as p:
        pass
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "...\scratches\scratch_1.py", line 4, in <module>
    print(i)
  File "...\venv\lib\site-packages\playwright\sync_api\_context_manager.py", line 71, in __enter__
    playwright = self._playwright
AttributeError: 'PlaywrightContextManager' object has no attribute '_playwright'
```

**Comment by KotlinIsland** [comment] 2021-11-02 05:47
sounds like #874 if you ask me

**Comment by phoenixor** [comment] 2021-11-25 00:58
i followed the official example
`from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()
    page.goto("http://playwright.dev")
    print(page.title())
    browser.close()`
and i got this bug:
`Node.js is only supported on Windows 8.1, Windows Server 2012 R2, or higher.
Setting the NODE_SKIP_PLATFORM_CHECK environment variable to 1 skips this
check, but Node.js might not execute correctly. Any issues encountered on
unsupported platforms will not be fixed.Traceback (most recent call last):

AttributeError: 'PlaywrightContextManager' object has no attribute '_playwright'
Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<Connection.run.<locals>.init() running at D:\python\py_projects\police_helper\.venv\lib\site-packages\playwright\_impl\_connection.py:179> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x0000000002678B20>()]>>`

platform: windows 7
nodejs v13.14.0
playwright python 1.17.0
python 3.8.10

**Comment by KotlinIsland** [comment] 2021-11-25 03:47
@phoenixor use triple backticks if you wanna have a multi line code block, and can you upvote this issue please.

**Comment by phoenixor** [comment] 2021-11-25 05:02
> @phoenixor use triple backticks if you wanna have a multi line code block, and can you upvote this issue please.

have you fixed this bug??

**Comment by KotlinIsland** [comment] 2021-11-25 05:39
Interesting, the reason it failed for you is that node needs windows 8, and you have windows 7, the docs don't mention this as a requirement.

**Comment by bnx05** [comment] 2021-11-26 09:42
@phoenixor I'm running into this same issue, were you able to fix it/find a workaround?

**Comment by phoenixor** [comment] 2021-11-28 00:57
> Interesting, the reason it failed for you is that node needs windows 8, and you have windows 7, the docs don't mention this as a requirement.

the problem is not nodejs version i think. i'v tried to reinstall nodejs v11.15.0 and v10.24.1, but i got the same bug

**Comment by remiliacn** [comment] 2021-11-28 01:21
From [System Requirements](https://playwright.dev/docs/library/#system-requirements) in the official Doc
> Playwright requires Node.js version 12 or above. The browser binaries for Chromium, Firefox and WebKit work across the 3 platforms (Windows, macOS, Linux):

So node.js downgrade won't work.

**Comment by phoenixor** [comment] 2021-11-28 03:29
> From [System Requirements](https://playwright.dev/docs/library/#system-requirements) in the official Doc
> 
> > Playwright requires Node.js version 12 or above. The browser binaries for Chromium, Firefox and WebKit work across the 3 platforms (Windows, macOS, Linux):
> 
> So node.js downgrade won't work.

you read the wrong offical doc of Playwright-nodejs，but my question is playwright-python

**Comment by KotlinIsland** [comment] 2021-11-28 03:30
Doesn't playwright install it's own node?

**Comment by phoenixor** [comment] 2021-11-28 04:54
> Doesn't playwright install it's own node?

you mean i just need to install Playwright-python and i got nodejs environment at the same time???

**Comment by KotlinIsland** [comment] 2021-11-28 05:15
yep

**Comment by phoenixor** [comment] 2021-11-28 07:24
> yep

still don't work, maybe playwright-python can not work on win7

**Comment by mxschmitt** [comment] 2021-12-01 14:06
@KotlinIsland which version of Windows are you using? Does it also reproduce for you when using Playwright normally? (instead of using the loop and pass etc)

**Comment by KotlinIsland** [comment] 2021-12-02 00:58
@mxschmitt Version 1909 (OS Build 18363.1801)

**Comment by AtuboDad** [comment] 2021-12-14 09:16
Same question: AttributeError: 'PlaywrightContextManager' object has no attribute '_playwright'.

But, when i back to version: 1.15.3,it works well.

**Comment by mxschmitt** [comment] 2021-12-27 18:28
Closing since Playwright does not support Windows 7 or Windows Server 2008. Both versions are end of life and not supported anymore (security updates by Microsoft as well).

**Closed by mxschmitt** 2021-12-27 18:28 UTC
Labels: triaging

**Comment by KotlinIsland** [comment] 2021-12-27 19:38
> Closing since Playwright does not support Windows 7 or Windows Server 2008. Both versions are end of life and not supported anymore (security updates by Microsoft as well).

The op was windows 10, not 7

**Comment by DetachHead** [comment] 2022-07-01 06:06
@mxschmitt can you reopen this please? the issue happens on windows 10 as @KotlinIsland said

**Comment by mxschmitt** [comment] 2022-07-01 07:58
Please file a new issue, since this one is old with a clear repro and make sure it reproduce on 1.23.

**Comment by CasperdenHaan** [comment] 2022-10-29 19:02
I got the same issue, Win 11, 1.27.1. I can't find anything else about this online except for this issue. What i've gathered form the comments on this issue, the problem lies with node? The weird thing is when i run the same exact code on a virual machine it runs just fine. I think it has more to do with any local differences.

Traceback (most recent call last):
  File "c:\Users\caspe\Documents\Programmeren\Python\test.py", line 3, in <module>
    with sync_playwright() as p:
  File "C:\Users\caspe\AppData\Roaming\Python\Python310\site-packages\playwright\sync_api\_context_manager.py", line 89, in __enter__
    playwright = self._playwright
AttributeError: 'PlaywrightContextManager' object has no attribute '_playwright'
Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<Connection.run.<locals>.init() running at C:\Users\caspe\AppData\Roaming\Python\Python310\site-packages\playwright\_impl\_connection.py:222> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[ProtocolCallback.__init__.<locals>.cb() at C:\Users\caspe\AppData\Roaming\Python\Python310\site-packages\playwright\_impl\_connection.py:145]>
Future exception was never retrieved
future: <Future finished exception=BrokenPipeError(32, 'The pipe is being closed', None, 232, None)>
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\asyncio\proactor_events.py", line 397, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
  File "C:\Program Files\Python310\lib\asyncio\windows_events.py", line 539, in send
    ov.WriteFile(conn.fileno(), buf)
BrokenPipeError: [WinError 232] The pipe is being closed
