### ISSUE TITLE
too many chrome processes left after the playwright browsing

### ISSUE THREAD

**Issue by XufengXufengXufeng** [microsoft/playwright-python#984] opened 2021-10-26 23:53 UTC
![image](https://user-images.githubusercontent.com/31204817/138976976-0af979e8-18d5-4795-ae44-57f8ab1b95f2.png)
i use python api and always use the 'with' clause. but after a few web goto, my system filled with a lot of the chrome processes even though my program has long finished.

**Comment by kumaraditya303** [comment] 2021-11-17 12:41
@mxschmitt @pavelfeldman Any update on this,when will this be fixed ?

**Comment by mxschmitt** [comment] 2021-12-10 22:04
Closing since we were not able to reproduce it. Please create a new issue with Python/OS/ etc. and preferable some code which helps to repro it.

**Closed by mxschmitt** 2021-12-10 22:04 UTC

**Comment by cpwan** [comment] 2021-12-14 07:12
Hi, same issure here. 
I am using docker. I installed playwright 1.17.0 with 
```shell
pip install --upgrade pip
pip install playwright
playwright install
```

## Code 
```python
# debug.py
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch(headless=True)
    page = browser.new_page()
    page.close()
    browser.close()
```
## Screenshot
![image](https://user-images.githubusercontent.com/22132868/145949947-261d009d-b82e-4a7b-979e-195e442bf1e2.png)

**Comment by cpwan** [comment] 2021-12-15 01:52
That was the problem with my container.  Specifying `--init` tag like `docker run --init xxxx` solves my problem.
