### ISSUE TITLE
[Question]: playwright hung up on win 10

### ISSUE THREAD

**Issue by WilliamQue** [microsoft/playwright-python#1428] opened 2022-07-13 10:05 UTC
### Your question

I installed the last playwright on python 3.9, then installed the embeded browsers, following the contents of Get started. everything was ok! But when running the testing codes, it seemed that the process hung up and I had to click stop button to kill the process.

I'v tested it on 2 pc of win10, same problems occurred, but I tried it on a centos machine, it's ok without problems.

So, some configurations are needed on win 10?

```
pip install playwright
playwright install

from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    for browser_type in [p.firefox, p.webkit]:
        browser = browser_type.launch()
        page = browser.new_page()
        page.goto('http://whatsmyuseragent.org/')
        page.screenshot(path=f'example-{browser_type.name}.png')
        browser.close()
```

It seems the codes will hang up on the second line
```
from playwright.sync_api import sync_playwright
playwright = sync_playwright().start()     # ERROR

browser = playwright.chromium.launch()
page = browser.new_page()
page.goto("httpw://www.baidu.com/")
print(page.title())
browser.close()
```
playwright.stop()

**Comment by WilliamQue** [comment] 2022-07-13 17:38
I got a warning message from win 10.

The 应用程序-特定 permission settings do not grant 本地 激活 (perharps local activation) permission for the COM Server application with CLSID 
{2593F8B9-4EAF-457C-B68A-50F6B8EA6B54}
 and APPID 
{15C20B67-12E7-4BB6-92BB-7AFF07997402}
 to the user PC\XXX SID (S-1-5-21-1225340504-3773195990-948549997-1001) from address LocalHost (使用 LRPC) running in the application container 不可用 SID (不可用). This security permission can be modified using the Component Services administrative tool.

**Comment by rwoll** [comment] 2022-07-14 04:41
Thanks for the report! Sorry it's not working smoothly!

I cannot repro on Win10 and the bots are passing without issue. Are your Win10 machines managed by a company/corp? I suspect there is something specific about the configuration that's not allowing Playwright to run properly.

You can run with the `DEBUG` env var set to get more logs from Playwright: https://playwright.dev/python/docs/next/debug#verbose-api-logs

**Comment by rwoll** [comment] 2022-07-18 18:43
Closing as part of triage. Please refile, reference this issue, and include the requested info if the issue is still not addressed. Thanks!

**Closed by rwoll** 2022-07-18 18:43 UTC
Labels: triaging
