### ISSUE TITLE
[Question]: Uploading big file crashes the browser

### ISSUE THREAD

**Issue by rai-gaurav** [microsoft/playwright-python#915] opened 2021-09-20 15:44 UTC
### Your question

I have a scenorio where I have to upload some big files - 150MB and 250 MB.
I am following this doc - https://playwright.dev/python/docs/input/#upload-files
For smaller file, I found it working but for bigger files it fails.
I tried to use both `set_input_files` and `expect_file_chooser` but got the similar issue.

Using `set DEBUG=pw:browser` I got the buffer error.

```
  pw:browser [pid=7016][err] [7016:11564:0920/113948.785:ERROR:http_connection.cc(37)] Too large read data is pending: capacity=104857600, max_buffer_size=104857600, read=104857600 +11s
  pw:browser [pid=7016][err] [7016:11564:0920/113948.785:ERROR:devtools_pipe_handler.cc(282)] Connection closed, not enough capacity +4ms
```
Do I need to set some flag for bigger files ? Or is there any workaround to get it working ?

Playwright Version - 1.14.1
OS - Windows 10 (64 bit)
Browser - Chrome
Python- 3.8.4

**Comment by mxschmitt** [comment] 2021-09-20 15:47
Sounds like a duplicate of https://github.com/microsoft/playwright/issues/3768

Uploading files bigger than 50MB is currently not possible.

**Comment by mxschmitt** [comment] 2021-09-21 07:44
Closing and merging into the other one. Please upvote it there.

**Closed** 2021-09-21 07:44 UTC
Labels: triaging
