### ISSUE TITLE
[Bug]: Playwright functions are getting stuck

### ISSUE THREAD

**Issue by gargvarun072** [microsoft/playwright-python#2543] opened 2024-09-01 03:09 UTC
### Version

1.46.0

### Steps to reproduce

`

    import time
    from playwright.sync_api import Page, sync_playwright
    CHROME_EXECUTABLE_PATH = "/app/ungoogled-chromium_125.0.6422.141-1_linux/chrome"
 
    with sync_playwright() as playwright:

    browser = playwright.chromium.launch(
            executable_path=CHROME_EXECUTABLE_PATH,
            args=[
                "--no-sandbox",
                "--disable-setuid-sandbox",
                "--disable-dev-shm-usage",
                # Enabling dev tools to execute the JavaScript and make it persistent
                "--auto-open-devtools-for-tabs",
                "--test-type",
                "--enable-logging",
                "--ignore-certificate-errors",
                "--ignore-certificate-errors-spki-list",
                "--window-size=1280,720",
                "--disable-browser-side-navigation"
            ],
            env={
                "DISPLAY": ":0",
            },
            headless=True,
            timeout=30 * 1000,
        )
    
    browserContext = browser.new_context(java_script_enabled=True, bypass_csp=True)

    if len(browserContext.pages) == 0:
        page = browserContext.new_page()
    else:
        page = browserContext.pages[0]

    page.set_default_timeout(60000)

    browserContext.tracing.start(screenshots=True, snapshots=True, sources=True)

    try:
        print("started")
        page.goto("XXXXXXXX")

        inputUserXpath = '//*[@id="email"]'
        passwordXpath = '//*[@id="passphrase"]'

        username = "XXXXXXX"
        passowrd = "XXXXXX"

        page.fill(inputUserXpath, username)
        page.fill(passwordXpath, password)
        
        print("input")
        page.screenshot(path="test.png")

        sign_in_buttons = page.locator('//span[contains(text(), "Sign In")]')

        # Count the number of buttons found
        button_count = sign_in_buttons.count()

        print(f"Found {button_count} 'Sign In' button(s).")

        # Click each "Sign In" button
        for i in range(button_count):
            sign_in_buttons.nth(i).click()
            print(f"Clicked 'Sign In' button {i+1}")

        print("click")
        page.screenshot(path="test2.png")

        page.wait_for_timeout(10000)

        if browser.is_connected():
            print("The browser is open.")
        else:
            print("The browser is closed.")
        page.screenshot(path="test3.png")

        page.wait_for_timeout(10000)

        page.screenshot(path="test4.png", timeout=10000)

        page.wait_for_load_state(state="networkidle")

        if browser.is_connected():
            print("The browser is open.")
        else:
            print("The browser is closed.")
        page.screenshot(path="test5.png", timeout=10000)

    except Exception as e:
        print(e)

    browserContext.tracing.stop(path="trace.zip")
    print("trace generated")

    page.screenshot(path="test5.png", timeout=10000)

    print("here")`
    

**Output**
 `
started
input
Found 1 'Sign In' button(s).
Clicked 'Sign In' button 1
click
The browser is open.
^CTraceback (most recent call last):
  File "/app/test.py", line 85, in <module>
    page.wait_for_timeout(10000)
  File "/root/.cache/pypoetry/virtualenvs/browser-9TtSrW0h-py3.12/lib/python3.12/site-packages/playwright/sync_api/_generated.py", line 11235, in wait_for_timeout
    self._sync(self._impl_obj.wait_for_timeout(timeout=timeout))
  File "/root/.cache/pypoetry/virtualenvs/browser-9TtSrW0h-py3.12/lib/python3.12/site-packages/playwright/_impl/_sync_base.py", line 113, in _sync
    self._dispatcher_fiber.switch()
  File "/root/.cache/pypoetry/virtualenvs/browser-9TtSrW0h-py3.12/lib/python3.12/site-packages/playwright/sync_api/_context_manager.py", line 56, in greenlet_main
    self._loop.run_until_complete(self._connection.run_as_sync())
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1949, in _run_once
    event_list = self._selector.select(timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
Future exception was never retrieved
future: <Future finished exception=TargetClosedError('Target page, context or browser has been closed')>
playwright._impl._errors.TargetClosedError: Target page, context or browser has been closed
`

This scenario is not occurring on all websites. And it's not about specific functions as well, it is stuck on any function like screenshot, etc. 

I have tried different Playwright versions and Chrome/ chromium versions but none of them are working as soon as we are using **Firefox**, it works as expected. 

### Expected behavior

Playwright should not be stuck and working on website. 

### Actual behavior

Playwright function are getting stuck

### Environment

```Text
- Docker image - python:3.12.3-slim
- Browser: Chromium/Chrome
- Python Version: 3.12
- Playwright: 1.46.0
```

**Comment by mxschmitt** [comment] 2024-09-02 06:46
While this might be a bug with Playwright, I recommend to apply the best-practises first. This includes:
- Use Locator API: https://playwright.dev/docs/best-practices#use-locators
- Never use `wait_for_timeout`
- Try it without `executable_path` and args - since a custom one falls outside our support
- In theory you can also just drop the wait_for_load_state call

Since the script you shared is not a minimal reproducible, I have to close it for now. I recommend our [debugging utils](https://playwright.dev/python/docs/debug) for further debugging: esp. `DEBUG=pw:api` env var or `page.pause()` to open an Inspector.

**Closed by mxschmitt** 2024-09-02 06:46 UTC
