### ISSUE TITLE
[BUG] chromium browser closes during test execution/debugging i.e. pausing session

### ISSUE THREAD

**Issue by TestTheTest7** [microsoft/playwright-python#1900] opened 2023-05-04 19:52 UTC
### System info
- Playwright Version: [1.31.1]
- Operating System: [Mac OS Monterey (Apple M1, 16GB)]
- Browser: [Chromium]
- Python [3.11.2]
- Selenium 4 grid [4.3.0] 

### Source code:
 [Project](https://github.com/TestTheTest7/pw_project)
 [Related commit](https://github.com/TestTheTest7/pw_project/commit/214a658776e1f6a95fa570644f53067374cdcd4c)

**Describe the bug**

If the test execution time is approx. 4.5-5 minutes browser closes and everything crashes. For simple reproducing I call pause() to pause script execution. It has the same behaviour as the slightly longer test and I note, the execution time I'm talking about is approx 5 minutes for both cases. I get 'Target page, context or browser has been closed' all the time.
Is there some test expiration time or there is an issue cause if the execution doesn't go through selenium server browser behaves well and doesn't close?

**Comment by mxschmitt** [comment] 2023-05-05 08:10
From the next release on we deprecate Selenium integration with Playwright, since the APIs which Playwright relies on are getting removed from Selenium. We recommend [sharding](https://pypi.org/project/pytest-shard/) instead.

Is this also reproducible without Selenium?

**Comment by TestTheTest7** [comment] 2023-05-05 13:24
Thanks @mxschmitt for the quick answer and information. Will find alternative.
No, it s not reproducible without Selenium.

**Comment by mxschmitt** [comment] 2023-05-06 08:25
Thanks! We'll announce the deprecation and removal of Selenium in the next release.

Closing it then for now.

**Closed by mxschmitt** 2023-05-06 08:25 UTC
