### ISSUE TITLE
Cannot find reference 'sync_playwright' in 'sync_api.py'

### ISSUE THREAD

**Issue by vitorbferna** [microsoft/playwright-python#604] opened 2021-03-29 23:33 UTC
I am using a mac, python 3.8 and PyCharm

I am trying to run the example code of playwright

`from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.webkit.launch()
    page = browser.new_page()
    page.goto("http://whatsmyuseragent.org/")
    page.screenshot(path="example.png")
    browser.close()`

but I keep getting these errors

**Traceback (most recent call last):
  File "/Users/user/PycharmProjects/pythonProject2/main.py", line 3, in <module>
    with sync_playwright() as p:
AttributeError: __enter__**

**Comment by mxschmitt** [comment] 2021-03-30 08:06
Which version of Playwright are you using? With which steps can you reproduce this?

**Comment by mxschmitt** [comment] 2021-04-01 18:08
@vitorbferna  which package manager installer are you using and how did you install Playwright?

**Comment by dgozman** [comment] 2021-04-15 18:21
Closing this, since we are unable to reproduce the issue. If you have any new information that helps us reproduce the issue, please comment here.

**Closed by dgozman** 2021-04-15 18:21 UTC
Labels: triaging
