### ISSUE TITLE
[BUG] New install on different environment

### ISSUE THREAD

**Issue by Rivalyr** [microsoft/playwright-python#1740] opened 2023-01-27 04:20 UTC
I cant install playwright for using it for code. 

- Playwright Version: 1.30.0
- Operating System: [e.g. Windows, Linux or Mac]
- Python version: Python 3.11.1
- Browser: All
- Extra: New environment

```python
pip install
playwright install 
playwright install-deps chromium
```

```
import asyncio
from playwright.async_api import async_playwright
```
```
>>> Traceback (most recent call last):
  File "D:\Programacion\Python\python\playwright\PlayWright\src\app.py", line 2, in <module>
    from playwright.async_api import async_playwright
ModuleNotFoundError: No module named 'playwright'
```

since a few days ago i was learning the package in another environment and today. when i did wanted to install it on another environment for practicing. The first thing i realize when i execute "playwright install" anything happen. then i try with 'install-deps' and nothing happens and the output was something like this:

```
>>> (env) D:\Programacion\Python\python\playwright\PlayWright>playwright install --with-deps chromium

(env) D:\Programacion\Python\python\playwright\PlayWright>playwright -V
```

**Comment by mxschmitt** [comment] 2023-01-27 08:55
Looks like you have multiple Python installations on your system, python and pip don't know each other.

I would recommend to install all the Python installations on your system and install it again.

**Comment by Rivalyr** [comment] 2023-01-27 16:49
![image](https://user-images.githubusercontent.com/100269858/215144893-c9288386-baf4-4c07-87f1-940703eae936.png)

Any relate with this?

i have to add the python.exe that is on every environment at the PATH??

**Comment by Rivalyr** [comment] 2023-01-27 19:21
> Looks like you have multiple Python installations on your system, python and pip don't know each other.
> 
> I would recommend to install all the Python installations on your system and install it again.

![image](https://user-images.githubusercontent.com/100269858/215144893-c9288386-baf4-4c07-87f1-940703eae936.png)

Any relate with this?
 i have to add the python folder that is on every environment at the PATH??

**Comment by mxschmitt** [comment] 2023-01-31 10:43
If you install Python on a fresh system then it should be all configured correctly. It's expected that install-deps does nothing, since on Windows its noop.

Oh I think I found the root cause in your case, you have a folder named Playwright, thats why its not finding the right module, could you rename your project to e.g. test_playwright? `D:\Programacion\Python\python\playwright`

**Comment by mxschmitt** [comment] 2023-02-06 10:12
Closing since we cannot act on our side and this is a general Python installation issue, closing as per above.

**Closed by mxschmitt** 2023-02-06 10:13 UTC
Labels: triaging
