### ISSUE TITLE
How to solve this Evaluation failed.

### ISSUE THREAD

**Issue by chpeih** [microsoft/playwright-python#395] opened 2020-12-24 03:07 UTC
Evaluation failed: TypeError: Failed to set the 'innerHTML' property on 'Element': This document requires 'TrustedHTML' assignment
at prepareTemplate (eval at extend (:1987:39), <anonymous>:428:24)
    at Object.html (eval at extend (:1987:39), <anonymous>:407:17)
    at new Recorder (eval at extend (:1987:39), <anonymous>:583:51)
    at new Script (eval at extend (:1987:39), <anonymous>:1024:13)
    at InjectedScript.extend (<anonymous>:1988:16)
    at eval (eval at callFunction (:304:29), <anonymous>:2:35)
    at UtilityScript.callFunction (<anonymous>:305:24)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
    at Connection.sendMessageToServer (/snapshot/playwright-cli/node_modules/playwright/lib/client/connection.js:69:15)
    at Proxy.<anonymous> (/snapshot/playwright-cli/node_modules/playwright/lib/client/channelOwner.js:44:61)
    at Frame._extendInjectedScript (/snapshot/playwright-cli/node_modules/playwright/lib/client/frame.js:360:44)

**Comment by mxschmitt** [comment] 2020-12-28 13:11
Looks like a duplicate of https://github.com/microsoft/playwright-cli/issues/179

**Comment by pavelfeldman** [comment] 2021-01-14 22:56
Yup, a dupe, tracking there.

**Closed by pavelfeldman** 2021-01-14 22:56 UTC
