### ISSUE TITLE
cannot set playwright firefoxUserPrefs for using DRM content

### ISSUE THREAD

**Issue by Shinoby92** [microsoft/playwright-python#287] opened 2020-11-07 12:18 UTC
I try to set a firefoxUserPrefs Dict
i still have to figure out which prefs are needed because I need to enable DRM content.
What I now so far is that one of the needed preference needed is to enable media.gmp-manager.updateEnabled.
I can manually activating it after launch in about:config but not with firefoxUserPrefs. 

I also need to do the same thing for webkit but I cannot find any place to set any settings? how can I set the experimental features of webkit

```
playwright = await async_playwright().start()
prefDict = ''
browser = await playwright.firefox.launch(headless=False, firefoxUserPrefs=prefDict)
```

I tried already these out and none of them are working, what am I doing wrong?

```
prefDict = {'media.gmp-manager.updateEnabled':true}
prefDict = {'media.gmp-manager.updateEnabled':True}
prefDict = {'media.gmp-manager.updateEnabled':'true'}
prefDict = {'media.gmp-manager.updateEnabled':'True'}
prefDict = [{'media.gmp-manager.updateEnabled':true}]
prefDict = [{'media.gmp-manager.updateEnabled':True}]
prefDict = [{'media.gmp-manager.updateEnabled':'true'}]
prefDict = [{'media.gmp-manager.updateEnabled':'True'}]
```

**Comment by mxschmitt** [comment] 2020-11-08 21:35
Could reproduce it:

```py
from playwright import sync_playwright

with sync_playwright() as playwright:
    browser = playwright.firefox.launch(firefoxUserPrefs={"kekstar": "bar"})
    page = browser.newPage()
    page.goto("http://whatsmyuseragent.org/")
    page.screenshot(path="example.png")
    browser.close()
```

With env var `DEBUGP=1` it gets shown in the logs, but won't get received on the pw-client level (DEBUG=*). Will investigate further.

**Comment by Shinoby92** [comment] 2020-11-09 05:08
i guess the bug existed and got fixed in the vanilla non python playwright, what doesnt got fixed in the python version(just a guess)


https://github.com/microsoft/playwright/issues/917

**Comment by pavelfeldman** [comment] 2020-11-12 06:41
I can reproduce it both upstream and downstream. There is something special about these preferences because I can see other preferences in about:config just fine, but these retain their built-in values. @aslushnikov.

**Comment by Shinoby92** [comment] 2020-11-12 16:49
I could reproduce it on OS X (bug reporting was in linux)

I just figure out that starting firefox with 

```
from playwright import sync_playwright

with sync_playwright() as playwright:
    browser = playwright.firefox.launch(headless=False, firefoxUserPrefs={"kekstar": "bar"})
    page = browser.newPage()
    page.goto("http://whatsmyuseragent.org/")
    page.screenshot(path="example.png")
    time.sleep(2000)
    browser.close()
```

creates a profile folder in
OS X path 
> /private/var/folders/xy/g6gksh6n7nldmrqg8lxb9z600000gn/T/playwright_firefoxdev_profile-SND7pI
(the ending -SND7pI is always randomly created)
and when I ctrl-c close the script it deletes the profile folder from that path.

I thought there may be a easy workaround solution like -> 
copying a autoconfig file in the profile path before starting playwright 
explained here [https://support.mozilla.org/de/kb/firefox-mit-autoconfig-anpassen](url)
 but not possible due the profile is created dynamically and not static (better it stays like that) 

or a second solution would be to looking for the path after starting and change the config and reload it then somethow.
but that's too complicated. So I hope that's getting fixed, I guess watching the behaviour of playwright from node should be a hint how to solve that problem.
I guess playwright don't copy the settings in the profile path due to incorrectly using the wrong profile path (maybe?) or doesn't even takes the arguments

**Comment by Shinoby92** [comment] 2020-11-12 17:00
I could reproduce it on OS X (bug reporting was in linux)

I just figure out that starting firefox with 

```
from playwright import sync_playwright

with sync_playwright() as playwright:
    browser = playwright.firefox.launch(headless=False, firefoxUserPrefs={"kekstar": "bar"})
    page = browser.newPage()
    page.goto("http://whatsmyuseragent.org/")
    page.screenshot(path="example.png")
    time.sleep(2000)
    browser.close()
```

creates a profile folder in
OS X path 
/private/var/folders/xy/g6gksh6n7nldmrqg8lxb9z600000gn/T/playwright_firefoxdev_profile-SND7pI
(the ending -SND7pI is always randomly created)
and when I ctrl-c close the script it deletes the profile folder from that path.

I thought there may be a easy workaround copying a autoconfig file (explained [here](https://support.mozilla.org/de/kb/firefox-mit-autoconfig-anpassen))  in the profile path before starting playwright 
 but not possible due the profile is created dynamically and not static (I guess behaviour is wanted like that)

a second solution would be to ... looking for the path after starting and change the config file with arguments that are wished, and then reload the firefox config but that's too complicated workaround .

So I hope that's getting fixed,
I guess watching the behaviour of playwright from node should be a hint how to solve that problem, as it seems playwright don't copy the settings in the profile path due to incorrectly path providing (maybe?) or even doesn't do anything with the arguments

**Comment by pavelfeldman** [comment] 2020-11-30 22:21
I can see the value specified just fine. But I can't override DRM-related properties. Could you confirm the same?

![ffox](https://user-images.githubusercontent.com/883973/100672765-3fa56380-3317-11eb-8b07-9d09ea0b5a7b.png)

**Comment by pavelfeldman** [comment] 2020-12-19 00:57
Closing this since the property setting works. But please feel free to reopen one for media specifically.

**Closed by pavelfeldman** 2020-12-19 00:57 UTC
Labels: P3-collecting-feedback

**Comment by Shinoby92** [comment] 2021-03-05 10:52
testing it out now using
prefDict = {"media.gmp-manager.updateEnabled": True, "media.allowed-to-play.enabled": True}

media.allowed-to-play.enabled is enabled 
but still media.gmp-manager.updateEnabled getting ignored
