### ISSUE TITLE
[Bug]: FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by phongtnit** [microsoft/playwright-python#901] opened 2021-09-13 15:11 UTC
### Playwright version

1.13.0

### Operating system

Linux

### What browsers are you seeing the problem on?

Chromium

### Other information

My environment:
```
Node v12.20.1
Python 3.8.10
Ubuntu 20.04
```

### What happened? / Describe the bug

I created every domain url with new context and close context after get content and take a screenshot. When I ran the code  more than 10.000 urls, the code likely crashed because of "**JavaScript heap out of memory**" error. I see some solutions to increase the memory limit in Node by setting `NODE_OPTIONS=--max-old-space-size=<size>` as an environment variable. So, I added `export NODE_OPTIONS=--max-old-space-size=8192` in `nano ~/.profile`. But the setting didn't fix the issue.

How can I fix the issue? 

Thanks in advance,

### Code snippet to reproduce your bug

```shell
context = await self.browser.new_context()
....
context.close()
```

### Relevant log output

```shell
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa18150 node::Abort() [/home/ubuntu/.local/lib/python3.8/site-packages/playwright/driver/node]
 2: 0xa1855c node::OnFatalError(char const*, char const*) [/home/ubuntu/.local/lib/python3.8/site-packages/playwright/driver/node]
 3: 0xb9715e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/home/ubuntu/.local/lib/python3.8/site-packages/playwright/driver/node]
 4: 0xb974d9 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/home/ubuntu/.local/lib/python3.8/site-packages/playwright/driver/node]
 5: 0xd54755  [/home/ubuntu/.local/lib/python3.8/site-packages/playwright/driver/node]
 6: 0xd54de6 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/home/ubuntu/.local/lib/python3.8/site-packages/playwright/driver/node]
 7: 0xd616a5 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/home/ubuntu/.local/lib/python3.8/site-packages/playwright/driver/node]
 8: 0xd62555 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/home/ubuntu/.local/lib/python3.8/site-packages/playwright/driver/node]
 9: 0xd6500c v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/home/ubuntu/.local/lib/python3.8/site-packages/playwright/driver/node]
10: 0xd32eac v8::internal::Factory::NewRawOneByteString(int, v8::internal::AllocationType) [/home/ubuntu/.local/lib/python3.8/site-packages/playwright/driver/node]
11: 0xe3e68b v8::internal::JsonParser<unsigned char>::MakeString(v8::internal::JsonString const&, v8::internal::Handle<v8::internal::String>) [/home/ubuntu/.local/lib/python3.8/site-packages/playwright/driver/node]
12: 0xe411a6 v8::internal::JsonParser<unsigned char>::ParseJsonValue() [/home/ubuntu/.local/lib/python3.8/site-packages/playwright/driver/node]
13: 0xe4181f v8::internal::JsonParser<unsigned char>::ParseJson() [/home/ubuntu/.local/lib/python3.8/site-packages/playwright/driver/node]
14: 0xc485fd v8::internal::Builtin_JsonParse(int, unsigned long*, v8::internal::Isolate*) [/home/ubuntu/.local/lib/python3.8/site-packages/playwright/driver/node]
15: 0x140a9f9  [/home/ubuntu/.local/lib/python3.8/site-packages/playwright/driver/node]
Aborted (core dumped)
```

**Comment by mxschmitt** [comment] 2021-09-13 15:37
Are you doing all of that with the same context? If so, then its probably a duplicate of https://github.com/microsoft/playwright/issues/6319

**Comment by phongtnit** [comment] 2021-09-13 18:57
@mxschmitt No, I used uuid4()  to create new unique context name with every urls.

**Comment by mxschmitt** [comment] 2021-09-13 19:02
How many URLs are you navigating to per context?
Do you have a reproducible?

**Comment by hi-time** [comment] 2021-09-14 11:29
Hello, i met the same issue. I create context per page and it is over 7000 page over. 
> How many URLs are you navigating to per context?
> Do you have a reproducible?

**Comment by mxschmitt** [comment] 2021-09-14 11:37
Can you try creating a new context for every page? or e.g. every 10 pages?

**Comment by phongtnit** [comment] 2021-09-14 15:58
> How many URLs are you navigating to per context?
> Do you have a reproducible?

Hi @mxschmitt , my script created one unique context for one url and close the context. It worked fine about first 10k urls. However, when the script ran more than 10k urls, the error occurs. I guess the issue was about release memory in Nodejs.

**Comment by mxschmitt** [comment] 2021-09-15 14:41
Oh thats interesting and not expected! I'll take a look. Thanks for the report.

**Comment by phongtnit** [comment] 2021-09-15 19:58
@mxschmitt my server should have enough RAM to allocate more RAM to any process [htop](https://imgur.com/5LWIDEo) , you can test with crawling urls from [Majestic](https://majestic.com/reports/majestic-million)

**Comment by mxschmitt** [comment] 2021-09-15 21:50
@phongtnit would it be possible that you can share some of your code? I tried to reproduce it by navigating to 5k URLs but looks good so far and no memory leak after closing the contexts.

**Comment by mxschmitt** [comment] 2021-09-27 09:25
Closing since it seems stale.

**Closed by mxschmitt** 2021-09-27 09:25 UTC
Labels: triaging

**Comment by rigwild** [comment] 2021-12-27 09:36
> > How many URLs are you navigating to per context?
> > Do you have a reproducible?
> 
> Hi @mxschmitt , my script created one unique context for one url and close the context after crawling the url. It worked fine about first 10k urls. However, when the script ran more than 10k urls, the error occurs, sometimes, the error occurred while accessing about 100k urls. I guess the issue was about release memory in Nodejs.

Looks like the same issues than mentionned in comments of #6319

**Comment by rakeshnambiar** [comment] 2023-12-23 12:37
I see a similar issue on version `1.39.0`; the error looks like the one below. I am using Python along with pytest for my scripting.

```
<--- Last few GCs --->
[22:0x67ad560] 89435467 ms: Scavenge 4037.8 (4120.4) -> 4037.3 (4131.2) MB, 5.8 / 0.0 ms  (average mu = 0.968, current mu = 0.213) allocation failure; 
[22:0x67ad560] 89435488 ms: Scavenge 4044.5 (4131.2) -> 4043.5 (4132.4) MB, 6.8 / 0.0 ms  (average mu = 0.968, current mu = 0.213) allocation failure; 
[22:0x67ad560] 89436176 ms: Scavenge 4045.4 (4132.4) -> 4044.4 (4153.2) MB, 683.0 / 0.0 ms  (average mu = 0.968, current mu = 0.213) allocation failure; 
<--- JS stacktrace --->
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb87bc0 node::Abort() [/usr/local/lib/python3.9/site-packages/playwright/driver/node]
 2: 0xa96834  [/usr/local/lib/python3.9/site-packages/playwright/driver/node]
 3: 0xd687f0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/lib/python3.9/site-packages/playwright/driver/node]
 4: 0xd68b97 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/lib/python3.9/site-packages/playwright/driver/node]
 5: 0xf462a5  [/usr/local/lib/python3.9/site-packages/playwright/driver/node]
 6: 0xf[587](https://gitlab.com/nuclera/cloud/custom-software/polaris-ui-test-playwright/-/jobs/5806717160#L587)8d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/lib/python3.9/site-packages/playwright/driver/node]
 7: 0xf32e8e v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/lib/python3.9/site-packages/playwright/driver/node]
 8: 0xf34257 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/lib/python3.9/site-packages/playwright/driver/node]
 9: 0xf147a0 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/usr/local/lib/python3.9/site-packages/playwright/driver/node]
10: 0xf0c214 v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawWithImmortalMap(int, v8::internal::AllocationType, v8::internal::Map, v8::internal::AllocationAlignment) [/usr/local/lib/python3.9/site-packages/playwright/driver/node]
11: 0xf0e4c8 v8::internal::FactoryBase<v8::internal::Factory>::NewRawOneByteString(int, v8::internal::AllocationType) [/usr/local/lib/python3.9/site-packages/playwright/driver/node]
12: 0x11ebb1d v8::internal::String::SlowFlatten(v8::internal::Isolate*, v8::internal::Handle<v8::internal::ConsString>, v8::internal::AllocationType) [/usr/local/lib/python3.9/site-packages/playwright/driver/node]
13: 0x12fae1d v8::internal::Runtime_StringCharCodeAt(int, unsigned long*, v8::internal::Isolate*) [/usr/local/lib/python3.9/site-packages/playwright/driver/node]
14: 0x170a079  [/usr/local/lib/python3.9/site-packages/playwright/driver/node]
Aborted (core dumped)
```
