### ISSUE TITLE
[Question]: chrome extension load and test

### ISSUE THREAD

**Issue by wanghaisheng** [microsoft/playwright-python#1961] opened 2023-06-07 21:27 UTC
### Your question

```
(base) wenke@wenkedeMac-mini hine-latest-paper % python translate_pl.py
/Users/wenke/github/hine-latest-paper/chrome-immersive-translate-0.6.1
Traceback (most recent call last):
  File "/Users/wenke/github/hine-latest-paper/translate_pl.py", line 74, in <module>
    page.goto(base)
  File "/Users/wenke/miniconda3/lib/python3.9/site-packages/playwright/sync_api/_generated.py", line 9256, in goto
    self._sync(
  File "/Users/wenke/miniconda3/lib/python3.9/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/Users/wenke/miniconda3/lib/python3.9/site-packages/playwright/_impl/_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "/Users/wenke/miniconda3/lib/python3.9/site-packages/playwright/_impl/_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/Users/wenke/miniconda3/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "/Users/wenke/miniconda3/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 461, in wrap_api_call
    return await cb()
  File "/Users/wenke/miniconda3/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target page, context or browser has been closed
(base) wenke@wenkedeMac-mini hine-latest-paper % python translate_pl.py
/Users/wenke/github/hine-latest-paper/chrome-immersive-translate-0.6.1
Traceback (most recent call last):
  File "/Users/wenke/github/hine-latest-paper/translate_pl.py", line 43, in <module>
    target.send('Target.activateTarget', {'targetId': target.targets()[0]['targetId']})
AttributeError: 'CDPSession' object has no attribute 'targets'
```

code is here
```
import os
from urllib.parse import quote
from playwright.sync_api import sync_playwright
import time
# https://github.com/immersive-translate/immersive-translate/releases/download/v0.6.1/chrome-immersive-translate-0.6.1.zip
# unzip to this local path
extension_path = "chrome-immersive-translate-0.6.1"
extension_path = os.path.join(os.path.dirname(__file__), extension_path)
print(extension_path)


# Path to the folder containing PDF files
pdf_folder = "hine-en"

# Output folder to save the result PDFs
output_folder = "hine-cn"

def save_pdf_with_extension(page, pdf_path, output_path):
    # Load the PDF file in the browser
    page.goto("file://" + pdf_path)

    # Wait for the PDF to load
    page.wait_for_load_state("networkidle")

    # Use the browser extension to modify the page if needed
    # Replace "extension_function" with the actual function provided by your extension
    page.evaluate("extension_function()")

    
    # Save the modified page as a PDF
    page.pdf(path=output_path)

with sync_playwright() as playwright:
    # Launch the browser with the extension loaded
    browser = playwright.chromium.launch(args=["--load-extension=" + extension_path],headless=False)
    
    context = browser.new_context()
    page = context.new_page()

      # Enable Chrome extension
    target = context.new_cdp_session(context.pages[0])
    target.send('Target.activateTarget', {'targetId': target.targets()[0]['targetId']})
    target.send('Browser.enable')
    target.send('Browser.grantPermissions', {'origin': '', 'permissions': ['management']})
    target.send('Management.enable')

    # Load the extension
    # extension_path = '/path/to/extension/folder'
    extension = target.send('Management.install', {'extensionPath': extension_path})
    target.send('Management.setEnabled', {'extensionId': extension['id'], 'enabled': True})

    # Create a new page in the browser context
    extension_id="bpoadfkcbjbfhfodiogcnhhhpibjhbnh"
    is_installed = page.evaluate(
        '''() => {
            return !!chrome.runtime.getManifest("{extension_id}");
        }'''
        .format(extension_id="bpoadfkcbjbfhfodiogcnhhhpibjhbnh")
    )
    print("Extension installed:", is_installed)    
# chrome-extension://bpoadfkcbjbfhfodiogcnhhhpibjhbnh/pdf/index.html
# chrome-extension://bpoadfkcbjbfhfodiogcnhhhpibjhbnh/pdf/index.html?file=file%3A%2F%2F%2FUsers%2Fwenke%2Fgithub%2Fhine-latest-paper%2Fhine-en%2Fwinston1991.pdf

# chrome-extension://bpoadfkcbjbfhfodiogcnhhhpibjhbnh/pdf/index.html?file=file%3A%2F%2F%2FUsers%2Fwenke%2Fgithub%2Fhine-latest-paper%2Fhine-en%2Fwinston1991.pdf
# chrome-extension://bpoadfkcbjbfhfodiogcnhhhpibjhbnh/pdf/index.html?file=files:///Users/wenke/github/hine-latest-paper/hine-en/chin2018%20(2).pdf
    base="chrome-extension://bpoadfkcbjbfhfodiogcnhhhpibjhbnh/pdf/index.html"
    # Iterate over the PDF files in the folder
    for filename in os.listdir(pdf_folder):
        if filename.endswith(".pdf"):
            pdf_path = os.path.join(pdf_folder, filename)
            output_filename = quote(filename)
            time.sleep(60)
            # url=base+"?file=files://"+os.path.join(os.path.dirname(__file__),pdf_path)
            page.goto(base)
            page.wait_for_load_state('networkidle')
            
            page.locator('#openFile').set_input_files(os.path.join(os.path.dirname(__file__),pdf_path))
            output_path = os.path.join(output_folder, output_filename)
            
            # Save the PDF page with the extension
            save_pdf_with_extension(page, pdf_path, output_path)

    # Close the browser
    browser.close()
```

**Comment by wanghaisheng** [comment] 2023-06-07 21:45
update with this
```
with sync_playwright() as playwright:
    # Launch the browser with the extension loaded
    context = playwright.chromium.launch_persistent_context(
        "",
        headless=False,
        args=[
            f"--disable-extensions-except={extension_path}",
            f"--load-extension={extension_path}",
        ],
    )
    # for manifest v2:
    # background = context.background_pages[0]
    # if not background:
    #     background = context.wait_for_event("backgroundpage")

    # for manifest v3:
    background = context.service_workers[0]
    if not background:
        background = context.wait_for_event("serviceworker")

    extension_id = background.url.split("/")[2]
    print('id=====',extension_id)
    page = context.new_page()

````


aceback (most recent call last):
  File "/Users/wenke/github/hine-latest-paper/translate_pl.py", line 44, in <module>
    background_page = context.wait_for_event('backgroundpage')
  File "/Users/wenke/miniconda3/lib/python3.9/site-packages/playwright/sync_api/_generated.py", line 13656, in wait_for_event
    self._sync(
  File "/Users/wenke/miniconda3/lib/python3.9/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/Users/wenke/miniconda3/lib/python3.9/site-packages/playwright/_impl/_browser_context.py", line 464, in wait_for_event
    pass
  File "/Users/wenke/miniconda3/lib/python3.9/site-packages/playwright/_impl/_event_context_manager.py", line 33, in __aexit__
    await self._future
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded while waiting for event "backgroundpage"
(base) wenke@wenkedeMac-mini hine-latest-paper % python translate_pl.py
Traceback (most recent call last):
  File "/Users/wenke/github/hine-latest-paper/translate_pl.py", line 49, in <module>
    background = context.service_workers[0]
IndexError: list index out of range

**Comment by mxschmitt** [comment] 2023-06-12 09:51
I unfortunately have to close this, since this is not actionable for us. Please provide a full reproducible in form of a GitHub repository withe expected and actual outcome. Thanks for your understanding.

**Closed by mxschmitt** 2023-06-12 09:51 UTC

**Comment by wanghaisheng** [comment] 2023-06-12 11:05
@mxschmitt 
https://github.com/ai4ecd/hine-latest-paper-on-google/blob/main/translate_pl.py
