### ISSUE TITLE
Pipeline job constantly fail with INTERNALERROR on pytest using playwright docker image

### ISSUE THREAD

**Issue by ArnoldGergely** [microsoft/playwright-python#1785] opened 2023-02-27 09:49 UTC
Hello,

I'm having issue since last few days, i cannot run any tests with python-playwright and the docker images **v1.25.0-focal** and later updated to **v1.31.0-focal** however the results are the same. I also updated pytest to latest version (from v7.1.3 to v7.2.1) however that didn't help either.

Docker image:
```
Using Docker executor with image mcr.microsoft.com/playwright/python:v1.31.0-focal ...
Pulling docker image mcr.microsoft.com/playwright/python:v1.31.0-focal ...
Using docker image sha256:04f0efe8383ac016dd3348456b056f6049 ... for mcr.microsoft.com/playwright/python:v1.31.0-focal with digest mcr.microsoft.com/playwright/python@sha256:8cb0c3cda09259a2ad568d5d7f611f8811d33ed089b2c3dbfee049d96140648f ...
```

Error output:
```
$ pytest --env staging tests/web
============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-7.2.1, pluggy-1.0.0
rootdir: /builds/arnoldg/playwright-project
plugins: html-3.2.0, base-url-2.0.0, playwright-0.3.0, metadata-2.0.4
collected 74 items
tests/web/websitest/test_website_kjb.py
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/_pytest/main.py", line 270, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/_pytest/main.py", line 324, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/_pytest/main.py", line 349, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/_pytest/runner.py", line 112, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/_pytest/runner.py", line 131, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/_pytest/runner.py", line 222, in call_and_report
INTERNALERROR>     report: TestReport = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py", line 55, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/builds/arnoldg/playwright-project/conftest.py", line 106, in pytest_runtest_makereport
INTERNALERROR>     page.screenshot(path=screenshot_file)
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/playwright/sync_api/_generated.py", line 9[93](https://gitlab..../arnoldg/playwright-project/-/jobs/15008449#L93)1, in screenshot
INTERNALERROR>     self._sync(
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_sync_base.py", line [104](https://gitlab.../arnoldg/playwright-project/-/jobs/15008449#L104), in _sync
INTERNALERROR>     return task.result()
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_page.py", line 667, in screenshot
INTERNALERROR>     encoded_binary = await self._channel.send("screenshot", params)
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_connection.py", line 44, in send
INTERNALERROR>     return await self._connection.wrap_api_call(
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
INTERNALERROR>     return await cb()
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_connection.py", line 79, in inner_send
INTERNALERROR>     result = next(iter(done)).result()
INTERNALERROR> playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
INTERNALERROR> =========================== logs ===========================
INTERNALERROR> taking page screenshot
INTERNALERROR> ============================================================
======================= no tests ran in 91.01s (0:01:31) =======================
```

**Comment by mxschmitt** [comment] 2023-02-27 09:54
Can you provide a minimal reproducible which we can run locally to reproduce this issue?

**Comment by ArnoldGergely** [comment] 2023-02-28 11:46
Hi Max,

With reverse engineering the code I found the issue and solved the problem. 

The problem:
There were old URL domains for dev/staging environments in the code, those domains were functional with a redirection to the new environment URLs. However the domains were blocked recently, and the routes caused unexpected close of connection on browsers. That triggered this error on pipelines, but it didn't give clear error handling, while on locally it did after some setup.

Error locally:
`E       playwright._impl._api_types.Error: net::ERR_CONNECTION_CLOSED at https://...
E       =========================== logs ===========================
E       navigating to "https://...", waiting until "load"
E       ============================================================`

With the page screenshot:
![connection_closed](https://user-images.githubusercontent.com/22047733/221843999-2a61cbf0-2487-4a06-aa75-cf963377e48c.png)

**Comment by mxschmitt** [comment] 2023-02-28 15:01
Well done! So since the error is clear, timeout error due screenshot and the cause has been identified, I'm closing it for now.

**Closed by mxschmitt** 2023-02-28 15:01 UTC
Labels: triaging
