### ISSUE TITLE
playwright on Python3.9.2 or python 3.8.8 get No module named of "greenlet._greenlet" Error.

### ISSUE THREAD

**Issue by onebits** [microsoft/playwright-python#596] opened 2021-03-22 10:03 UTC
Windows 10 Pro
Python 3.9.2
SublimeText3 + Anaconda + virtualenv

`from playwright.sync_api import sync_playwright`

get error:

No module named "greenlet._greenlet"

But I installed greenlet.

When I change the python version to 3.7.9.  All done...

PS: The same error get with 3.8.8

**Comment by vitorbferna** [comment] 2021-03-29 22:36
I am having this same problem, how can I solve this?

**Comment by mxschmitt** [comment] 2021-03-30 04:22
> I am having this same problem, how can I solve this?
> 

Would be helpful if you could give us reproduce instructions, since we can't reproduce it yet.

And more input like which package manager etc.

Thanks!

**Comment by mxschmitt** [comment] 2021-04-01 18:07
@vitorbferna are you also using Windows + Anaconda?

**Comment by dgozman** [comment] 2021-04-15 18:34
Closing this issue since we cannot reproduce it. If you have any additional information that helps us reproduce this issue, please comment here and we'll reopen.

**Closed by dgozman** 2021-04-15 18:34 UTC
Labels: triaging

**Comment by why2lyj** [comment] 2022-11-26 13:46
@dgozman 

Meeting this issue with latest version: playwright 1.28.0

python version: 3.8.10

I used Win7 64 and Win10 64 with the same issue(It's frist time to install the playwright for both PC, BTW)

**I uninstall playwright 1.28.0 and install 1.27.1. the issue fixed.**

```shell
Traceback (most recent call last):
  File "main_check.py", line 11, in <module>
    from playwright.async_api import async_playwright, Dialog
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\playwright\async_api\__init__.py", line 25, in <module>
    import playwright.async_api._generated
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\playwright\async_api\_generated.py", line 25, in <module>
    from playwright._impl._accessibility import Accessibility as AccessibilityImpl
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\playwright\_impl\_accessibility.py", line 17, in <module>
    from playwright._impl._connection import Channel
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\playwright\_impl\_connection.py", line 23, in <module>
    from greenlet import greenlet
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\greenlet\__init__.py", line 29, in <module>
    from ._greenlet import _C_API # pylint:disable=no-name-in-module
ImportError: DLL load failed while importing _greenlet: No module 
```

**Comment by thirtyai** [comment] 2023-02-02 10:26
in same project, have 2 files(main.py , grab.py) , main.py can work, but grab.py not.  
in grab.py file ,add "import pandas as pd " to the top of file. the grab.py is working well.
why???

**Comment by ksyong168** [comment] 2023-02-04 20:23
Same here, using the simplest code from playwright documentation. I have remove python and reinstall again, try to fix this but no luck. I run playwright in 3 PC and 4 VPS. Just this VPS have this problem. FYI, I installed follow playwright documentation

Script as below:
from playwright.sync_api import sync_playwright

def run(playwright):
    chromium = playwright.chromium # or "firefox" or "webkit".
    browser = chromium.launch()
    page = browser.new_page()
    page.goto("http://example.com")
    # other actions...
    browser.close()

with sync_playwright() as playwright:
    run(playwright)


Output as below:

"C:\Program Files\Python311\python.exe" C:\APIKS\Playwright\test.py 
Traceback (most recent call last):
  File "C:\APIKS\Playwright\test.py", line 1, in <module>
    from playwright.sync_api import sync_playwright
  File "C:\Program Files\Python311\Lib\site-packages\playwright\sync_api\__init__.py", line 25, in <module>
    import playwright.sync_api._generated
  File "C:\Program Files\Python311\Lib\site-packages\playwright\sync_api\_generated.py", line 25, in <module>
    from playwright._impl._accessibility import Accessibility as AccessibilityImpl
  File "C:\Program Files\Python311\Lib\site-packages\playwright\_impl\_accessibility.py", line 17, in <module>
    from playwright._impl._connection import Channel
  File "C:\Program Files\Python311\Lib\site-packages\playwright\_impl\_connection.py", line 23, in <module>
    from greenlet import greenlet
  File "C:\Program Files\Python311\Lib\site-packages\greenlet\__init__.py", line 29, in <module>
    from ._greenlet import _C_API # pylint:disable=no-name-in-module
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: DLL load failed while importing _greenlet: The specified module could not be found.

Process finished with exit code 1

**Comment by N0Noorz** [comment] 2023-02-14 09:14
> Same here, using the simplest code from playwright documentation. I have remove python and reinstall again, try to fix this but no luck. I run playwright in 3 PC and 4 VPS. Just this VPS have this problem. FYI, I installed follow playwright documentation Playwright version 1.30.0
> 
> Script as below: from playwright.sync_api import sync_playwright
> 
> def run(playwright): chromium = playwright.chromium # or "firefox" or "webkit". browser = chromium.launch() page = browser.new_page() page.goto("http://example.com") # other actions... browser.close()
> 
> with sync_playwright() as playwright: run(playwright)
> 
> Output as below:
> 
> "C:\Program Files\Python311\python.exe" C:\APIKS\Playwright\test.py Traceback (most recent call last): File "C:\APIKS\Playwright\test.py", line 1, in from playwright.sync_api import sync_playwright File "C:\Program Files\Python311\Lib\site-packages\playwright\sync_api__init__.py", line 25, in import playwright.sync_api._generated File "C:\Program Files\Python311\Lib\site-packages\playwright\sync_api_generated.py", line 25, in from playwright._impl._accessibility import Accessibility as AccessibilityImpl File "C:\Program Files\Python311\Lib\site-packages\playwright_impl_accessibility.py", line 17, in from playwright._impl._connection import Channel File "C:\Program Files\Python311\Lib\site-packages\playwright_impl_connection.py", line 23, in from greenlet import greenlet File "C:\Program Files\Python311\Lib\site-packages\greenlet__init__.py", line 29, in from ._greenlet import _C_API # pylint:disable=no-name-in-module ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ImportError: DLL load failed while importing _greenlet: The specified module could not be found.
> 
> Process finished with exit code 1

try install vc-redistfirst.
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by ksyong168** [comment] 2023-02-14 18:20
Hi N0Noors,

Thx for your reply.

I already installed visual c++ redist on on my windows 10 and 11 pro pcs
(total 5). it's working now. But windows server 2012 R2 (total 5 VPS) and
server 2016 R2 (1 VPS) not working even after I installed visual c++ redist

Tested in Ubuntu linux, working fine without need to install anything.

Problem now with windows server 2012 R2 and 2016 R2.
