### ISSUE TITLE
can't install on Alpine3.12

### ISSUE THREAD

**Issue by etishka** [microsoft/playwright-python#234] opened 2020-10-13 21:43 UTC
```
# python -m playwright install
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/site-packages/playwright/__main__.py", line 17, in <module>
    main()
  File "/usr/local/lib/python3.8/site-packages/playwright/main.py", line 145, in main
    st = os.stat(driver_executable)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/site-packages/playwright/drivers/driver-linux'
```

**Comment by arjunattam** [comment] 2020-10-13 22:50
Thanks for reporting this! 

The driver executable was not download when `pip install playwright` was run. This is because the Python wheel does not support non-glibc based Linux distributions (including Alpine). [Relevant issue](https://github.com/pypa/manylinux/issues/37) and [this article](https://pythonspeed.com/articles/alpine-docker-python/). I'm seeing [this workaround](https://github.com/insightfulsystems/alpine-python/blob/master/3.6/Dockerfile#L28) in some public Dockerfiles based on Alpine, but it is probably not recommended.

We would have to rethink packaging to be able to support Alpine.

**Comment by kumaraditya303** [comment] 2020-12-07 10:29
Bump Is building browsers on alpine possible ?

**Comment by mxschmitt** [comment] 2020-12-07 11:09
Depends on the need, since not a lot of people are upvoting the feature, not much gets investigated into it. For WebKit and Firefox its not super easy, since there would be separate browser builds needed. For Chromium it could be possible when Chrome Canary gets used.

Do you want to use Playwright for Python with Alpine?

**Comment by kumaraditya303** [comment] 2020-12-07 12:54
@mxschmitt as much as  I have used alpine with python there are too many issues to deal with mostly because of musl and many workarounds are required so we should not be investigating it anymore & I don't want to use alpine, Ubuntu is just fine,  FYI I am on PR for playwright to install only selected browsers.

**Comment by mxschmitt** [comment] 2020-12-07 12:56
@kumaraditya303 I think the same way. (For the selected browsers, it's not an easy change, needs to be made upstream the change on the Playwright project and designed that it can be used with the other language providers too.)

**Comment by kumaraditya303** [comment] 2020-12-07 13:25
> @kumaraditya303 I think the same way. (For the selected browsers, it's not an easy change, needs to be made upstream the change on the Playwright project and designed that it can be used with the other language providers too.)

@mxschmitt I am doing it by setting PLAYWRIGHT_BROWSERS_LIST env var and then parsing it to download the browser if not present download all, this approach can be easily implemented as there isn't need for any language specific code. Any Suggestions ?

**Comment by aleksandr-kotlyar** [comment] 2021-01-19 19:28
> Bump Is building browsers on alpine possible ?

Hi, if the question was - is it possible to run ui-tests on chromium-alpine - so yes, it's possible. I did it on selenium. If the problem is with chromium webdriver - you can look at my PR https://github.com/SergeyPirogov/webdriver_manager/pull/97 for webdriver_manager where i solved the same issue.
I hope I didn't miss the topic and my answer will be helpful for someone :). I'm new in playwright project and just watching an activity here to see what i can do for the project.

**Comment by pavelfeldman** [comment] 2021-03-02 19:16
Alpine is currently out of scope for Playwright and the core team is not looking at it actively, hence closing.

**Closed by pavelfeldman** 2021-03-02 19:16 UTC
Labels: P3-collecting-feedback

**Comment by jtomek** [comment] 2022-07-28 14:57
Is Alpine still out of scope?

**Comment by gerzha** [comment] 2023-03-29 09:11
Any news about Alpine?
