### ISSUE TITLE
is pyinstaller supported

### ISSUE THREAD

**Issue by jinhang87** [microsoft/playwright-python#407] opened 2020-12-29 01:39 UTC
PS D:\python\demo_lib_playwright\dist> .\tester.exe
Traceback (most recent call last):
  File "test.py", line 37, in <module>
  File "lib\site-packages\playwright\_main.py", line 78, in __enter__
  File "lib\site-packages\playwright\_main.py", line 59, in greenlet_main
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "lib\site-packages\playwright\_connection.py", line 134, in run_as_sync
  File "lib\site-packages\playwright\_connection.py", line 139, in run
  File "lib\site-packages\playwright\_transport.py", line 39, in run
  File "asyncio\subprocess.py", line 236, in create_subprocess_exec
  File "asyncio\base_events.py", line 1630, in subprocess_exec
  File "asyncio\windows_events.py", line 385, in _make_subprocess_transport
  File "asyncio\base_subprocess.py", line 36, in __init__
  File "asyncio\windows_events.py", line 881, in _start
  File "asyncio\windows_utils.py", line 153, in __init__
  File "subprocess.py", line 854, in __init__
  File "subprocess.py", line 1307, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
[40328] Failed to execute script test

**Comment by JoelEinbinder** [comment] 2021-01-05 22:48
It doesn't look like its supported 🙃 

@pavelfeldman You were talking about people packing up all the browsers into a single executable right?

**Comment by mxschmitt** [comment] 2021-01-05 22:51
Its a duplicate of #342 and should be fixed in #345 but seems like it isn't.

**Comment by zhanghaofei** [comment] 2021-01-08 08:17
Encountering the same problem

**Comment by zhanghaofei** [comment] 2021-01-12 01:07
@mxschmitt I've solved it. I'm missing --add-data option

**Comment by niemtin6789** [comment] 2021-01-14 09:32
@zhanghaofei  how do you deploy to customer. i get error "failed to launch chromium because executable doesn't exists".
thanks you

**Comment by pavelfeldman** [comment] 2021-01-14 22:53
Closing as per --add-data comment above.

**Closed by pavelfeldman** 2021-01-14 22:53 UTC
Labels: triaging
