### ISSUE TITLE
[Feature] allow client certificate selection and settings from Python

### ISSUE THREAD

**Issue by mesa123123** [microsoft/playwright-python#485] opened 2021-02-06 03:54 UTC
https://github.com/microsoft/playwright/issues/1799

Basically theres a workaround you can use in JS that works with the agent options settings in the node request library that allows you to dynamically inject ca bundles straight to the context.route.EventHandler

I've tried to find out if this can work using urllib request but I can't seem to find a plausible way to do it

Could you guys please advise?

Heres the work around from the JS version

```
const fs = require('fs');
const request = require('request');
const browser = await chromium.launch();
const ctx = await browser.newContext();
await ctx.route('**/*', (route, req) => {
    const options = {
      uri: req.url(),
      method: req.method(),
      headers: req.headers(),
      body: req.postDataBuffer(),
      timeout: 10000,
      followRedirect: false,
      agentOptions: {
        ca: fs.readFileSync('./certs/ca.pem'),
        pfx: fs.readFileSync('./certs/user_cert.p12'),
        passphrase: fs.readFileSync('./certs/user_cert.p12.pwd'),
      },
    };
    let firstTry = true;
    const handler = function handler(err, resp, data) {
      if (err) {
        /* Strange random connection error on first request, do one re-try */
        if (firstTry) {
          firstTry = false;
          return request(options, handler);
        }
        console.error(`Unable to call ${options.uri}`, err.code, err);
        return route.abort();
      } else {
        return route.fulfill({
          status: resp.statusCode,
          headers: resp.headers,
          body: data,
        });
      }
    };
    return request(options, handler);
  });
```

**Comment by mxschmitt** [comment] 2021-04-20 14:25
Closing as duplicate of https://github.com/microsoft/playwright/issues/1799

(The features are tracked upstream and then get implemented in the specific languages)

**Closed by mxschmitt** 2021-04-20 14:25 UTC
Labels: P3-collecting-feedback

**Comment by medina325** [comment] 2022-08-14 20:41
Except it's not a duplicate, he's asking for the implementation in Python of the code. Which I also seem to have no idea on how to do it :)

**Comment by dchronos** [comment] 2023-06-20 02:22
yeap, same problem here...
