### ISSUE TITLE
Firefox browser won`t start

### ISSUE THREAD

**Issue by Ank2503** [microsoft/playwright-python#509] opened 2021-02-15 10:27 UTC
Hello, i'm starting simple test code, and i'm keep getting the error, that firefox process "pid" not found.

```js
const { firefox } = require('playwright');

(async () => {
    const browser = await firefox.launch({
        headless:false,
        slowMo: 1000
    });
  const page = await browser.newPage();
  await page.goto('https://danube-webshop.herokuapp.com/');

  await page.waitForTimeout(3000);

  await page.focus('input');

  await browser.close();
})()
```

The result is:
```
Debugger attached.
ERROR: The process "12756" not found.
(node:8816) UnhandledPromiseRejectionWarning: browserType.launch: Protocol error (Browser.enable): Browser closed.
==================== Browser output: ====================
<launching> C:\Users\a.kurochkin\AppData\Local\ms-playwright\firefox-1225\firefox\firefox.exe -no-remote -wait-for-browser -foreground -profile C:\Users\A54DE~1.KUR\AppData\Local\Temp\playwright_firefoxdev_profile-pXcxKx -juggler-pipe -silent
<launched> pid=12756
[out]
[out] Juggler listening to the pipe
[out] console.warn: SearchSettings: "get: No settings file exists, new profile?" (new Error("", "(unknown module)"))
[err] JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
[err] JavaScript error: resource://activity-stream/lib/ASRouterNewTabHook.jsm, line 61: TypeError: this._router is null
[err]
[err] ###!!! [Child][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost
[err]
=========================== logs ===========================
<launching> C:\Users\a.kurochkin\AppData\Local\ms-playwright\firefox-1225\firefox\firefox.exe -no-remote -wait-for-browser -foreground -profile C:\Users\A54DE~1.KUR\AppData\Local\Temp\playwright_firefoxdev_profile-pXcxKx -juggler-pipe -silent
<launched> pid=12756
[out]
[out] Juggler listening to the pipe
[out] console.warn: SearchSettings: "get: No settings file exists, new profile?" (new Error("", "(unknown module)"))
[err] JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
[err] JavaScript error: resource://activity-stream/lib/ASRouterNewTabHook.jsm, line 61: TypeError: this._router is null
[err]
[err] ###!!! [Child][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost
[err]
============================================================
```

**Comment by mxschmitt** [comment] 2021-02-15 10:30
Seems to be a duplicate of https://github.com/microsoft/playwright/issues/5355 thanks for reporting!

**Comment by mxschmitt** [comment] 2021-02-15 10:46
Seems to be a duplicate of https://github.com/microsoft/playwright/issues/5355 thanks for reporting!

Which version of Windows are you using?

**Comment by Ank2503** [comment] 2021-02-15 10:55
@mxschmitt  Windows 10 Enterprise, 1909

**Comment by Ank2503** [comment] 2021-02-15 10:56
downgraded to playwright 1.7.0, working for now.

**Comment by pavelfeldman** [comment] 2021-03-01 23:59
Closing as the upstream issue was resolved.

**Closed by pavelfeldman** 2021-03-01 23:59 UTC

**Comment by EtshD1** [comment] 2021-04-07 12:06
Hello I had the exact same error and I was able to fix it by installing some libraries. [Here](https://stackoverflow.com/questions/66984974/firefox-browser-does-not-start-in-playwright/66985671#66985671) is the issue I handled on stackoverflow.

**Comment by kingsley967** [comment] 2022-02-22 07:53
hihi Anyone facing this type of error ?
Tested good in local, but failed to open FireFox during IIS...

Exception: 
System.TimeoutException: Timeout 30000ms exceeded.
=========================== logs ===========================
<launching> C:\Windows\system32\config\systemprofile\AppData\Local\ms-playwright\firefox-1304\firefox\firefox.exe -no-remote -wait-for-browser -foreground -profile C:\Windows\TEMP\playwright_firefoxdev_profile-nGhAlE -juggler-pipe -silent
<launched> pid=25444
[pid=25444][err] Error: Access was denied while trying to open files in your profile directory.
[pid=25444][err] JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
[pid=25444][err] JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
[pid=25444][err] JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
[pid=25444][err] JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
[pid=25444][out] Crash Annotation GraphicsCriticalError: |[G0][GFX1-]: shader-cache: Shader disk cache is not supported (t=2.2087) [GFX1-]: shader-cache: Shader disk cache is not supported
[pid=25444][err] [2022-02-22T07:51:47Z ERROR webrender_bindings::program_cache] shader-cache: Shader disk cache is not supported
[pid=25444][out] Crash Annotation GraphicsCriticalError: |[G0][GFX1-]: shader-cache: Shader disk cache is not supported (t=2.2087) |[G1][GFX1-]: RcANGLE(no compositor window) (t=2.2087) [GFX1-]: RcANGLE(no compositor window)
[pid=25444][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: Failed to connect WebRenderBridgeChild. (t=4.64253) [GFX1-]: Failed to connect WebRenderBridgeChild.
[pid=25444][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: Failed to connect WebRenderBridgeChild. (t=4.64253) |[1][GFX1-]: Fallback WR to SW-WR + D3D11 (t=4.80253) [GFX1-]: Fallback WR to SW-WR + D3D11
[pid=25444][out] Crash Annotation GraphicsCriticalError: |[G0][GFX1-]: shader-cache: Shader disk cache is not supported (t=2.2087) |[G1][GFX1-]: RcANGLE(no compositor window) (t=2.2087) |[G2][GFX1-]: [D3D11] create swap chain failed: 0x887a0022, 0 (t=2.3687) [GFX1-]: [D3D11] create swap chain failed: 0x887a0022, 0
[pid=25444][out] Crash Annotation GraphicsCriticalError: |[G0][GFX1-]: shader-cache: Shader disk cache is not supported (t=2.2087) |[G1][GFX1-]: RcANGLE(no compositor window) (t=2.2087) |[G2][GFX1-]: [D3D11] create swap chain failed: 0x887a0022, 0 (t=2.3687) |[G3][GFX1-]: Failed to initialize CompositorD3D11 for SWGL: FEATURE_FAILURE_D3D11_SWAP_CHAIN (t=2.3687) [GFX1-]: Failed to initialize CompositorD3D11 for SWGL: FEATURE_FAILURE_D3D11_SWAP_CHAIN
[pid=25444][err] JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
============================================================
   at Microsoft.Playwright.Transport.Connection.SendMessageToServerAsync[T](String guid, String method, Object args)
   at Microsoft.Playwright.Core.BrowserType.LaunchAsync(BrowserTypeLaunchOptions options)
   at SC.BankTransferMimic.Engine.Banks.BankBase.Initialize(String browser) in C:\SigmaCoders\SC.BankTransferMimic\SC.BankTransferMimic.Engine\Banks\BankBase.cs:line 43
   at SC.BankTransferMimic.Engine.Banks.Malaysia.CIMBBankFactory.NewBankAsync() in C:\SigmaCoders\SC.BankTransferMimic\SC.BankTransferMimic.Engine\Banks\Malaysia\CIMBBankFactory.cs:line 16
   at SC.BankTransferMimic.Engine.Banks.BankProvider.NewSessionAsync(String bankId, String merchantId) in C:\SigmaCoders\SC.BankTransferMimic\SC.BankTransferMimic.Engine\Banks\BankProvider.cs:line 52
   at Program.<>c.<<<Main>$>b__0_1>d.MoveNext() in C:\SigmaCoders\SC.BankTransferMimic\SC.BankTransferMimic.Engine\Program.cs:line 60
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.ExecuteTaskResult[T](Task`1 task, HttpContext httpContext)
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass46_3.<<HandleRequestBodyAndCompileRequestDelegate>b__2>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

**Comment by mxschmitt** [comment] 2022-02-22 09:02
This looks like you are using dotnet but that's the Python repository. Please create separate issues.
