### ISSUE TITLE
How to maximize the browser window

### ISSUE THREAD

**Issue by jamesz2011** [microsoft/playwright-python#384] opened 2020-12-18 08:47 UTC
How to maximize the browser window？

**Comment by mxschmitt** [comment] 2020-12-18 10:28
Sounds like this feature request, would be great if you could upvote it there so it can prioritised in the upstream repository: https://github.com/microsoft/playwright/issues/4046

**Comment by aslushnikov** [comment] 2020-12-18 23:56
closing as dupe of microsoft/playwright#4046

**Closed by aslushnikov** 2020-12-18 23:56 UTC
