### ISSUE TITLE
[Question]: The mouse cannot slide the slider on the webpage when using the automatic code generation function, 

### ISSUE THREAD

**Issue by marshzhao** [microsoft/playwright-python#862] opened 2021-08-22 04:53 UTC
### Your question

I want to use playwright to drag the slider in the webpage, and use the playwright automatic code generation function to get the required code. But after running the "python -m playwright codegen" command in the terminal, the code for clicking links, opening pages, etc. can be generated normally, but when the code recording function is turned on, you cannot drag the slider on the webpage.
[Can slide](https://github.com/marshzhao/marshzhao/blob/main/WechatIMG3146.png)
[Can not slide](https://github.com/marshzhao/marshzhao/blob/main/WechatIMG3145.png)

eg:"https://jobs.51job.com/beijing/124662690.html?s=sou_sou_soulb&t=0_0"，this is a page I want to use playwright to drag the slider.Refresh this page several times quickly, and the slider verification interface will appear. When the automatic code generation function is used, the slider of this page cannot be dragged by the mouse. 

How to solve this problem, thank you for attention.

### Playwright version

1.12.1

### Operating system

MacOS

### What browsers are you seeing the problem on?

Chromium, Firefox, WebKit

**Comment by mxschmitt** [comment] 2021-08-22 07:35
Sounds like a duplicate of https://github.com/microsoft/playwright/issues/8022. Thank you for reporting the bug!

**Closed** 2021-08-22 13:18 UTC
