### ISSUE TITLE
how  could i   remove  the disable,  let  me could  click the submit button.

### ISSUE THREAD

**Issue by chenhunhun** [microsoft/playwright-python#1444] opened 2022-07-21 11:11 UTC
### Your question

the button item is like  this.
<button type="submit" class="" disabled=""><span>login</span></button>

the button is disabled, i find on the web,but  could not find  the result.
how  could i   remove  the disable,  let  me could  click the submit button.

now i use the python  .

**Comment by rwoll** [comment] 2022-07-21 18:20
dupe of https://github.com/microsoft/playwright-python/issues/1446

**Closed by rwoll** 2022-07-21 18:20 UTC
