### ISSUE TITLE
Browser Freezes

### ISSUE THREAD

**Issue by CheemaOTB** [microsoft/playwright-python#662] opened 2021-05-05 17:19 UTC
After a while, the browser just freezes (using firefox). Any reason why?

**Comment by mxschmitt** [comment] 2021-05-05 18:43
Is it reproducible? Are you re-using the same context over and over again? Hard to debug without any information, thanks!

**Comment by CheemaOTB** [comment] 2021-05-05 23:21
> Is it reproducible? Are you re-using the same context over and over again? Hard to debug without any information, thanks!

At the end of the script, I have it set up so there can be some human input but after a while, the browser becomes non-responsive for example you cant refresh the page or open a new tab. I have tried adding a time.sleep at the end and input to make the script stay open but neither works and the browser ends up freezing. Let me know if you need any more information, thanks.

**Comment by mxschmitt** [comment] 2021-05-06 08:59
How long do you keep the script running? Do you interact with the page over and over again?

If you e.g. navigate to a few sites without recreating a new context and there is a lot of interaction on the page with resources, then it seems for me related/duplicate of https://github.com/microsoft/playwright/issues/6319

**Comment by CheemaOTB** [comment] 2021-05-06 22:57
> How long do you keep the script running? Do you interact with the page over and over again?
> 
> If you e.g. navigate to a few sites without recreating a new context and there is a lot of interaction on the page with resources, then it seems for me related/duplicate of [microsoft/playwright#6319](https://github.com/microsoft/playwright/issues/6319)
> 
> A small script which demonstrates the issue would be super helpful, thanks!

At the end of the script, there's only one interaction but the script stays running for 10-15 mins after just sitting on the website with no interactions. Could it be due to the webpage being dynamic?

**Comment by smartahsan** [comment] 2021-05-08 05:14
I am also experiencing the exact same issue where I keep the process going and the script aswell, but for some reason half of the website elements disappear and I am unable to reload or even open a new tab in the nightly window after a while. The browser freezes entirely and sometimes it even gets this weird loading animation where a load wheel just keeps spinning endlessly.

**Comment by aslushnikov** [comment] 2021-05-10 15:46
Everybody: Any chance you can a share a script with us and your host configuration? We can try reproducing this in docker where we'll allocate exactly the same amount of RAM and CPUs that you have.

**Comment by mxschmitt** [comment] 2021-05-17 08:52
Closed since it seemed stale, please reopen / create a new issue with a reproducible script to dig more deeper into it.

**Closed by mxschmitt** 2021-05-17 08:52 UTC
Labels: triaging
