### ISSUE TITLE
Playwright 1.12.1 can't get installed under Alpine Linux via PIP

### ISSUE THREAD

**Issue by budsee** [microsoft/playwright-python#792] opened 2021-07-05 16:15 UTC
Context:

Playwright Version: 1.12.1
Operating System: Ubuntu 20.04 container in Apple M1 Chip Machine
Python 3.9.5
Browser: All
Extra: [any specific details about your environment]

I can't install playwright 1.12.1 using pip when I am in container, i.e. ubuntu or alpine, etc The latest version I would get is

[ 9/12] RUN pip install playwright==1.12.1:
#12 1.309 ERROR: Could not find a version that satisfies the requirement playwright==1.12.1 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.16, 0.0.17, 0.0.18, 0.7.0, 0.7.1, 0.8.0, 0.140.0, 0.142.0, 0.142.1, 0.142.2, 0.142.3, 0.150.0, 0.151.0, 0.151.1, 0.152.0, 0.162.0, 0.162.1, 0.162.2)
#12 1.309 ERROR: No matching distribution found for playwright==1.12.1

I think 0.162.2 is the last version that has a general *.tar.gz in pip. The later version are OS specific like linux, macOS, Win. I suspect it's due to me running a Linux container in Apple M1 chip machine which is why it said it cannot find the latest version. How can I install 1.12.1 in the container?

**Comment by DSsdet** [comment] 2021-07-07 10:17
Hi Amost,
the same issue as above

Context:
we are trying to run this with dockercontainer (ppodgorsek/docker-robot-framework)

Playwright Version: 1.12.1
Operating System: Docker container on alpine3.12
Python 3.9.0
Browser: All

ERROR: Could not find a version that satisfies the requirement playwright==1.12.1 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.16, 0.0.17, 0.0.18, 0.7.0, 0.7.1, 0.8.0, 0.140.0, 0.142.0, 0.142.1, 0.142.2, 0.142.3, 0.150.0, 0.151.0, 0.151.1, 0.152.0, 0.162.0, 0.162.1, 0.162.2)
ERROR: No matching distribution found for playwright==1.12.1



Note:
If I do this locally on Ubuntu 21.04 python 3.9.5 it all works fine.

**Comment by mxschmitt** [comment] 2021-07-07 12:51
Hi, its intended that it does not work in Alpine, Playwright itself is only [officially compatible](https://playwright.dev/docs/intro#linux) with Ubuntu 18.04/20.04 so far since the browsers need to get compiled for the other architectures too which leads otherwise in missing dependencies (dynamically linked).

I tried to reproduce it with the [official Docker image](https://playwright.dev/docs/docker) but this was working for me. Also `ubuntu:focal` seems to be working.

Since Alpine is not manylinux compliant, it does not install Playwright via PIP. The old versions which you are getting are quite outdated and not supported anymore.

**Comment by YusukeIwaki** [comment] 2021-07-08 04:56
Hi, I tried to execute automation script using playwright-python on `python:3.9-alpine` Docker image.
We can execute the script on alpine with WebSocketTransport communicating with isolated Playwright server (like the fig below).
![structure](https://user-images.githubusercontent.com/11763113/124863646-713f8500-dff2-11eb-8bbe-48fdd11f6e4c.png)

https://github.com/YusukeIwaki/playwright-python-remote

Playwright package contains Playwright driver and browsers, and they requires many dependencies. I guess it is the main reason to prevent installation on alpine. But if PlaywrightServer is prepared and Playwright protocol is transported via WebSocket, playwright-python does not require so many dependencies and it works just as a Playwright client on alpine.

I know `playwright run-server` is hidden command and WebSocketTransport is in private package, and totally not supported offically. Just sharing my trial :)

**Comment by mxschmitt** [comment] 2021-07-08 18:13
Hi, this API is considered as internal and can/will change over time. For your proposal, we already got a tracking issue upstream: https://github.com/microsoft/playwright/issues/4687.

Since supporting Alpine in general with Playwright (except via connecting some sort of server - see the upstream issue) is out of scope of Playwright, I'm closing this issue.

Saw that also M1 is mentioned in the original comment, we are tracking support for M1 here: https://github.com/microsoft/playwright-python/issues/796

**Closed by mxschmitt** 2021-07-08 18:13 UTC
Labels: triaging

**Comment by YusukeIwaki** [comment] 2021-07-08 21:43
@mxschmitt Thank you, I will watch the issue.

> For your proposal, we already got a tracking issue upstream: microsoft/playwright#4687.
