### ISSUE TITLE
"RuntimeError: This event loop is already running" When attempting REPL example

### ISSUE THREAD

**Issue by JacobCallahan** [microsoft/playwright-python#178] opened 2020-08-25 19:59 UTC
Each time I attempt the REPl example, I get the traceback below. Sync context-manager example worked though.
`playwright==0.8.0`
REPL Example: https://github.com/microsoft/playwright-python#repl-support-without-context-managers

IPython session
```python
 jake  (e) venvplaywright  ~  ipython
/home/jake/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py:935: UserWarning: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
  warn("Attempting to work in a virtualenv. If you encounter problems, please "
Python 3.8.3 (default, May 29 2020, 00:00:00) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from playwright import sync_playwright                                                                                                                                                

In [2]: playwright = sync_playwright().start()                                                                                                                                                

Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/home/jake/.local/lib/python3.8/site-packages/IPython/__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/jake/.local/lib/python3.8/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/home/jake/.local/lib/python3.8/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/home/jake/.local/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 558, in mainloop
    self.interact()
  File "/home/jake/.local/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 541, in interact
    code = self.prompt_for_code()
  File "/home/jake/.local/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 467, in prompt_for_code
    text = self.pt_app.prompt(
  File "/home/jake/.local/lib/python3.8/site-packages/prompt_toolkit/shortcuts/prompt.py", line 994, in prompt
    return self.app.run(set_exception_handler=set_exception_handler)
  File "/home/jake/.local/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 811, in run
    return loop.run_until_complete(
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 592, in run_until_complete
    self._check_running()
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 552, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running

If you suspect this is an IPython 7.13.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

sys:1: RuntimeWarning: coroutine 'Application.run_async' was never awaited
```

**Comment by mxschmitt** [comment] 2020-08-25 20:20
for iPython / Jupiter notebooks it seems like the current workaround would be to use that before you run your shell:

```
import nest_asyncio
nest_asyncio.apply()
```

Out of curiosity to understand more the user case. You are trying out Playwright in a REPL or are you using it only with with the REPL in the end?

**Comment by JacobCallahan** [comment] 2020-08-25 21:13
@mxschmitt thanks for the quick response!
nest_asyncio isn't a standard package or one installed as a requirement for playwright. As such, I'm guessing most users wouldn't have it installed. However, that did solve the problem:
```python
In [1]: import nest_asyncio                                                                                                                                   

In [2]: nest_asyncio.apply()                                                                                                                                  

In [3]: from playwright import sync_playwright                                                                                                                

In [4]: playwright = sync_playwright().start()                                                                                                                

In [5]:     
```
My use-case within IPython is largely API exploration and interactive process development before writing a script or integration with an application. 

Additional note, your example works perfectly in the base python REPL.

**Comment by bubthegreat** [comment] 2020-10-02 03:17
@mxschmitt - FYI, the nested async doesn't work for jupyter notebooks for at least the sync REPL example:
```
import nest_asyncio
nest_asyncio.apply()
p = async_playwright()
from playwright import sync_playwright
playwright = sync_playwright().start()
playwright = sync_playwright().start()
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-3-85d403adca24> in <module>
----> 1 playwright = sync_playwright().start()

c:\users\bubth\development\playwright\venv\lib\site-packages\playwright\__init__.py in sync_playwright()
     32 
     33 def sync_playwright() -> SyncPlaywrightContextManager:
---> 34     return SyncPlaywrightContextManager()
     35 
     36 

c:\users\bubth\development\playwright\venv\lib\site-packages\playwright\main.py in __init__(self)
     81 class SyncPlaywrightContextManager:
     82     def __init__(self) -> None:
---> 83         self._connection = run_driver()
     84         self._playwright: SyncPlaywright
     85 

c:\users\bubth\development\playwright\venv\lib\site-packages\playwright\main.py in run_driver()
     76     # if loop.is_running():
     77     #     raise Error("Can only run one Playwright at a time.")
---> 78     return loop.run_until_complete(run_driver_async())
     79 
     80 

c:\users\bubth\development\playwright\venv\lib\site-packages\nest_asyncio.py in run_until_complete(self, future)
     93                 raise RuntimeError(
     94                     'Event loop stopped before Future completed.')
---> 95             return f.result()
     96         finally:
     97             events._set_running_loop(old_running_loop)

C:\Program Files\Python37\lib\asyncio\futures.py in result(self)
    176         self.__log_traceback = False
    177         if self._exception is not None:
--> 178             raise self._exception
    179         return self._result
    180 

C:\Program Files\Python37\lib\asyncio\tasks.py in __step(***failed resolving arguments***)
    221                 # We use the `send` method directly, because coroutines
    222                 # don't have `__iter__` and `__next__` methods.
--> 223                 result = coro.send(None)
    224             else:
    225                 result = coro.throw(exc)

c:\users\bubth\development\playwright\venv\lib\site-packages\playwright\main.py in run_driver_async()
     62         stdout=asyncio.subprocess.PIPE,
     63         stderr=_get_stderr_fileno(),
---> 64         limit=32768,
     65     )
     66     assert proc.stdout

C:\Program Files\Python37\lib\asyncio\subprocess.py in create_subprocess_exec(program, stdin, stdout, stderr, loop, limit, *args, **kwds)
    215         program, *args,
    216         stdin=stdin, stdout=stdout,
--> 217         stderr=stderr, **kwds)
    218     return Process(transport, protocol, loop)

C:\Program Files\Python37\lib\asyncio\base_events.py in subprocess_exec(self, protocol_factory, program, stdin, stdout, stderr, universal_newlines, shell, bufsize, *args, **kwargs)
   1531         transport = await self._make_subprocess_transport(
   1532             protocol, popen_args, False, stdin, stdout, stderr,
-> 1533             bufsize, **kwargs)
   1534         if self._debug and debug_log is not None:
   1535             logger.info('%s: %r', debug_log, transport)

C:\Program Files\Python37\lib\asyncio\base_events.py in _make_subprocess_transport(self, protocol, args, shell, stdin, stdout, stderr, bufsize, extra, **kwargs)
    461                                          extra=None, **kwargs):
    462         """Create subprocess transport."""
--> 463         raise NotImplementedError
    464 
    465     def _write_to_self(self):

NotImplementedError: 
```

**Comment by pavelfeldman** [comment] 2020-10-06 03:14
@bubthegreat: This looks like a `SelectorEventLoop`'s limitation on Python 3.7 on Windows. Starting with 3.8, a more complete implementation of the loop is used on Windows and it should support running subprocesses. See the [platform support](https://docs.python.org/3/library/asyncio-platforms.html) section for more details.

**Comment by bubthegreat** [comment] 2020-10-06 04:02
I assume upgrading to 3.9 would improve this, still saw issues, and downgraded to 3.8.3 - still having issues with sync_playwright:

```
import nest_asyncio
nest_asyncio.apply()
from playwright import sync_playwright                                                                                                                
playwright = sync_playwright().start()    
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
<ipython-input-2-dfa883f2869c> in <module>
      1 from playwright import sync_playwright
----> 2 playwright = sync_playwright().start()

c:\users\bubth\development\playwright-test\venv\lib\site-packages\playwright\__init__.py in sync_playwright()
     32 
     33 def sync_playwright() -> SyncPlaywrightContextManager:
---> 34     return SyncPlaywrightContextManager()
     35 
     36 

c:\users\bubth\development\playwright-test\venv\lib\site-packages\playwright\main.py in __init__(self)
     86 class SyncPlaywrightContextManager:
     87     def __init__(self) -> None:
---> 88         self._connection = run_driver()
     89         self._playwright: SyncPlaywright
     90 

c:\users\bubth\development\playwright-test\venv\lib\site-packages\playwright\main.py in run_driver()
     80     loop = asyncio.get_event_loop()
     81     if loop.is_running():
---> 82         raise Error("Can only run one Playwright at a time.")
     83     return loop.run_until_complete(run_driver_async())
     84 

Error: Can only run one Playwright at a time.
```

**Comment by ddelange** [comment] 2020-10-06 09:20
Currently, playwright disallows attaching to a running loop: https://github.com/microsoft/playwright-python/blob/d98d38b89b4864966218b1333c9399fc35487725/playwright/main.py#L79-L83

This will fail in IPython and Jupyter.

For IPython, I would suggest exlpoiting py37's [`asyncio.get_running_loop`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.get_running_loop) and removing the `is_running` check.
```py
import asyncio

def get_loop():
    try:
        return asyncio.get_running_loop()
    except RuntimeError:
        return asyncio.get_event_loop()

get_loop().run_until_complete(asyncio.sleep(1))
```

This example will run in latest IPython, but will break on Jupyter environments that use `tornado>=5` under the hood.

So for Jupyter, additionally a `pip install 'notebook<6' 'tornado<5'` should fix loop issues introduced in `tornado>=5`. ref https://github.com/jupyter/notebook/issues/3397#issuecomment-675566100

**Comment by pavelfeldman** [comment] 2020-10-06 14:35
My understanding is that resolving this requires cooperation between the embedder that controls the loop and sync Playwright that also wants to dispatch its messages forever. And I don't think such cooperation is the right way to go. Sync API is designed as self-contained, assumes it controls execution. Is there a way to use async in Jupyter?

**Comment by bubthegreat** [comment] 2020-10-06 14:47
If I get time tonight ill play around with it- I dont see any reason for it
not to run in the existing loop - or are there architectural challenges
with it sharing the loop?

**Comment by ddelange** [comment] 2020-10-08 07:51
Executing a cell in Jupyter will actually require a lock on the main loop from ipykernel, so you could schedule execution of a Future in one cell (which will start execution once that cell has finished), and get the result in the next cell. Doing it all in one cell is certainly not trivial without nested loops.

![image](https://user-images.githubusercontent.com/14880945/95430186-afb4f000-094b-11eb-816e-6851f2dfb907.png)

**Comment by tals** [comment] 2020-12-24 15:44
> for iPython / Jupiter notebooks it seems like the current workaround would be to use that before you run your shell:
> 
> ```
> import nest_asyncio
> nest_asyncio.apply()
> ```
> 
> Out of curiosity to understand more the user case. You are trying out Playwright in a REPL or are you using it only with with the REPL in the end?

Was just bitten by this.

It is very convenient to use Jupyter for explorative programming, especially when the thing you're working with is heavy (like a browser in a particular state).
For my use case, I wanted to spin up a few browser instances and use them to test out a complicated feature that involves webrtc etc.

Also ran into this cute tutorial demonstrating why this is nice (he's using Selenium): https://medium.com/shakuro/adopting-ipython-jupyter-for-selenium-testing-d02309dd00b8

Hope this helps!

**Comment by tals** [comment] 2020-12-24 16:26
Found a trick as a workaround for getting Playwright working within Jupyter.

It leverages an awesome python library called [RPyc](https://github.com/tomerfiliba-org/rpyc) to run Playwright outside of the kernel while keeping the API the same.

```python
!pip install rpyc

import rpyc
import subprocess
subprocess.Popen('rpyc_classic.py -m forking'.split())  # start RPyc worker

conn = rpyc.classic.connect("localhost")
rplaywright = conn.modules['playwright']  

# rplaywright has the same API as playwright
pr = rplaywright.sync_playwright().start()
browser = pr.chromium.launch()
page = browser.newPage()
page.goto('http://whatsmyuseragent.org/')
page.screenshot(path='example.png')
browser.close()
```

**Comment by wohenniubi** [comment] 2021-01-02 04:13
> Found a workaround for getting Playwright working within Jupyter.
> 
> It leverages an awesome python library called [RPyc](https://github.com/tomerfiliba-org/rpyc) to run Playwright outside of the kernel while keeping the API the same.
> 
> ```python
> !pip install rpyc
> 
> import rpyc
> import subprocess
> subprocess.Popen('rpyc_classic.py -m forking'.split())  # start RPyc worker
> 
> conn = rpyc.classic.connect('localhost')
> rplaywright = conn.modules['playwright']  
> 
> # rplaywright has the same API as playwright
> pr = rplaywright.sync_playwright().start()
> browser = pr.chromium.launch()
> page = browser.newPage()
> page.goto('http://whatsmyuseragent.org/')
> page.screenshot(path='example.png')
> browser.close()
> ```
> 
> ```python
> # Grab screen
> from PIL import Image
> from io import BytesIO
> 
> browser = pr.chromium.launch()
> 
> page = browser.newPage()
> page.goto('http://localhost:4000/v/tf3nhh')
> img=page.screenshot(path='example.png')
> Image.open(BytesIO(img))
> ```
> 
> ![image](https://user-images.githubusercontent.com/761863/103101816-0617fd80-4622-11eb-8632-fa2ecd777d1d.png)

Hi tals, I follow the wolkaround that you mentioned, however, seems it can't help in win10. The error info shows "OSError: [WinError 193] %1 is not a valid Win32 application"

The complete error is as follows. Thanks for any further info.

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-2-1a79c22278a7> in <module>
      9 import rpyc
     10 import subprocess
---> 11 subprocess.Popen('rpyc_classic.py -m forking'.split())  # start RPyc worker
     12 
     13 conn = rpyc.classic.connect('localhost')

c:\program files\python38\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
    852                             encoding=encoding, errors=errors)
    853 
--> 854             self._execute_child(args, executable, preexec_fn, close_fds,
    855                                 pass_fds, cwd, env,
    856                                 startupinfo, creationflags, shell,

c:\program files\python38\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
   1305             # Start the process
   1306             try:
-> 1307                 hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
   1308                                          # no special security
   1309                                          None, None,

OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by tals** [comment] 2021-01-02 11:52
@wohenniubi sorry don't have a windows machine to test this out, but try figuring out how to run the rpyc_classic.py program on command line first

**Comment by wohenniubi** [comment] 2021-01-04 00:57
@tals Thanks for the response. After several trials without success, I might switch back to use selenium by now.
Anyway, I'll keep on watching this jupyter issue and this promising tool, playwright.

> @wohenniubi sorry don't have a windows machine to test this out, but try figuring out how to run the rpyc_classic.py program on command line first

**Comment by mxschmitt** [comment] 2021-04-24 09:43
Closed for now as part of the triage. Please reopen if it's still persistent.

**Closed by mxschmitt** 2021-04-24 09:43 UTC
Labels: P3-collecting-feedback

**Comment by tals** [comment] 2021-04-25 19:20
@mxschmitt not sure why its closed - this problem still exists. You can reproduce this on the latest versions of jupyter+playwright

**Comment by ddelange** [comment] 2021-04-25 19:44
The bug is upstream: https://github.com/ipython/ipykernel/issues/548

And there is a workaround: https://github.com/microsoft/playwright-python/issues/178#issuecomment-680249269

Maybe could warn the jupyter user with a verbose re-raising try-except?

**Comment by tals** [comment] 2021-04-25 20:58
@ddelange the proposed workaround sadly doesn't work on jupyter: https://github.com/microsoft/playwright-python/issues/178#issuecomment-702504459

The only thing I could do to get it working was running it outside of the process with RPyc

**Comment by bubthegreat** [comment] 2022-03-08 21:31
It's been almost two years and this still isn't fixed that I can find - playwright is explicitly stopping me from using nested loops: 
```
import nest_asyncio
nest_asyncio.apply()
​
from playwright.sync_api import sync_playwright
playwright = sync_playwright().start()
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
Input In [3], in <cell line: 2>()
      1 from playwright.sync_api import sync_playwright
----> 2 playwright = sync_playwright().start()

File c:\users\bubth\development\soc2\venv\lib\site-packages\playwright\sync_api\_context_manager.py:76, in PlaywrightContextManager.start(self)
     75 def start(self) -> SyncPlaywright:
---> 76     return self.__enter__()

File c:\users\bubth\development\soc2\venv\lib\site-packages\playwright\sync_api\_context_manager.py:42, in PlaywrightContextManager.__enter__(self)
     40             own_loop = loop
     41         if loop.is_running():
---> 42             raise Error(
     43                 """It looks like you are using Playwright Sync API inside the asyncio loop.
     44 Please use the Async API instead."""
     45             )
     47         def greenlet_main() -> None:
     48             loop.run_until_complete(self._connection.run_as_sync())

Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
```
The workarounds don't work for those of us using windows, and they don't appear to work in WSL either - is there a reason we can't get more information on why this is still closed two years later with no traction and no functional workarounds for presumably a fairly normal use case of using a jupyter notebook for exploratory programming?

It seems hard to believe that we just assume everyone will use raw iPython for everything so I'm confused by the reluctance to actually fix this.

**Comment by hkfsc** [comment] 2022-06-29 09:19
@bubthegreat Rpyc will only works if we will not call any playwright sub-modules directly, https://github.com/tomerfiliba-org/rpyc/issues/496.
In my case, it not works well, still finding a way to let playwright sync api work with jupyter now...

**Comment by hkfsc** [comment] 2022-06-29 09:20
@wohenniubi Rpyc will only works if we will not call any playwright sub-modules directly, https://github.com/tomerfiliba-org/rpyc/issues/496.
In my case, it not works well, still finding a way to let playwright sync api work with jupyter now...

**Comment by hkfsc** [comment] 2022-06-29 09:21
@tals Rpyc will only works if we will not call any playwright sub-modules directly, https://github.com/tomerfiliba-org/rpyc/issues/496.
In my case, it not works well, still finding a way to let playwright sync api work with jupyter now...

**Comment by danielichis** [comment] 2022-09-21 02:24
still waiting i want to leave selenium but this stop me

**Comment by ddelange** [comment] 2022-09-21 04:49
If you want to use an async framework (python-playwright is natively async) inside Jupyter Notebooks, the ipykernel maintainer [suggests](https://github.com/ipython/ipykernel/issues/548) to use the async api directly (`await` & `async def` syntax), instead of the sync wrappers. They don't support sync wrappers around async libs...

**Comment by ddelange** [comment] 2022-11-02 16:41
can you try the async snippet _without_ `nest_asyncio`, and post the full error traceback here?

**Comment by ddelange** [comment] 2022-11-02 16:53
this error is coming from `nest_asyncio` ^, can you run it in a fresh kernel without `nest_asyncio`?

**Comment by ddelange** [comment] 2022-11-02 17:27
I have no problem running the [example](https://playwright.dev/python/docs/api/class-browser) on a fresh jupyter server:
<img width="327" alt="image" src="https://user-images.githubusercontent.com/14880945/199559249-088a83aa-f91e-43c9-91f1-2445586d70ae.png">

The fact that your traceback hangs here:

> `--> [121](file:///c%3A/Users/Liu.D.H/AppData/Local/Programs/Python/Python310/lib/site-packages/playwright/_impl/_transport.py?line=120)     self._proc = await asyncio.create_subprocess_exec(`

Makes me think you might not be running in a clean jupyter environment. Maybe vscode does some magic?

**Comment by ddelange** [comment] 2022-11-03 16:14
do you get the same traceback when you run the snippet in ipython instead of jupyter? if yes, we eliminated the ipykernel loop issue, and my next guess would be the fact that you're on windows...

**Comment by ddelange** [comment] 2022-11-03 18:18
potentially indeed your OS ref stackoverflow.com/q/70349876

@mxschmitt would this be caught by the Windows CI?

**Comment by ddelange** [comment] 2022-11-04 07:20
> If you want to use an async framework (playwright-python is natively async) inside Jupyter Notebooks, the ipykernel maintainer [suggests](https://github.com/ipython/ipykernel/issues/548) to use the async api directly (`await` & `async def` syntax), instead of the sync wrappers. They don't support sync wrappers around async libs...

jup it's not allowed

**Comment by ddelange** [comment] 2022-11-05 19:48
I didn't double check, but I'm pretty sure those libraries don't use asyncio under the hood (they may still release the GIL however). For more information on the topic, see https://github.com/ipython/ipykernel/issues/548#issuecomment-713560735.

**Comment by VianneyMI** [comment] 2025-02-05 16:01
![Image](https://github.com/user-attachments/assets/21d2535a-0fae-4cc3-b81d-6a99f1edff10)

**Comment by ddelange** [comment] 2025-02-05 16:25
this ticket was closed in favour of https://github.com/ipython/ipykernel/issues/548

**Comment by VianneyMI** [comment] 2025-02-05 16:28
> this ticket was closed in favour of [ipython/ipykernel#548](https://github.com/ipython/ipykernel/issues/548)

Thanks, argh so no found/implemented solution yet ?

**Comment by VianneyMI** [comment] 2025-02-05 21:36
> 'solution' is to use async_playwright: [#178 (comment)](https://github.com/microsoft/playwright-python/issues/178#issuecomment-1300979205)

This doesn't work on Windows

**Comment by IanTaiAhn** [comment] 2025-04-12 16:51
If you're trying to run playwright asyncio in windows with a conda environment and it's a jupyter notebook, you'll have to use a regular python file instead of *.ipynb. This was the only fix that worked for me.

**Comment by HDembinski** [comment] 2025-10-19 07:29
Here is a workaround that works on Windows.

```py
from playwright.sync_api import sync_playwright
import joblib

def do_something_with_playwright(url: str) -> str:
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        [...]
        return "done"

joblib.Parallel(n_jobs=4)(
    joblib.delayed(do_something_with_playwright)(url) for url in urls
)
```

Works on Windows like a charm. joblib runs the jobs using a process poll, that's why the Jupyter event loop is sidestepped. A normal ProcessPoolExecutor does not work inside a Jupyter notebook on Windows. joblib uses some magic to make it work.
