### ISSUE TITLE
[BUG] Using two browser contexts via a fixture.

### ISSUE THREAD

**Issue by smolkin895** [microsoft/playwright-python#2090] opened 2023-09-27 10:48 UTC
### System info
- Playwright Version: [v1.37.0]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```python
// tests.conftest
import os

import pytest
from playwright.sync_api import Page, expect, sync_playwright

from config import Config
from helper.general import auth_path, get_logged_page
from pages.campaigns_edit import CampaignsEdit

@pytest.fixture(scope="session", autouse=True)
def playwright_configuration():
    expect.set_options(timeout=10_000)

@pytest.fixture(scope="function")
def browser_context_args(browser_context_args):
    return {
        **browser_context_args,
        "storage_state": os.path.join(auth_path, "auth.json"),
    }

@pytest.fixture(scope="session", autouse=True)
def login():
    with sync_playwright() as pw:
        chromium = pw.chromium
        browser = chromium.launch()
        page = browser.new_page()
        account_page = get_logged_page(page)
        account_page.context.storage_state(path=os.path.join(auth_path, "auth.json"))
        browser.close()



@pytest.fixture(scope="function")
def campaigns_edit(page: Page, browser_context_args):
    page.set_viewport_size({"width": 1920, "height": 1080})
    campaigns_edit = CampaignsEdit(page=page)
    yield campaigns_edit
    try:
        if campaigns_edit.name_of_ads:
            campaigns_edit.del_ads()
    except Exception:
        print("РО уже удалено!")



@pytest.fixture(scope='function')
def browser_context_args(browser_context_args):
    return {
        **browser_context_args,
        "storage_state": os.path.join(auth_path, "p_load_images_auth.json"),
    }

@pytest.fixture(scope="session", autouse=True)
def login_p_load_images():
    with sync_playwright() as pw:
        chromium = pw.chromium
        browser = chromium.launch()
        page = browser.new_page()
        account_page = get_logged_page(page,
                                       login=Config.login_load_images_web,
                                       account=Config.pass_load_images_web)
        account_page.context.storage_state(path=os.path.join(auth_path, "p_load_images_auth.json"))
        browser.close()

@pytest.fixture(scope="function")
def p_load_images(page: Page, browser_context_args):
    page.set_viewport_size({"width": 1920, "height": 1080})
    p_load_images = CampaignsEdit(page=page)
    yield p_load_images
    try:
        if p_load_images.name_of_ads:
            p_load_images.del_ads()
    except Exception:
        print("РО уже удалено!")

```

**Steps**
- [Run the test]
- [...]

**Expected**

[Tests using campaigns_edit use their authentication data, and tests with p_load_images use other authentication data]

**Actual**

[All tests use campaigns_edit authentication data]

**Comment by yury-s** [comment] 2023-09-27 18:51
You can use different browser parameters via annotations as specified in [our docs](https://playwright.dev/python/docs/test-runners#fixtures):

```py
@pytest.mark.browser_context_args(storage_state="api.json")
def test_has_title(context):
    pass
```

When you define two functions `browser_context_args` in the same file the later one overrides the former one. 

If you need to use two contexts with different storage state in the same test, you can create the second one manually:

```py
@pytest.mark.browser_context_args(storage_state="state1.json")
def test_has_title(context, browser):
    context2 = browser.new_context(storage_state='state2.json')
    page = context2.new_page()
    page.goto('https://playwright.dev/')
```
Will that work for you? If you must wrap it in a fixture, you can create one with a different name, say `context2` and initialize it with a different storage state.

**Comment by smolkin895** [comment] 2023-09-28 06:59
Then I'll have to annotate each test. I would like to do this in fixtures once rather than repeating this code every time. This is a very likely and obvious scenario for a tester, but it is unclear how to do it through fixtures in one place and reuse it.

**Comment by mxschmitt** [comment] 2023-10-04 14:25
I can reproduce, this is a bug, thanks for reporting!

**Comment by mxschmitt** [comment] 2023-10-09 07:57
You are not using the official `pytest-playwright` plugin, so `pytest.mark.browser_context_arg` won't work. We strongly don't recommend launching again Playwright, instead you can just use the `browser` or `context` fixture inside the places where you need them as shown in the second code snippet in https://github.com/microsoft/playwright-python/issues/2090#issuecomment-1737916093.

You can define `browser_context_args` once in your conftest or inside the test file which will setup defaults for all the tests and then in some places you can use `@pytest.mark.browser_context_args(storage_state="api.json")` to override them, and their context (-> page) in it. Would that work for you? If you need a separate context you can use the `browser` fixture to create a new context with your specific storage state.

Could you maybe share a minimal reproducible so we can run it locally if you think its a bug?

**Comment by mxschmitt** [comment] 2023-10-22 15:30
Closing as per above. Please re-file for further questions, since we don't monitor closed issues, thanks!

**Closed by mxschmitt** 2023-10-22 15:30 UTC
Labels: triaging
