### ISSUE TITLE
[BUG] download images make the main code delayed.. 

### ISSUE THREAD

**Issue by hhk22** [microsoft/playwright-python#1794] opened 2023-03-02 05:55 UTC
**Context:**
- Playwright Version: 1.30.0
- Operating System: Mac
- Python version: 3.9.11
- Browser: chromium

```python

import asyncio
import time
import playwright
from playwright.async_api import async_playwright


async def _save_image_from_response(res):
    try:
        s = time.time()
        print('img loading start...', res.url)
        await res.body()
        print('img loading done ...', time.time() - s, res.url)

    except playwright._impl._api_types.Error:
        pass


async def main():
    async with async_playwright() as p:
        browser = await p.chromium.launch()
        page = await browser.new_page()
        page.on('response', _save_image_from_response)
        await page.goto("https://www.xexymix.com/shop/shopdetail.html?branduid=2064856&xcode=008&mcode=003&scode=&special=7&GfDT=bW13Vg%3D%3D")

        s = time.time()
        print('evaluate start')
        await page.evaluate("() => {}")
        print('evaluate finished ', time.time() - s)

        await page.wait_for_timeout(1000)

        print('finished')

        await browser.close()


asyncio.run(main())

```

Downloading big images make the main code delayed. 
From my understanding, downloading big image, bigger than 5MB and image/gif type, makding the code delay. 
So, even very very simple code like `page.evaluate('() => {}')` takes 20seconds. 

Here is my console to describe details. 

> evaluate start
> img loading start... <src1>
> img loading start... <src2>
> img loading start... <src3>
> ....
> ....... do not showing any logs for 15 seconds .......
> img loading done ... 19.716237783432007 https://xexymix.jpg3.kr/xexymix/img/XP/2023/9224h/06/xp9224h_f2.gif
> img loading done ... 19sec <src2>
> img loading done ... 23sec <src3>
> ....
> evaluate finished ---> might take 25 - 30 seconds. 

-------------------

I want to process the main code normally
and download images from responses not interuppting main code processing.

**Comment by mxschmitt** [comment] 2023-03-02 11:46
It sounds expected that if you sniff all the requests, that the total page load duration will be higher.

Regarding the page.evaluate issue, I was not able to reproduce it, for me it was not slow:

evaluate start
evaluate finished  0.00803518295288086 aka. 8ms which sounds reasonable.

I was on macOS but Python 3.11, maybe it makes a difference.

**Comment by Hyeoghwan** [comment] 2023-03-03 03:36
Did you test with the given url? 
I tested the code with python 3.11, but still making problems. 

evaluate start
evaluate finished 16.x seconds

I ran the similar code on puppeteer library(js)
On that environment, the page load duration is not that higher as python.. 

Could you test the code with the given url?? and if slow, any ideas for it?

**Comment by mxschmitt** [comment] 2023-03-03 13:41
I was running the same snippet which you provided. You could try using the Node.js library which the Python version uses under the hood, so we know if this is a Playwright Python issue or more a general Playwright issue, see [here](https://playwright.dev/docs/library#usage).

You could also try running it with `DEBUGP=1` env var which will print debug logs between Python and Node.js. Or set `DEBUG=pw:protocol` which will print the logs between Node.js and Chromium.

I'd start with trying to reproduce it on Node.js, if its persistent there, set DEBUG=pw:protocol and upload the logs to eg. a Gist then we can see whats happening.

(Since we can't reproduce, I'm providing more general guidance, so we know what makes evaluate slow)

**Comment by Hyeoghwan** [comment] 2023-03-06 01:54
I tested with similar code on node.js
playwright: 1.31.2
node.js: v18.10.0 

and my node.js code

```
const { chromium } = require('playwright');

(async () => {
  s = new Date();
  const browser = await chromium.launch();
  const page = await browser.newPage();

  page.on('response', async (res) => {
    try {
        s = new Date();
        console.log(res.url())
        await res.body();
        console.log(res.url(), (new Date()- s)/1000);
    } catch (e) {
        //
    }
  })
  await page.goto('https://www.xexymix.com/shop/shopdetail.html?branduid=2064856&xcode=008&mcode=003&scode=&special=7&GfDT=bW13Vg%3D%3D');

  s = new Date();
  console.log('evaluate start');
  await page.evaluate(() => {});
  console.log('evaluate finished', (new Date() - s)/1000)
  await browser.close();

  console.log((new Date() - s)/1000)
})();
```

it's really fast. and any no delays. 
The elapsed time for the nodejs code is 0.098sec

But the python code takes 0.39 on average.
And i ran the python code, sometimes if hangs on evalaute code, but not always. 

and I ran the code with DEBUGP=1 and DEBUG=pw:protocol to know what contents are interacted between python and noejs and chromium. But it's hard to debug... too many logs, specifically, the body content.. 

just wondering.. is the problem related to python async/await?? or am i handling with the asnyc/await(page.on) in the wrong way?
```
page.on('response', _save_image_from_response)

# page.on('response', lambda x: asyncio.create_task(_save_image_from_response(x))) <- also delayed. 

```

Is there more simple ways to debug using DEBUGP=1 and DEBUG=pw:protocol, I will try. 
Thx.

**Comment by mxschmitt** [comment] 2023-03-06 18:32
When we are about to issue evaluation responses, we already have a lot of pending responses for image fetch that need to return to the client first. Hence the time between evaluate and its end is affected.

Try serialising the operations, by first navigating and appending the responses to an array, then process the responses and then evaluate. Then it will be fast.

See this snippet:

```py
async def main():
    async with async_playwright() as p:
        browser = await p.chromium.launch()
        page = await browser.new_page()

        resources = []
        page.on('response', lambda res: resources.append(res))

        s = time.time()
        await page.goto("https://www.xexymix.com/shop/shopdetail.html?branduid=2064856&xcode=008&mcode=003&scode=&special=7&GfDT=bW13Vg%3D%3D")
        print('goto finished', time.time() - s)

        s = time.time()
        for res in resources:
            try:
                await res.body()
            except Exception as e:
                pass
        print('body finished', time.time() - s)

        s = time.time()
        print('evaluate start')
        await page.evaluate("() => {}")
        print('evaluate finished ', time.time() - s)

        await page.wait_for_timeout(1000)

        print('finished')

        await browser.close()


asyncio.run(main())
```

**Comment by mxschmitt** [comment] 2023-03-13 08:39
closing as per above, batching is our recommended approach.

**Comment by Hyeoghwan** [comment] 2023-03-14 09:49
thanks. it's a bit slow.. but i will go with this concept.

**Closed** 2023-03-14 10:41 UTC
Labels: triaging
