### ISSUE TITLE
Is this issues?

### ISSUE THREAD

**Issue by ssdd123456** [microsoft/playwright-python#700] opened 2021-05-17 13:57 UTC
First, I start chrome.exe with args=["--remote-debugging-port=9222"].
Then I use browser_type.connect_over_cdp("http://localhost:9222") to connect it.
Then I get the page via cdp_browser.contexts[0].pages.
But the len(cdp_browser.contexts[0].pages)=0?
After I use cdp_browser.contexts[0].new_page().
len(cdp_browser.contexts[0].pages) return the actual number?
Is this issues?
This is codes:
cdp_browser = await browser_type.connect_over_cdp("http://localhost:9222")
context = await cdp_browser.contexts[0]
print(len(context.pages))
page = await context.new_page()
print(len(context.pages))

**Comment by JoelEinbinder** [comment] 2021-05-17 20:15
Yes, this is a bug that is being fixed shortly in an update. Duplicate of #679

**Closed by JoelEinbinder** 2021-05-17 20:15 UTC
