### ISSUE TITLE
[BUG]/opt/conda/envs/py38/lib/python3.8/site-packages/playwright/driver/node: /usr/lib/libstdc++.so.6: no version information available

### ISSUE THREAD

**Issue by 2424004764** [microsoft/playwright-python#2219] opened 2024-01-02 08:35 UTC
Existing issues have been searched and include those that have been closed. There is currently no solution and the latest playwright is being used

### System info
- Playwright Version: Latest
- Operating System: apline
- Browser: apline
- Other info:

### Source code

I can install playwright in APLINE, but when I execute playwright, I get an error message

i input command:
playwright

**Comment by mxschmitt** [comment] 2024-01-02 08:36
Duplicate of https://github.com/microsoft/playwright-python/issues/2218#issuecomment-1873732177.

This Linux distribution is not supported, we recommend using supported Linux distributions like Ubuntu or Debian.

**Closed by mxschmitt** 2024-01-02 08:36 UTC
