### ISSUE TITLE
[Question]:  Timeout 30000.0ms exceeded while waiting for event "download"

### ISSUE THREAD

**Issue by ww1223708191** [microsoft/playwright-python#1419] opened 2022-07-09 04:01 UTC
### Your question

when  I  run this download demo with python, “Timeout 30000.0ms exceeded while waiting for event "download"" this error occurs,but I don't known how to locate the problem or solve this problem.
![image](https://user-images.githubusercontent.com/34846727/178090982-14055719-fee2-4d6a-9dd4-e0be9e56afe9.png)

**Comment by rwoll** [comment] 2022-07-12 16:01
Thanks for the report! Can you share a repro and the site under test? The tests internally pass—maybe there is no download caused by the click in your particular site? You can run in Debug mode `PWDEBUG=1` and/or [record a trace](https://playwright.dev/python/docs/trace-viewer) to see look further.

**Comment by ww1223708191** [comment] 2022-07-14 11:35
> Thanks for the report! Can you share a repro and the site under test? The tests internally pass—maybe there is no download caused by the click in your particular site? You can run in Debug mode `PWDEBUG=1` and/or [record a trace](https://playwright.dev/python/docs/trace-viewer) to see look further.

when  I

> Thanks for the report! Can you share a repro and the site under test? The tests internally pass—maybe there is no download caused by the click in your particular site? You can run in Debug mode `PWDEBUG=1` and/or [record a trace](https://playwright.dev/python/docs/trace-viewer) to see look further.

thank you for your reply,when I debug this test case, I found  successfully download file ,but terminal has this error stack.
task = <Future finished exception=TimeoutError('Timeout 30000.0ms exceeded while waiting for event "download"\n==============...========================\nwaiting for event "download"\n================================================
============')>

    def done_callback(task: "asyncio.Future[T]") -> None:
        try:
>           self._value = mapping.from_maybe_impl(self._future.result())
E           playwright._impl._api_types.TimeoutError: Timeout 30000.0ms exceeded while waiting for event "download"
E           =========================== logs ===========================
E           waiting for event "download"
E           ============================================================

**Comment by ww1223708191** [comment] 2022-07-15 02:00
Sorry, sensitive information such as accounts cannot be provided, but you can access https://console.huaweicloud.com/ecm/.
![image](https://user-images.githubusercontent.com/34846727/179131724-79fd8937-cbf4-49cd-9588-c0ca7f256e74.png)

**Comment by rwoll** [comment] 2022-07-18 18:52
Hi, @ww1223708191. Unfortunately it's out of scope for me to create an account for this site. Can you try sharing a trace instead? https://playwright.dev/docs/api/class-tracing

You can email it to `<username>@microsoft.com`. Replace `<username>` with `rosswollman`.

**Comment by rwoll** [comment] 2022-07-20 19:38
Closing as part of triage, but please comment once the items are sent and I'll re-open.

Cheers!

**Closed by rwoll** 2022-07-20 19:38 UTC
Labels: triaging

**Comment by syx-ixuzhi** [comment] 2023-03-01 19:38
with page.expect_download(timeout=100000) as download_info:

try this.
