### ISSUE TITLE
Playwright not working with Pyinstaller

### ISSUE THREAD

**Issue by analogaio** [microsoft/playwright-python#255] opened 2020-10-28 19:24 UTC
When building with Pyinstaller, the script will fail to start. 

`Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "test.py", line 12, in start
  File "playwright\__init__.py", line 34, in sync_playwright
  File "playwright\main.py", line 81, in __init__
  File "playwright\main.py", line 76, in run_driver
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "playwright\main.py", line 56, in run_driver_async
  File "asyncio\subprocess.py", line 236, in create_subprocess_exec
  File "asyncio\base_events.py", line 1630, in subprocess_exec
  File "asyncio\windows_events.py", line 385, in _make_subprocess_transport
  File "asyncio\base_subprocess.py", line 36, in __init__
  File "asyncio\windows_events.py", line 881, in _start
  File "asyncio\windows_utils.py", line 153, in __init__
  File "subprocess.py", line 854, in __init__
  File "subprocess.py", line 1307, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified`

That is without --onefile ^. If I build it with --onefile it ends with an assertion error.

**Comment by pavelfeldman** [comment] 2020-10-29 16:25
That's expected, Playwright is using binaries that need to be bundled, extracted and handled with care.

**Comment by analogaio** [comment] 2020-11-01 13:22
> That's expected, Playwright is using binaries that need to be bundled, extracted and handled with care.

Would you be able to help me get it to work with Pyinstaller by any chance?

**Comment by analogaio** [comment] 2020-11-19 17:09
Bump

**Comment by tumregels** [comment] 2020-12-04 18:09
@analogaio - a solution is proposed at [342](https://github.com/microsoft/playwright-python/issues/342)

**Comment by pavelfeldman** [comment] 2020-12-19 00:56
Closing as a dupe of #342 that has more info.

**Closed by pavelfeldman** 2020-12-19 00:56 UTC
Labels: P3-collecting-feedback
