### ISSUE TITLE
Playwright and pyinstaller

### ISSUE THREAD

**Issue by Sharkyyy3** [microsoft/playwright-python#311] opened 2020-11-20 08:46 UTC
windows 10 x64
python 3.8.1
pyinstaller 4.0
playwright 0.152.0

My cod:
```
from playwright import sync_playwright
playwright = None
def get_playwright():
    if playwright == None:
        try:
            playwright = sync_playwright().start()
            print(playwright)
        except Exception as e:
            raise e
    return playwright

get_playwright()
```

Packing with command "pyinstaller -F main.py"

```
Traceback при запуске:
Traceback (most recent call last): 
   File "main.py", line 19, in get_playwright 
   File "playwright\__init__.py", line 34, in sync_playwright 
   File "playwright\main.py", line 81, in __init__ 
   File "playwright\main.py", line 76, in run_driver 
   File "asyncio\base_events.py", line 612, in run_until_complete 
   File "playwright\main.py", line 44, in run_driver_async 
   File "playwright\main.py", line 36, in compute_driver_executable 
   File "playwright\path_utils.py", line 23, in get_file_dirname 
AssertionError
[12388] Failed to execute script main
```

Actually if don't pack it there are no errors:
`<playwright.playwright.Playwright object at 0x00000278C0267760>`

**Comment by kumaraditya303** [comment] 2020-11-20 09:16
Duplicate of #255 
Playwright internally uses binaries such as playwright-cli and browser binaries and need to be bundled to work.

**Comment by Sharkyyy3** [comment] 2020-11-20 10:53
> Duplicate of #255
> Playwright internally uses binaries such as playwright-cli and browser binaries and need to be bundled to work.

Can you tell, what I need to do? Do I need to use a special flag in pyinstaller?

**Comment by kumaraditya303** [comment] 2020-11-21 11:02
> > Duplicate of #255
> > Playwright internally uses binaries such as playwright-cli and browser binaries and need to be bundled to work.
> 
> Can you tell, what I need to do? Do I need to use a special flag in pyinstaller?

It is not possible because pyinstaller unpacks the binaries in a temporary folder and hence the path would always change hence it isn't possible

**Comment by Sharkyyy3** [comment] 2020-11-21 11:48
> > > Duplicate of #255
> > > Playwright internally uses binaries such as playwright-cli and browser binaries and need to be bundled to work.
> > 
> > 
> > Can you tell, what I need to do? Do I need to use a special flag in pyinstaller?
> 
> It is not possible because pyinstaller unpacks the binaries in a temporary folder and hence the path would always change hence it isn't possible

Is there a workaround?

**Comment by pavelfeldman** [comment] 2020-11-21 17:40
Folding into #255

**Closed by pavelfeldman** 2020-11-21 17:40 UTC

**Comment by tumregels** [comment] 2020-12-04 18:12
@Sharkyyy3 @kumaraditya303 - a solution is proposed at [342](https://github.com/microsoft/playwright-python/issues/342)
